import OCaml.Vm.Primitives.AccessPlan
import OCaml.Vm.Primitives.Call
import OCaml.Vm.Primitives.DoubleAllocation
import OCaml.Vm.Primitives.SymbolicAppend
import Vsa.Sim.ChainFactsTac
import Vsa.Sim.Code.__call_exitprocs
import Vsa.Sim.ElfDecode.Part002
import Vsa.Sim.ElfDecode.Part005
import Vsa.Sim.ElfDecode.Part006
import Vsa.Sim.ElfDecode.Part007
import Vsa.Sim.ElfDecode.Part009
import Vsa.Sim.ElfDecode.Part010
import Vsa.Sim.ElfDecode.Part011
import Vsa.Sim.ElfDecode.Part014
import Vsa.Sim.ElfDecode.Part015
import Vsa.Sim.ElfDecode.Part017
import Vsa.Sim.ElfDecode.Part023
import Vsa.Sim.ElfDecode.Part029
import Vsa.Sim.ElfDecode.Part031
import Vsa.Sim.ElfDecode.Part032
import Vsa.Sim.ElfDecode.Part045
import Vsa.Sim.ElfDecode.Part047
import Vsa.Sim.ElfDecode.Part049
import Vsa.Sim.ElfDecode.Part051
import Vsa.Sim.ElfDecode.Part053
import Vsa.Sim.ElfDecode.Part058
import Vsa.Sim.ElfDecode.Part059
import Vsa.Sim.ElfDecode.Part061
import Vsa.Sim.ElfDecode.Part065
import Vsa.Sim.ElfDecode.Part066
import Vsa.Sim.ElfDecode.Part067
import Vsa.Sim.ElfDecode.Part070
import Vsa.Sim.ElfDecode.Part074
import Vsa.Sim.ElfDecode.Part076
import Vsa.Sim.ElfDecode.Part077
import Vsa.Sim.ElfDecode.Part079
import Vsa.Sim.ElfDecode.Part081
import Vsa.Sim.ElfDecode.Part082
import Vsa.Sim.ElfDecode.Part084
import Vsa.Sim.ElfDecode.Part085
import Vsa.Sim.ElfDecode.Part086
import Vsa.Sim.ElfDecode.Part092
import Vsa.Sim.ElfDecode.Part095
import Vsa.Sim.ElfDecode.Part100
import Vsa.Sim.ElfDecode.Part106
import Vsa.Sim.ElfDecode.Part119
import Vsa.Sim.ElfDecode.Part120
import Vsa.Sim.ElfDecode.Part129
import Vsa.Sim.ElfDecode.Part130
import Vsa.Sim.ElfDecode.Part186
import Vsa.Sim.ElfDecode.Part208
import Vsa.Sim.ElfDecode.Part209
import Vsa.Sim.ElfDecode.Part210
import Vsa.Sim.ElfDecode.Part211
import Vsa.Sim.ElfDecode.Part212
import Vsa.Sim.ElfDecode.Part214
import Vsa.Sim.ElfDecode.Part215
import Vsa.Sim.ElfDecode.Part216
import Vsa.Sim.ElfDecode.Part220
import Vsa.Sim.ElfDecode.Part224
import Vsa.Sim.ElfDecode.Part225
import Vsa.Sim.ElfDecode.Part227
import Vsa.Sim.ElfDecode.Part228
import Vsa.Sim.ElfDecode.Part229

/-! GENERATED by scripts/syi/gen_fn.py --ocaml-exit. -/
namespace OCaml.Vm.Primitives.ExitPath.ExitProcs
open Vsa.Machine Vsa.Sim LeanRV64DExecutable

theorem loaded {c : Config} (h : ExecutableImage c) : Vsa.Sim.Code.__call_exitprocsLoaded c.σ.mem := by
  unfold Vsa.Sim.Code.__call_exitprocsLoaded Vsa.Sim.Code.__call_exitprocsChunk0 Vsa.Sim.Code.__call_exitprocsChunk1 Vsa.Sim.Code.__call_exitprocsChunk2 Vsa.Sim.Code.__call_exitprocsChunk3 Vsa.Sim.Code.__call_exitprocsChunk4 Vsa.Sim.Code.__call_exitprocsChunk5
  repeat' apply And.intro
  · have hb := h.text 273704 (by decide)
    have he : Image.textByte 273704 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273705 (by decide)
    have he : Image.textByte 273705 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273706 (by decide)
    have he : Image.textByte 273706 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273707 (by decide)
    have he : Image.textByte 273707 = 0xfa#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273708 (by decide)
    have he : Image.textByte 273708 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273709 (by decide)
    have he : Image.textByte 273709 = 0x3c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273710 (by decide)
    have he : Image.textByte 273710 = 0x71#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273711 (by decide)
    have he : Image.textByte 273711 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273712 (by decide)
    have he : Image.textByte 273712 = 0x97#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273713 (by decide)
    have he : Image.textByte 273713 = 0x2b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273714 (by decide)
    have he : Image.textByte 273714 = 0x02#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273715 (by decide)
    have he : Image.textByte 273715 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273716 (by decide)
    have he : Image.textByte 273716 = 0x93#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273717 (by decide)
    have he : Image.textByte 273717 = 0x8b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273718 (by decide)
    have he : Image.textByte 273718 = 0x0b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273719 (by decide)
    have he : Image.textByte 273719 = 0xbd#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273720 (by decide)
    have he : Image.textByte 273720 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273721 (by decide)
    have he : Image.textByte 273721 = 0x30#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273722 (by decide)
    have he : Image.textByte 273722 = 0x61#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273723 (by decide)
    have he : Image.textByte 273723 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273724 (by decide)
    have he : Image.textByte 273724 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273725 (by decide)
    have he : Image.textByte 273725 = 0x0b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273726 (by decide)
    have he : Image.textByte 273726 = 0x05#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273727 (by decide)
    have he : Image.textByte 273727 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273728 (by decide)
    have he : Image.textByte 273728 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273729 (by decide)
    have he : Image.textByte 273729 = 0xb5#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273730 (by decide)
    have he : Image.textByte 273730 = 0x0b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273731 (by decide)
    have he : Image.textByte 273731 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273732 (by decide)
    have he : Image.textByte 273732 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273733 (by decide)
    have he : Image.textByte 273733 = 0x38#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273734 (by decide)
    have he : Image.textByte 273734 = 0x41#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273735 (by decide)
    have he : Image.textByte 273735 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273736 (by decide)
    have he : Image.textByte 273736 = 0x17#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273737 (by decide)
    have he : Image.textByte 273737 = 0x2a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273738 (by decide)
    have he : Image.textByte 273738 = 0x02#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273739 (by decide)
    have he : Image.textByte 273739 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273740 (by decide)
    have he : Image.textByte 273740 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273741 (by decide)
    have he : Image.textByte 273741 = 0x0a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273742 (by decide)
    have he : Image.textByte 273742 = 0x8a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273743 (by decide)
    have he : Image.textByte 273743 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273744 (by decide)
    have he : Image.textByte 273744 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273745 (by decide)
    have he : Image.textByte 273745 = 0x30#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273746 (by decide)
    have he : Image.textByte 273746 = 0x21#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273747 (by decide)
    have he : Image.textByte 273747 = 0x05#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273748 (by decide)
    have he : Image.textByte 273748 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273749 (by decide)
    have he : Image.textByte 273749 = 0x38#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273750 (by decide)
    have he : Image.textByte 273750 = 0x81#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273751 (by decide)
    have he : Image.textByte 273751 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273752 (by decide)
    have he : Image.textByte 273752 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273753 (by decide)
    have he : Image.textByte 273753 = 0x3c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273754 (by decide)
    have he : Image.textByte 273754 = 0x11#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273755 (by decide)
    have he : Image.textByte 273755 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273756 (by decide)
    have he : Image.textByte 273756 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273757 (by decide)
    have he : Image.textByte 273757 = 0x8c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273758 (by decide)
    have he : Image.textByte 273758 = 0x05#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273759 (by decide)
    have he : Image.textByte 273759 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273760 (by decide)
    have he : Image.textByte 273760 = 0xef#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273761 (by decide)
    have he : Image.textByte 273761 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273762 (by decide)
    have he : Image.textByte 273762 = 0x8f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273763 (by decide)
    have he : Image.textByte 273763 = 0xfd#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273764 (by decide)
    have he : Image.textByte 273764 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273765 (by decide)
    have he : Image.textByte 273765 = 0x39#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273766 (by decide)
    have he : Image.textByte 273766 = 0x0a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273767 (by decide)
    have he : Image.textByte 273767 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273768 (by decide)
    have he : Image.textByte 273768 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273769 (by decide)
    have he : Image.textByte 273769 = 0x0e#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273770 (by decide)
    have he : Image.textByte 273770 = 0x09#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273771 (by decide)
    have he : Image.textByte 273771 = 0x08#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273772 (by decide)
    have he : Image.textByte 273772 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273773 (by decide)
    have he : Image.textByte 273773 = 0x3c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273774 (by decide)
    have he : Image.textByte 273774 = 0x31#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273775 (by decide)
    have he : Image.textByte 273775 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273776 (by decide)
    have he : Image.textByte 273776 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273777 (by decide)
    have he : Image.textByte 273777 = 0x34#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273778 (by decide)
    have he : Image.textByte 273778 = 0x51#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273779 (by decide)
    have he : Image.textByte 273779 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273780 (by decide)
    have he : Image.textByte 273780 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273781 (by decide)
    have he : Image.textByte 273781 = 0x38#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273782 (by decide)
    have he : Image.textByte 273782 = 0x81#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273783 (by decide)
    have he : Image.textByte 273783 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273784 (by decide)
    have he : Image.textByte 273784 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273785 (by decide)
    have he : Image.textByte 273785 = 0x34#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273786 (by decide)
    have he : Image.textByte 273786 = 0x91#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273787 (by decide)
    have he : Image.textByte 273787 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273788 (by decide)
    have he : Image.textByte 273788 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273789 (by decide)
    have he : Image.textByte 273789 = 0x34#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273790 (by decide)
    have he : Image.textByte 273790 = 0x91#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273791 (by decide)
    have he : Image.textByte 273791 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273792 (by decide)
    have he : Image.textByte 273792 = 0x93#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273793 (by decide)
    have he : Image.textByte 273793 = 0x09#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273794 (by decide)
    have he : Image.textByte 273794 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273795 (by decide)
    have he : Image.textByte 273795 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273796 (by decide)
    have he : Image.textByte 273796 = 0x93#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273797 (by decide)
    have he : Image.textByte 273797 = 0x0a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273798 (by decide)
    have he : Image.textByte 273798 = 0x10#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273799 (by decide)
    have he : Image.textByte 273799 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273800 (by decide)
    have he : Image.textByte 273800 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273801 (by decide)
    have he : Image.textByte 273801 = 0x24#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273802 (by decide)
    have he : Image.textByte 273802 = 0x89#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273803 (by decide)
    have he : Image.textByte 273803 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273804 (by decide)
    have he : Image.textByte 273804 = 0x1b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273805 (by decide)
    have he : Image.textByte 273805 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273806 (by decide)
    have he : Image.textByte 273806 = 0xf4#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273807 (by decide)
    have he : Image.textByte 273807 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273808 (by decide)
    have he : Image.textByte 273808 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273809 (by decide)
    have he : Image.textByte 273809 = 0x40#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273810 (by decide)
    have he : Image.textByte 273810 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273811 (by decide)
    have he : Image.textByte 273811 = 0x06#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273812 (by decide)
    have he : Image.textByte 273812 = 0x93#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273813 (by decide)
    have he : Image.textByte 273813 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273814 (by decide)
    have he : Image.textByte 273814 = 0x09#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273815 (by decide)
    have he : Image.textByte 273815 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273816 (by decide)
    have he : Image.textByte 273816 = 0x93#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273817 (by decide)
    have he : Image.textByte 273817 = 0x17#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273818 (by decide)
    have he : Image.textByte 273818 = 0x34#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273819 (by decide)
    have he : Image.textByte 273819 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273820 (by decide)
    have he : Image.textByte 273820 = 0xb3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273821 (by decide)
    have he : Image.textByte 273821 = 0x84#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273822 (by decide)
    have he : Image.textByte 273822 = 0xf4#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273823 (by decide)
    have he : Image.textByte 273823 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273824 (by decide)
    have he : Image.textByte 273824 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273825 (by decide)
    have he : Image.textByte 273825 = 0x14#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273826 (by decide)
    have he : Image.textByte 273826 = 0x0c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273827 (by decide)
    have he : Image.textByte 273827 = 0x08#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273828 (by decide)
    have he : Image.textByte 273828 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273829 (by decide)
    have he : Image.textByte 273829 = 0x27#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273830 (by decide)
    have he : Image.textByte 273830 = 0x89#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273831 (by decide)
    have he : Image.textByte 273831 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273832 (by decide)
    have he : Image.textByte 273832 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273833 (by decide)
    have he : Image.textByte 273833 = 0xb6#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273834 (by decide)
    have he : Image.textByte 273834 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273835 (by decide)
    have he : Image.textByte 273835 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273836 (by decide)
    have he : Image.textByte 273836 = 0x9b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273837 (by decide)
    have he : Image.textByte 273837 = 0x87#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273838 (by decide)
    have he : Image.textByte 273838 = 0xf7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273839 (by decide)
    have he : Image.textByte 273839 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273840 (by decide)
    have he : Image.textByte 273840 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273841 (by decide)
    have he : Image.textByte 273841 = 0x88#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273842 (by decide)
    have he : Image.textByte 273842 = 0x87#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273843 (by decide)
    have he : Image.textByte 273843 = 0x0c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273844 (by decide)
    have he : Image.textByte 273844 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273845 (by decide)
    have he : Image.textByte 273845 = 0xb0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273846 (by decide)
    have he : Image.textByte 273846 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273847 (by decide)
    have he : Image.textByte 273847 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273848 (by decide)
    have he : Image.textByte 273848 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273849 (by decide)
    have he : Image.textByte 273849 = 0x86#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273850 (by decide)
    have he : Image.textByte 273850 = 0x06#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273851 (by decide)
    have he : Image.textByte 273851 = 0x02#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273852 (by decide)
    have he : Image.textByte 273852 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273853 (by decide)
    have he : Image.textByte 273853 = 0x27#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273854 (by decide)
    have he : Image.textByte 273854 = 0x09#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273855 (by decide)
    have he : Image.textByte 273855 = 0x31#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273856 (by decide)
    have he : Image.textByte 273856 = 0x3b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273857 (by decide)
    have he : Image.textByte 273857 = 0x97#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273858 (by decide)
    have he : Image.textByte 273858 = 0x8a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273859 (by decide)
    have he : Image.textByte 273859 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273860 (by decide)
    have he : Image.textByte 273860 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273861 (by decide)
    have he : Image.textByte 273861 = 0x2c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273862 (by decide)
    have he : Image.textByte 273862 = 0x89#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273863 (by decide)
    have he : Image.textByte 273863 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273864 (by decide)
    have he : Image.textByte 273864 = 0xb3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273865 (by decide)
    have he : Image.textByte 273865 = 0xf7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273866 (by decide)
    have he : Image.textByte 273866 = 0xe7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273867 (by decide)
    have he : Image.textByte 273867 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273868 (by decide)
    have he : Image.textByte 273868 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273869 (by decide)
    have he : Image.textByte 273869 = 0x92#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273870 (by decide)
    have he : Image.textByte 273870 = 0x07#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273871 (by decide)
    have he : Image.textByte 273871 = 0x08#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273872 (by decide)
    have he : Image.textByte 273872 = 0xe7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273873 (by decide)
    have he : Image.textByte 273873 = 0x80#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273874 (by decide)
    have he : Image.textByte 273874 = 0x06#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273875 (by decide)
    have he : Image.textByte 273875 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273876 (by decide)
    have he : Image.textByte 273876 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273877 (by decide)
    have he : Image.textByte 273877 = 0x27#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273878 (by decide)
    have he : Image.textByte 273878 = 0x89#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273879 (by decide)
    have he : Image.textByte 273879 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273880 (by decide)
    have he : Image.textByte 273880 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273881 (by decide)
    have he : Image.textByte 273881 = 0x37#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273882 (by decide)
    have he : Image.textByte 273882 = 0x0a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273883 (by decide)
    have he : Image.textByte 273883 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273884 (by decide)
    have he : Image.textByte 273884 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273885 (by decide)
    have he : Image.textByte 273885 = 0x1c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273886 (by decide)
    have he : Image.textByte 273886 = 0x97#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273887 (by decide)
    have he : Image.textByte 273887 = 0x09#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273888 (by decide)
    have he : Image.textByte 273888 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273889 (by decide)
    have he : Image.textByte 273889 = 0x9a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273890 (by decide)
    have he : Image.textByte 273890 = 0x27#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273891 (by decide)
    have he : Image.textByte 273891 = 0x09#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273892 (by decide)
    have he : Image.textByte 273892 = 0x1b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273893 (by decide)
    have he : Image.textByte 273893 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273894 (by decide)
    have he : Image.textByte 273894 = 0xf4#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273895 (by decide)
    have he : Image.textByte 273895 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273896 (by decide)
    have he : Image.textByte 273896 = 0x93#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273897 (by decide)
    have he : Image.textByte 273897 = 0x84#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273898 (by decide)
    have he : Image.textByte 273898 = 0x84#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273899 (by decide)
    have he : Image.textByte 273899 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273900 (by decide)
    have he : Image.textByte 273900 = 0xe3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273901 (by decide)
    have he : Image.textByte 273901 = 0x1a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273902 (by decide)
    have he : Image.textByte 273902 = 0x34#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273903 (by decide)
    have he : Image.textByte 273903 = 0xfb#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273904 (by decide)
    have he : Image.textByte 273904 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273905 (by decide)
    have he : Image.textByte 273905 = 0x34#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273906 (by decide)
    have he : Image.textByte 273906 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273907 (by decide)
    have he : Image.textByte 273907 = 0x05#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273908 (by decide)
    have he : Image.textByte 273908 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273909 (by decide)
    have he : Image.textByte 273909 = 0x34#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273910 (by decide)
    have he : Image.textByte 273910 = 0x81#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273911 (by decide)
    have he : Image.textByte 273911 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273912 (by decide)
    have he : Image.textByte 273912 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273913 (by decide)
    have he : Image.textByte 273913 = 0x39#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273914 (by decide)
    have he : Image.textByte 273914 = 0x81#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273915 (by decide)
    have he : Image.textByte 273915 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273916 (by decide)
    have he : Image.textByte 273916 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273917 (by decide)
    have he : Image.textByte 273917 = 0x3a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273918 (by decide)
    have he : Image.textByte 273918 = 0x81#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273919 (by decide)
    have he : Image.textByte 273919 = 0x02#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273920 (by decide)
    have he : Image.textByte 273920 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273921 (by decide)
    have he : Image.textByte 273921 = 0x3c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273922 (by decide)
    have he : Image.textByte 273922 = 0x81#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273923 (by decide)
    have he : Image.textByte 273923 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273924 (by decide)
    have he : Image.textByte 273924 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273925 (by decide)
    have he : Image.textByte 273925 = 0xb5#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273926 (by decide)
    have he : Image.textByte 273926 = 0x0b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273927 (by decide)
    have he : Image.textByte 273927 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273928 (by decide)
    have he : Image.textByte 273928 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273929 (by decide)
    have he : Image.textByte 273929 = 0x30#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273930 (by decide)
    have he : Image.textByte 273930 = 0x81#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273931 (by decide)
    have he : Image.textByte 273931 = 0x05#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273932 (by decide)
    have he : Image.textByte 273932 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273933 (by decide)
    have he : Image.textByte 273933 = 0x39#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273934 (by decide)
    have he : Image.textByte 273934 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273935 (by decide)
    have he : Image.textByte 273935 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273936 (by decide)
    have he : Image.textByte 273936 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273937 (by decide)
    have he : Image.textByte 273937 = 0x3a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273938 (by decide)
    have he : Image.textByte 273938 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273939 (by decide)
    have he : Image.textByte 273939 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273940 (by decide)
    have he : Image.textByte 273940 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273941 (by decide)
    have he : Image.textByte 273941 = 0x3b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273942 (by decide)
    have he : Image.textByte 273942 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273943 (by decide)
    have he : Image.textByte 273943 = 0x02#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273944 (by decide)
    have he : Image.textByte 273944 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273945 (by decide)
    have he : Image.textByte 273945 = 0x3b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273946 (by decide)
    have he : Image.textByte 273946 = 0x81#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273947 (by decide)
    have he : Image.textByte 273947 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273948 (by decide)
    have he : Image.textByte 273948 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273949 (by decide)
    have he : Image.textByte 273949 = 0x3c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273950 (by decide)
    have he : Image.textByte 273950 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273951 (by decide)
    have he : Image.textByte 273951 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273952 (by decide)
    have he : Image.textByte 273952 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273953 (by decide)
    have he : Image.textByte 273953 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273954 (by decide)
    have he : Image.textByte 273954 = 0x01#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273955 (by decide)
    have he : Image.textByte 273955 = 0x06#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273956 (by decide)
    have he : Image.textByte 273956 = 0x6f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273957 (by decide)
    have he : Image.textByte 273957 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273958 (by decide)
    have he : Image.textByte 273958 = 0xcf#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273959 (by decide)
    have he : Image.textByte 273959 = 0xf2#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273960 (by decide)
    have he : Image.textByte 273960 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273961 (by decide)
    have he : Image.textByte 273961 = 0xb7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273962 (by decide)
    have he : Image.textByte 273962 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273963 (by decide)
    have he : Image.textByte 273963 = 0x20#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273964 (by decide)
    have he : Image.textByte 273964 = 0x1b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273965 (by decide)
    have he : Image.textByte 273965 = 0x07#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273966 (by decide)
    have he : Image.textByte 273966 = 0xf4#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273967 (by decide)
    have he : Image.textByte 273967 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273968 (by decide)
    have he : Image.textByte 273968 = 0xe3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273969 (by decide)
    have he : Image.textByte 273969 = 0x0a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273970 (by decide)
    have he : Image.textByte 273970 = 0xfc#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273971 (by decide)
    have he : Image.textByte 273971 = 0xf6#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273972 (by decide)
    have he : Image.textByte 273972 = 0x1b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273973 (by decide)
    have he : Image.textByte 273973 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273974 (by decide)
    have he : Image.textByte 273974 = 0xe4#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273975 (by decide)
    have he : Image.textByte 273975 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273976 (by decide)
    have he : Image.textByte 273976 = 0xe3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273977 (by decide)
    have he : Image.textByte 273977 = 0x0c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273978 (by decide)
    have he : Image.textByte 273978 = 0x37#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273979 (by decide)
    have he : Image.textByte 273979 = 0xfb#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273980 (by decide)
    have he : Image.textByte 273980 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273981 (by decide)
    have he : Image.textByte 273981 = 0xb7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273982 (by decide)
    have he : Image.textByte 273982 = 0x84#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273983 (by decide)
    have he : Image.textByte 273983 = 0x1f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273984 (by decide)
    have he : Image.textByte 273984 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273985 (by decide)
    have he : Image.textByte 273985 = 0x84#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273986 (by decide)
    have he : Image.textByte 273986 = 0x87#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273987 (by decide)
    have he : Image.textByte 273987 = 0x05#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273988 (by decide)
    have he : Image.textByte 273988 = 0x93#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273989 (by decide)
    have he : Image.textByte 273989 = 0x84#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273990 (by decide)
    have he : Image.textByte 273990 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273991 (by decide)
    have he : Image.textByte 273991 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273992 (by decide)
    have he : Image.textByte 273992 = 0xe3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273993 (by decide)
    have he : Image.textByte 273993 = 0x10#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273994 (by decide)
    have he : Image.textByte 273994 = 0x34#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273995 (by decide)
    have he : Image.textByte 273995 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273996 (by decide)
    have he : Image.textByte 273996 = 0x6f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273997 (by decide)
    have he : Image.textByte 273997 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273998 (by decide)
    have he : Image.textByte 273998 = 0x5f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 273999 (by decide)
    have he : Image.textByte 273999 = 0xfa#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274000 (by decide)
    have he : Image.textByte 274000 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274001 (by decide)
    have he : Image.textByte 274001 = 0x27#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274002 (by decide)
    have he : Image.textByte 274002 = 0x49#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274003 (by decide)
    have he : Image.textByte 274003 = 0x31#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274004 (by decide)
    have he : Image.textByte 274004 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274005 (by decide)
    have he : Image.textByte 274005 = 0xb5#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274006 (by decide)
    have he : Image.textByte 274006 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274007 (by decide)
    have he : Image.textByte 274007 = 0x10#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274008 (by decide)
    have he : Image.textByte 274008 = 0x33#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274009 (by decide)
    have he : Image.textByte 274009 = 0x77#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274010 (by decide)
    have he : Image.textByte 274010 = 0xf7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274011 (by decide)
    have he : Image.textByte 274011 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274012 (by decide)
    have he : Image.textByte 274012 = 0x63#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274013 (by decide)
    have he : Image.textByte 274013 = 0x1c#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274014 (by decide)
    have he : Image.textByte 274014 = 0x07#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274015 (by decide)
    have he : Image.textByte 274015 = 0x02#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274016 (by decide)
    have he : Image.textByte 274016 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274017 (by decide)
    have he : Image.textByte 274017 = 0x05#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274018 (by decide)
    have he : Image.textByte 274018 = 0x0b#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274019 (by decide)
    have he : Image.textByte 274019 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274020 (by decide)
    have he : Image.textByte 274020 = 0xe7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274021 (by decide)
    have he : Image.textByte 274021 = 0x80#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274022 (by decide)
    have he : Image.textByte 274022 = 0x06#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274023 (by decide)
    have he : Image.textByte 274023 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274024 (by decide)
    have he : Image.textByte 274024 = 0x03#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274025 (by decide)
    have he : Image.textByte 274025 = 0x27#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274026 (by decide)
    have he : Image.textByte 274026 = 0x89#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274027 (by decide)
    have he : Image.textByte 274027 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274028 (by decide)
    have he : Image.textByte 274028 = 0x83#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274029 (by decide)
    have he : Image.textByte 274029 = 0x37#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274030 (by decide)
    have he : Image.textByte 274030 = 0x0a#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274031 (by decide)
    have he : Image.textByte 274031 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274032 (by decide)
    have he : Image.textByte 274032 = 0xe3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274033 (by decide)
    have he : Image.textByte 274033 = 0x08#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274034 (by decide)
    have he : Image.textByte 274034 = 0x97#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274035 (by decide)
    have he : Image.textByte 274035 = 0xf7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274036 (by decide)
    have he : Image.textByte 274036 = 0xe3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274037 (by decide)
    have he : Image.textByte 274037 = 0x8e#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274038 (by decide)
    have he : Image.textByte 274038 = 0x07#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274039 (by decide)
    have he : Image.textByte 274039 = 0xf6#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274040 (by decide)
    have he : Image.textByte 274040 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274041 (by decide)
    have he : Image.textByte 274041 = 0x89#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274042 (by decide)
    have he : Image.textByte 274042 = 0x07#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274043 (by decide)
    have he : Image.textByte 274043 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274044 (by decide)
    have he : Image.textByte 274044 = 0x6f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274045 (by decide)
    have he : Image.textByte 274045 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274046 (by decide)
    have he : Image.textByte 274046 = 0xdf#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274047 (by decide)
    have he : Image.textByte 274047 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274048 (by decide)
    have he : Image.textByte 274048 = 0x23#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274049 (by decide)
    have he : Image.textByte 274049 = 0x24#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274050 (by decide)
    have he : Image.textByte 274050 = 0x89#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274051 (by decide)
    have he : Image.textByte 274051 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274052 (by decide)
    have he : Image.textByte 274052 = 0x6f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274053 (by decide)
    have he : Image.textByte 274053 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274054 (by decide)
    have he : Image.textByte 274054 = 0x5f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274055 (by decide)
    have he : Image.textByte 274055 = 0xf3#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274056 (by decide)
    have he : Image.textByte 274056 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274057 (by decide)
    have he : Image.textByte 274057 = 0x04#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274058 (by decide)
    have he : Image.textByte 274058 = 0x07#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274059 (by decide)
    have he : Image.textByte 274059 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274060 (by decide)
    have he : Image.textByte 274060 = 0x93#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274061 (by decide)
    have he : Image.textByte 274061 = 0x84#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274062 (by decide)
    have he : Image.textByte 274062 = 0x84#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274063 (by decide)
    have he : Image.textByte 274063 = 0xff#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274064 (by decide)
    have he : Image.textByte 274064 = 0x6f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274065 (by decide)
    have he : Image.textByte 274065 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274066 (by decide)
    have he : Image.textByte 274066 = 0x5f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274067 (by decide)
    have he : Image.textByte 274067 = 0xf1#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274068 (by decide)
    have he : Image.textByte 274068 = 0x13#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274069 (by decide)
    have he : Image.textByte 274069 = 0x85#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274070 (by decide)
    have he : Image.textByte 274070 = 0x05#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274071 (by decide)
    have he : Image.textByte 274071 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274072 (by decide)
    have he : Image.textByte 274072 = 0xe7#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274073 (by decide)
    have he : Image.textByte 274073 = 0x80#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274074 (by decide)
    have he : Image.textByte 274074 = 0x06#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274075 (by decide)
    have he : Image.textByte 274075 = 0x00#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274076 (by decide)
    have he : Image.textByte 274076 = 0x6f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274077 (by decide)
    have he : Image.textByte 274077 = 0xf0#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274078 (by decide)
    have he : Image.textByte 274078 = 0x9f#8 := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 274079 (by decide)
    have he : Image.textByte 274079 = 0xf3#8 := by decide +kernel
    rw [he] at hb
    exact hb
def enter_body : List MInstr := [
  ⟨0x80042d28#64, 0xfa010113#32, 0x13#8, 0x01#8, 0x01#8, 0xfa#8, .addi, 2, 2, 0, 0xfa0#12⟩,
  ⟨0x80042d2c#64, 0x01713c23#32, 0x23#8, 0x3c#8, 0x71#8, 0x01#8, .sd, 0, 2, 23, 0x018#12⟩,
  ⟨0x80042d30#64, 0x00022b97#32, 0x97#8, 0x2b#8, 0x02#8, 0x00#8, .auipc, 23, 0, 0, 0x000#12⟩,
  ⟨0x80042d34#64, 0xbd0b8b93#32, 0x93#8, 0x8b#8, 0x0b#8, 0xbd#8, .addi, 23, 23, 0, 0xbd0#12⟩,
  ⟨0x80042d38#64, 0x03613023#32, 0x23#8, 0x30#8, 0x61#8, 0x03#8, .sd, 0, 2, 22, 0x020#12⟩,
  ⟨0x80042d3c#64, 0x00050b13#32, 0x13#8, 0x0b#8, 0x05#8, 0x00#8, .addi, 22, 10, 0, 0x000#12⟩,
  ⟨0x80042d40#64, 0x000bb503#32, 0x03#8, 0xb5#8, 0x0b#8, 0x00#8, .ld, 10, 23, 0, 0x000#12⟩,
  ⟨0x80042d44#64, 0x03413823#32, 0x23#8, 0x38#8, 0x41#8, 0x03#8, .sd, 0, 2, 20, 0x030#12⟩,
  ⟨0x80042d48#64, 0x00022a17#32, 0x17#8, 0x2a#8, 0x02#8, 0x00#8, .auipc, 20, 0, 0, 0x000#12⟩,
  ⟨0x80042d4c#64, 0x048a0a13#32, 0x13#8, 0x0a#8, 0x8a#8, 0x04#8, .addi, 20, 20, 0, 0x048#12⟩,
  ⟨0x80042d50#64, 0x05213023#32, 0x23#8, 0x30#8, 0x21#8, 0x05#8, .sd, 0, 2, 18, 0x040#12⟩,
  ⟨0x80042d54#64, 0x01813823#32, 0x23#8, 0x38#8, 0x81#8, 0x01#8, .sd, 0, 2, 24, 0x010#12⟩,
  ⟨0x80042d58#64, 0x04113c23#32, 0x23#8, 0x3c#8, 0x11#8, 0x04#8, .sd, 0, 2, 1, 0x058#12⟩,
  ⟨0x80042d5c#64, 0x00058c13#32, 0x13#8, 0x8c#8, 0x05#8, 0x00#8, .addi, 24, 11, 0, 0x000#12⟩
]
def enter_blocks : List BBlock := [{ body := enter_body, term := none }]
def enter_input (R : Nat → BitVec 64) : GRegs := [(1, R 1), (2, R 2), (10, R 10), (11, R 11), (18, R 18), (20, R 20), (22, R 22), (23, R 23), (24, R 24)]

theorem enter_code {c : Config} (image : ExecutableImage c) : CodeFacts c.σ.mem enter_body := by
  have hc := loaded image
  simp only [CodeFacts, enter_body]
  chain_facts hc with "Vsa.Sim.Code.__call_exitprocs_at_"

theorem enter_shape : ChainOK 0x80042d28#64 [1, 2, 10, 11, 18, 20, 22, 23, 24] enter_blocks := by
  simp only [ChainOK, BBlockOK, enter_blocks, enter_body, BlockOKM]
  repeat' apply And.intro
  all_goals decide

theorem enter_summary (c : Config) (ra : BitVec 64) (R : Nat → BitVec 64)
    (loads : List (List (BitVec 8))) (h : LeafInput ra c)
    (regs : GHolds c.σ (enter_input R))
    (access : AccessPlan c.σ.mem (enter_input R) loads enter_body)
    (control : TermFactsO (runGM enter_body (enter_input R) loads) (none)) :
    FnSummary 0x80042d28#64 (fun d => d = c)
      (BlockPost enter_blocks 0x80042d28#64 (enter_input R) loads c) := by
  apply block_summary enter_blocks _ _ _ c
  refine ⟨h.good, h.minstret, regs, ?_, ?_, enter_shape, h.tick⟩
  · change KeysOK [1, 2, 10, 11, 18, 20, 22, 23, 24]; decide
  · apply singleton_chain_facts (accessPlan_facts (enter_code h.image) access) ?_ control
    trivial

def enter_regs (R : Nat → BitVec 64) (loads : List (List (BitVec 8))) : GRegs :=
  [(24, R 11), (20, 0x80064d90#64), (10, bytesVal .ld (loads.getD 0 [])), (22, R 10), (23, 0x80064900#64), (2, R 2 - 96#64), (1, R 1), (11, R 11), (18, R 18)]
theorem enter_eval (R : Nat → BitVec 64) (loads : List (List (BitVec 8))) :
    runGM enter_body (enter_input R) loads = enter_regs R loads := by
  simp [enter_body, enter_input, enter_regs, runGM, stepGM, stepLdsM,
    wvalM, srcVal, lookupG, eraseG, imm20Of, DoubleAllocation.domainGlobal, Layout.sym_Caml_state,
    Functions.sign_extend, Sail.BitVec.signExtend, BitVec.sub_eq_add_neg, List.head?_eq_getElem?, BitVec.add_assoc]

def enter_call : CallInstr := ⟨0x80042d60#64, 0xfd8ff0ef#32, 0xef#8, 0xf0#8, 0x8f#8, 0xfd#8, 0x1ff7d8#21⟩
theorem enter_call_shape : CallShape enter_call := by constructor <;> decide
theorem enter_call_decode : CallDecode enter_call := by
  intro s hm hp he
  exact Vsa.Sim.ElfDecode.decode_fd8ff0ef s hm hp he
theorem enter_call_target : enter_call.target = 0x80042538#64 := by decide
theorem enter_call_pins {c : Config} (h : ExecutableImage c) : CallPins enter_call c := by
  obtain ⟨h0, h1, h2, h3⟩ := Vsa.Sim.Code.__call_exitprocs_at_80042d60 (loaded h)
  exact ⟨h0, h1, h2, h3⟩

def empty_body : List MInstr := [
  ⟨0x80042d64#64, 0x000a3903#32, 0x03#8, 0x39#8, 0x0a#8, 0x00#8, .ld, 18, 20, 0, 0x000#12⟩
]
def empty_term : TInstr := ⟨0x80042d68#64, 0x08090e63#32, 0x63#8, 0x0e#8, 0x09#8, 0x08#8, .br bop.BEQ true, 18, 0, 0x009c#13, 0#21, 0#12⟩
def empty_blocks : List BBlock := [{ body := empty_body, term := some empty_term }]
def empty_input (R : Nat → BitVec 64) : GRegs := [(1, R 1), (2, R 2), (10, R 10), (20, R 20), (23, R 23)]

theorem empty_code {c : Config} (image : ExecutableImage c) : CodeFacts c.σ.mem empty_body := by
  have hc := loaded image
  simp only [CodeFacts, empty_body]
  chain_facts hc with "Vsa.Sim.Code.__call_exitprocs_at_"

theorem empty_shape : ChainOK 0x80042d64#64 [1, 2, 10, 20, 23] empty_blocks := by
  simp only [ChainOK, BBlockOK, empty_blocks, empty_body, empty_term, BlockOKM]
  repeat' apply And.intro
  all_goals decide

theorem empty_summary (c : Config) (ra : BitVec 64) (R : Nat → BitVec 64)
    (loads : List (List (BitVec 8))) (h : LeafInput ra c)
    (regs : GHolds c.σ (empty_input R))
    (access : AccessPlan c.σ.mem (empty_input R) loads empty_body)
    (control : TermFactsO (runGM empty_body (empty_input R) loads) (some empty_term)) :
    FnSummary 0x80042d64#64 (fun d => d = c)
      (BlockPost empty_blocks 0x80042d64#64 (empty_input R) loads c) := by
  apply block_summary empty_blocks _ _ _ c
  refine ⟨h.good, h.minstret, regs, ?_, ?_, empty_shape, h.tick⟩
  · change KeysOK [1, 2, 10, 20, 23]; decide
  · apply singleton_chain_facts (accessPlan_facts (empty_code h.image) access) ?_ control
    have hc := loaded h.image
    chain_facts hc with "Vsa.Sim.Code.__call_exitprocs_at_"

def empty_regs (R : Nat → BitVec 64) (loads : List (List (BitVec 8))) : GRegs :=
  [(18, bytesVal .ld (loads.getD 0 [])), (1, R 1), (2, R 2), (10, R 10), (20, R 20), (23, R 23)]
theorem empty_eval (R : Nat → BitVec 64) (loads : List (List (BitVec 8))) :
    runGM empty_body (empty_input R) loads = empty_regs R loads := by
  simp [empty_body, empty_input, empty_regs, runGM, stepGM, stepLdsM,
    wvalM, srcVal, lookupG, eraseG, imm20Of, DoubleAllocation.domainGlobal, Layout.sym_Caml_state,
    Functions.sign_extend, Sail.BitVec.signExtend, BitVec.sub_eq_add_neg, List.head?_eq_getElem?, BitVec.add_assoc]

def leave_body : List MInstr := [
  ⟨0x80042e04#64, 0x000bb503#32, 0x03#8, 0xb5#8, 0x0b#8, 0x00#8, .ld, 10, 23, 0, 0x000#12⟩,
  ⟨0x80042e08#64, 0x05813083#32, 0x83#8, 0x30#8, 0x81#8, 0x05#8, .ld, 1, 2, 0, 0x058#12⟩,
  ⟨0x80042e0c#64, 0x04013903#32, 0x03#8, 0x39#8, 0x01#8, 0x04#8, .ld, 18, 2, 0, 0x040#12⟩,
  ⟨0x80042e10#64, 0x03013a03#32, 0x03#8, 0x3a#8, 0x01#8, 0x03#8, .ld, 20, 2, 0, 0x030#12⟩,
  ⟨0x80042e14#64, 0x02013b03#32, 0x03#8, 0x3b#8, 0x01#8, 0x02#8, .ld, 22, 2, 0, 0x020#12⟩,
  ⟨0x80042e18#64, 0x01813b83#32, 0x83#8, 0x3b#8, 0x81#8, 0x01#8, .ld, 23, 2, 0, 0x018#12⟩,
  ⟨0x80042e1c#64, 0x01013c03#32, 0x03#8, 0x3c#8, 0x01#8, 0x01#8, .ld, 24, 2, 0, 0x010#12⟩,
  ⟨0x80042e20#64, 0x06010113#32, 0x13#8, 0x01#8, 0x01#8, 0x06#8, .addi, 2, 2, 0, 0x060#12⟩
]
def leave_term : TInstr := ⟨0x80042e24#64, 0xf2cff06f#32, 0x6f#8, 0xf0#8, 0xcf#8, 0xf2#8, .j, 0, 0, 0#13, 0x1ff72c#21, 0#12⟩
def leave_blocks : List BBlock := [{ body := leave_body, term := some leave_term }]
def leave_input (R : Nat → BitVec 64) : GRegs := [(1, R 1), (2, R 2), (23, R 23)]

theorem leave_code {c : Config} (image : ExecutableImage c) : CodeFacts c.σ.mem leave_body := by
  have hc := loaded image
  simp only [CodeFacts, leave_body]
  chain_facts hc with "Vsa.Sim.Code.__call_exitprocs_at_"

theorem leave_shape : ChainOK 0x80042e04#64 [1, 2, 23] leave_blocks := by
  simp only [ChainOK, BBlockOK, leave_blocks, leave_body, leave_term, BlockOKM]
  repeat' apply And.intro
  all_goals decide

theorem leave_summary (c : Config) (ra : BitVec 64) (R : Nat → BitVec 64)
    (loads : List (List (BitVec 8))) (h : LeafInput ra c)
    (regs : GHolds c.σ (leave_input R))
    (access : AccessPlan c.σ.mem (leave_input R) loads leave_body)
    (control : TermFactsO (runGM leave_body (leave_input R) loads) (some leave_term)) :
    FnSummary 0x80042e04#64 (fun d => d = c)
      (BlockPost leave_blocks 0x80042e04#64 (leave_input R) loads c) := by
  apply block_summary leave_blocks _ _ _ c
  refine ⟨h.good, h.minstret, regs, ?_, ?_, leave_shape, h.tick⟩
  · change KeysOK [1, 2, 23]; decide
  · apply singleton_chain_facts (accessPlan_facts (leave_code h.image) access) ?_ control
    have hc := loaded h.image
    chain_facts hc with "Vsa.Sim.Code.__call_exitprocs_at_"

def leave_regs (R : Nat → BitVec 64) (loads : List (List (BitVec 8))) : GRegs :=
  [(2, R 2 + 96#64), (24, bytesVal .ld (loads.getD 6 [])), (23, bytesVal .ld (loads.getD 5 [])), (22, bytesVal .ld (loads.getD 4 [])), (20, bytesVal .ld (loads.getD 3 [])), (18, bytesVal .ld (loads.getD 2 [])), (1, bytesVal .ld (loads.getD 1 [])), (10, bytesVal .ld (loads.getD 0 []))]
theorem leave_eval (R : Nat → BitVec 64) (loads : List (List (BitVec 8))) :
    runGM leave_body (leave_input R) loads = leave_regs R loads := by
  simp [leave_body, leave_input, leave_regs, runGM, stepGM, stepLdsM,
    wvalM, srcVal, lookupG, eraseG, imm20Of, DoubleAllocation.domainGlobal, Layout.sym_Caml_state,
    Functions.sign_extend, Sail.BitVec.signExtend, BitVec.sub_eq_add_neg, List.head?_eq_getElem?, BitVec.add_assoc]

end OCaml.Vm.Primitives.ExitPath.ExitProcs
