import Vsa.Elf

/-! Code-region predicate + fetch-hypothesis lemmas for `camlUgeintTrue`
(GENERATED by scripts/gen_arm_pilot.py (experiments/syi/gen_code_lemmas.py) — do not hand-edit).
6 instructions at [0x800034e0, 0x800034f8). -/

open Std (ExtHashMap)

namespace Vsa.Sim.Code

def camlUgeintTrueChunk0 (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  mem[(0x800034e0 : Nat)]? = some (0x83 : BitVec 8) ∧
  mem[(0x800034e1 : Nat)]? = some (0xb7 : BitVec 8) ∧
  mem[(0x800034e2 : Nat)]? = some (0x04 : BitVec 8) ∧
  mem[(0x800034e3 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x800034e4 : Nat)]? = some (0x13 : BitVec 8) ∧
  mem[(0x800034e5 : Nat)]? = some (0x84 : BitVec 8) ∧
  mem[(0x800034e6 : Nat)]? = some (0x0b : BitVec 8) ∧
  mem[(0x800034e7 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x800034e8 : Nat)]? = some (0x93 : BitVec 8) ∧
  mem[(0x800034e9 : Nat)]? = some (0x84 : BitVec 8) ∧
  mem[(0x800034ea : Nat)]? = some (0x84 : BitVec 8) ∧
  mem[(0x800034eb : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x800034ec : Nat)]? = some (0x63 : BitVec 8) ∧
  mem[(0x800034ed : Nat)]? = some (0xe0 : BitVec 8) ∧
  mem[(0x800034ee : Nat)]? = some (0xfa : BitVec 8) ∧
  mem[(0x800034ef : Nat)]? = some (0x18 : BitVec 8) ∧
  mem[(0x800034f0 : Nat)]? = some (0x93 : BitVec 8) ∧
  mem[(0x800034f1 : Nat)]? = some (0x0a : BitVec 8) ∧
  mem[(0x800034f2 : Nat)]? = some (0x30 : BitVec 8) ∧
  mem[(0x800034f3 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x800034f4 : Nat)]? = some (0x6f : BitVec 8) ∧
  mem[(0x800034f5 : Nat)]? = some (0xe0 : BitVec 8) ∧
  mem[(0x800034f6 : Nat)]? = some (0x9f : BitVec 8) ∧
  mem[(0x800034f7 : Nat)]? = some (0xa6 : BitVec 8)

/-- The whole `camlUgeintTrue` code region is loaded. -/
def CamlUgeintTrueLoaded (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  camlUgeintTrueChunk0 mem

theorem camlUgeintTrue_chunk0 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlUgeintTrueLoaded mem) : camlUgeintTrueChunk0 mem :=
  h

theorem camlUgeintTrue_at_800034e0 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlUgeintTrueLoaded mem) :
      mem[(0x800034e0 : Nat)]? = some (0x83 : BitVec 8) ∧
      mem[(0x800034e1 : Nat)]? = some (0xb7 : BitVec 8) ∧
      mem[(0x800034e2 : Nat)]? = some (0x04 : BitVec 8) ∧
      mem[(0x800034e3 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := camlUgeintTrue_chunk0 h
  ⟨hc.1, hc.2.1, hc.2.2.1, hc.2.2.2.1⟩

theorem camlUgeintTrue_at_800034e4 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlUgeintTrueLoaded mem) :
      mem[(0x800034e4 : Nat)]? = some (0x13 : BitVec 8) ∧
      mem[(0x800034e5 : Nat)]? = some (0x84 : BitVec 8) ∧
      mem[(0x800034e6 : Nat)]? = some (0x0b : BitVec 8) ∧
      mem[(0x800034e7 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := camlUgeintTrue_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.1, hc.2.2.2.2.2.1, hc.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.1⟩

theorem camlUgeintTrue_at_800034e8 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlUgeintTrueLoaded mem) :
      mem[(0x800034e8 : Nat)]? = some (0x93 : BitVec 8) ∧
      mem[(0x800034e9 : Nat)]? = some (0x84 : BitVec 8) ∧
      mem[(0x800034ea : Nat)]? = some (0x84 : BitVec 8) ∧
      mem[(0x800034eb : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := camlUgeintTrue_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem camlUgeintTrue_at_800034ec {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlUgeintTrueLoaded mem) :
      mem[(0x800034ec : Nat)]? = some (0x63 : BitVec 8) ∧
      mem[(0x800034ed : Nat)]? = some (0xe0 : BitVec 8) ∧
      mem[(0x800034ee : Nat)]? = some (0xfa : BitVec 8) ∧
      mem[(0x800034ef : Nat)]? = some (0x18 : BitVec 8) :=
  have hc := camlUgeintTrue_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem camlUgeintTrue_at_800034f0 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlUgeintTrueLoaded mem) :
      mem[(0x800034f0 : Nat)]? = some (0x93 : BitVec 8) ∧
      mem[(0x800034f1 : Nat)]? = some (0x0a : BitVec 8) ∧
      mem[(0x800034f2 : Nat)]? = some (0x30 : BitVec 8) ∧
      mem[(0x800034f3 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := camlUgeintTrue_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1⟩

theorem camlUgeintTrue_at_800034f4 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlUgeintTrueLoaded mem) :
      mem[(0x800034f4 : Nat)]? = some (0x6f : BitVec 8) ∧
      mem[(0x800034f5 : Nat)]? = some (0xe0 : BitVec 8) ∧
      mem[(0x800034f6 : Nat)]? = some (0x9f : BitVec 8) ∧
      mem[(0x800034f7 : Nat)]? = some (0xa6 : BitVec 8) :=
  have hc := camlUgeintTrue_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2⟩

end Vsa.Sim.Code
