import Vsa.Elf

/-! Code-region predicate + fetch-hypothesis lemmas for `caml_terminate_signals`
(GENERATED by scripts/syi/gen_fn.py --ocaml-exit — do not hand-edit).
1 instructions at [0x8000dbe8, 0x8000dbec). -/

open Std (ExtHashMap)

namespace Vsa.Sim.Code

def caml_terminate_signalsChunk0 (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  mem[(0x8000dbe8 : Nat)]? = some (0x67 : BitVec 8) ∧
  mem[(0x8000dbe9 : Nat)]? = some (0x80 : BitVec 8) ∧
  mem[(0x8000dbea : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x8000dbeb : Nat)]? = some (0x00 : BitVec 8)

/-- The whole `caml_terminate_signals` code region is loaded. -/
def Caml_terminate_signalsLoaded (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  caml_terminate_signalsChunk0 mem

theorem caml_terminate_signals_chunk0 {mem : ExtHashMap Nat (BitVec 8)}
    (h : Caml_terminate_signalsLoaded mem) : caml_terminate_signalsChunk0 mem :=
  h

theorem caml_terminate_signals_at_8000dbe8 {mem : ExtHashMap Nat (BitVec 8)}
    (h : Caml_terminate_signalsLoaded mem) :
      mem[(0x8000dbe8 : Nat)]? = some (0x67 : BitVec 8) ∧
      mem[(0x8000dbe9 : Nat)]? = some (0x80 : BitVec 8) ∧
      mem[(0x8000dbea : Nat)]? = some (0x00 : BitVec 8) ∧
      mem[(0x8000dbeb : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := caml_terminate_signals_chunk0 h
  ⟨hc.1, hc.2.1, hc.2.2.1, hc.2.2.2⟩

end Vsa.Sim.Code
