import Vsa.Elf

/-! Code-region predicate + fetch-hypothesis lemmas for `camlConst1`
(GENERATED by scripts/gen_arm_pilot.py (experiments/syi/gen_code_lemmas.py) — do not hand-edit).
3 instructions at [0x80002e04, 0x80002e10). -/

open Std (ExtHashMap)

namespace Vsa.Sim.Code

def camlConst1Chunk0 (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  mem[(0x80002e04 : Nat)]? = some (0x13 : BitVec 8) ∧
  mem[(0x80002e05 : Nat)]? = some (0x84 : BitVec 8) ∧
  mem[(0x80002e06 : Nat)]? = some (0x0b : BitVec 8) ∧
  mem[(0x80002e07 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80002e08 : Nat)]? = some (0x93 : BitVec 8) ∧
  mem[(0x80002e09 : Nat)]? = some (0x0a : BitVec 8) ∧
  mem[(0x80002e0a : Nat)]? = some (0x30 : BitVec 8) ∧
  mem[(0x80002e0b : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80002e0c : Nat)]? = some (0x6f : BitVec 8) ∧
  mem[(0x80002e0d : Nat)]? = some (0xf0 : BitVec 8) ∧
  mem[(0x80002e0e : Nat)]? = some (0x0f : BitVec 8) ∧
  mem[(0x80002e0f : Nat)]? = some (0x95 : BitVec 8)

/-- The whole `camlConst1` code region is loaded. -/
def CamlConst1Loaded (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  camlConst1Chunk0 mem

theorem camlConst1_chunk0 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlConst1Loaded mem) : camlConst1Chunk0 mem :=
  h

theorem camlConst1_at_80002e04 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlConst1Loaded mem) :
      mem[(0x80002e04 : Nat)]? = some (0x13 : BitVec 8) ∧
      mem[(0x80002e05 : Nat)]? = some (0x84 : BitVec 8) ∧
      mem[(0x80002e06 : Nat)]? = some (0x0b : BitVec 8) ∧
      mem[(0x80002e07 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := camlConst1_chunk0 h
  ⟨hc.1, hc.2.1, hc.2.2.1, hc.2.2.2.1⟩

theorem camlConst1_at_80002e08 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlConst1Loaded mem) :
      mem[(0x80002e08 : Nat)]? = some (0x93 : BitVec 8) ∧
      mem[(0x80002e09 : Nat)]? = some (0x0a : BitVec 8) ∧
      mem[(0x80002e0a : Nat)]? = some (0x30 : BitVec 8) ∧
      mem[(0x80002e0b : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := camlConst1_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.1, hc.2.2.2.2.2.1, hc.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.1⟩

theorem camlConst1_at_80002e0c {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlConst1Loaded mem) :
      mem[(0x80002e0c : Nat)]? = some (0x6f : BitVec 8) ∧
      mem[(0x80002e0d : Nat)]? = some (0xf0 : BitVec 8) ∧
      mem[(0x80002e0e : Nat)]? = some (0x0f : BitVec 8) ∧
      mem[(0x80002e0f : Nat)]? = some (0x95 : BitVec 8) :=
  have hc := camlConst1_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2⟩

end Vsa.Sim.Code
