import Vsa.Elf

/-! Code-region predicate + fetch-hypothesis lemmas for `camlAcc0`
(GENERATED by scripts/gen_arm_pilot.py (experiments/syi/gen_code_lemmas.py) — do not hand-edit).
3 instructions at [0x80002320, 0x8000232c). -/

open Std (ExtHashMap)

namespace Vsa.Sim.Code

def camlAcc0Chunk0 (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  mem[(0x80002320 : Nat)]? = some (0x83 : BitVec 8) ∧
  mem[(0x80002321 : Nat)]? = some (0xba : BitVec 8) ∧
  mem[(0x80002322 : Nat)]? = some (0x04 : BitVec 8) ∧
  mem[(0x80002323 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80002324 : Nat)]? = some (0x13 : BitVec 8) ∧
  mem[(0x80002325 : Nat)]? = some (0x84 : BitVec 8) ∧
  mem[(0x80002326 : Nat)]? = some (0x0b : BitVec 8) ∧
  mem[(0x80002327 : Nat)]? = some (0x00 : BitVec 8) ∧
  mem[(0x80002328 : Nat)]? = some (0x6f : BitVec 8) ∧
  mem[(0x80002329 : Nat)]? = some (0xf0 : BitVec 8) ∧
  mem[(0x8000232a : Nat)]? = some (0x5f : BitVec 8) ∧
  mem[(0x8000232b : Nat)]? = some (0xc3 : BitVec 8)

/-- The whole `camlAcc0` code region is loaded. -/
def CamlAcc0Loaded (mem : ExtHashMap Nat (BitVec 8)) : Prop :=
  camlAcc0Chunk0 mem

theorem camlAcc0_chunk0 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlAcc0Loaded mem) : camlAcc0Chunk0 mem :=
  h

theorem camlAcc0_at_80002320 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlAcc0Loaded mem) :
      mem[(0x80002320 : Nat)]? = some (0x83 : BitVec 8) ∧
      mem[(0x80002321 : Nat)]? = some (0xba : BitVec 8) ∧
      mem[(0x80002322 : Nat)]? = some (0x04 : BitVec 8) ∧
      mem[(0x80002323 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := camlAcc0_chunk0 h
  ⟨hc.1, hc.2.1, hc.2.2.1, hc.2.2.2.1⟩

theorem camlAcc0_at_80002324 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlAcc0Loaded mem) :
      mem[(0x80002324 : Nat)]? = some (0x13 : BitVec 8) ∧
      mem[(0x80002325 : Nat)]? = some (0x84 : BitVec 8) ∧
      mem[(0x80002326 : Nat)]? = some (0x0b : BitVec 8) ∧
      mem[(0x80002327 : Nat)]? = some (0x00 : BitVec 8) :=
  have hc := camlAcc0_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.1, hc.2.2.2.2.2.1, hc.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.1⟩

theorem camlAcc0_at_80002328 {mem : ExtHashMap Nat (BitVec 8)}
    (h : CamlAcc0Loaded mem) :
      mem[(0x80002328 : Nat)]? = some (0x6f : BitVec 8) ∧
      mem[(0x80002329 : Nat)]? = some (0xf0 : BitVec 8) ∧
      mem[(0x8000232a : Nat)]? = some (0x5f : BitVec 8) ∧
      mem[(0x8000232b : Nat)]? = some (0xc3 : BitVec 8) :=
  have hc := camlAcc0_chunk0 h
  -- discipline: allow(R6-anon-projection-tower) generated code-pin projections (bounded, chunked)
  ⟨hc.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.1, hc.2.2.2.2.2.2.2.2.2.2.2⟩

end Vsa.Sim.Code
