import Vsa.Sim.DeriveCaseRow
import Vsa.Sim.FnSummary
import Vsa.Sim.Code.Caml_ext_table_init

/-!
# `caml_ext_table_init` — GENERATED region [0x80003dd8, 0x80003ddc) summary blocks (scripts/gen_fn.py)

1 instrs, 1 blocks.
GENERATED by scripts/gen_startup_rows.py via `scripts/syi/gen_fn.py --fn caml_ext_table_init --entry 0x80003dd8`.  DO NOT hand-edit.
NO `sorry`/`axiom`/`native_decide`/`bv_decide`; no Mathlib.
-/
-- discipline: allow(R9-handrolled-fn-assembly) GENERATED by gen_fn.py

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail Vsa
open Register
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic (Triple)


namespace Vsa.Sim

/- The `caml_ext_table_initX3dd8` span body `0x80003dd8 → 0x80003ddc` (fallthrough-terminated, 1 block(s)), decoded from the pinned runtime ELF. -/
#derive_case caml_ext_table_initX3dd8Seg chain
  [(0x80003dd8#64, 0x00a43423#32)]  -- sd a0,8(s0)

/-- The `caml_ext_table_initX3dd8` entry pin list — the registers the body reads: `x10`, `x8`. -/
def caml_ext_table_initX3dd8L (a0 s0 : BitVec 64) : GRegs := [(10, a0), (8, s0)]

/-- The `caml_ext_table_initX3dd8` row post: parked at the computed end PC `0x80003ddc#64`, memory = the entry memory with the seg's write-log applied (computed off `#derive_case`). -/
structure Caml_ext_table_initX3dd8Post (a0 : BitVec 64) (s0 : BitVec 64) (lds : List (List (BitVec 8)))
    (m0 : Std.ExtHashMap Nat (BitVec 8)) (c : Config) : Prop where
  good : GoodState c.σ
  memory : c.σ.mem = writeLog m0 (evalBlocks caml_ext_table_initX3dd8Seg
    (SegEvalState.init (caml_ext_table_initX3dd8L a0 s0) lds)).log
  pc : c.σ.regs.get? Register.PC = some 0x80003ddc#64
  tick : c.tick < 2
  minstret : ∃ w, c.σ.regs.get? Register.minstret = some w
  registers : GHolds c.σ (evalBlocks caml_ext_table_initX3dd8Seg (SegEvalState.init (caml_ext_table_initX3dd8L a0 s0) lds)).regs

/-- **`caml_ext_table_initX3dd8Row`** — the `caml_ext_table_initX3dd8` span as a `Triple`, via `segToTriple` over the fallthrough-terminated `caml_ext_table_initX3dd8Seg`.  `hwf` is the row's one kernel `decide` (`ChainOK`); `hpost` projects the computed end PC (0x80003ddc#64) and the write-log memory off the outcome.  Replaces the hand `site_*` `stepObs` battery for this span. -/
theorem caml_ext_table_initX3dd8Row (a0 : BitVec 64) (s0 : BitVec 64) (lds : List (List (BitVec 8)))
    (m0 : Std.ExtHashMap Nat (BitVec 8)) :
    Triple (SegPre caml_ext_table_initX3dd8Seg (caml_ext_table_initX3dd8L a0 s0) lds 0x80003dd8#64 m0)
      (Caml_ext_table_initX3dd8Post a0 s0 lds m0) := by
  apply segToTriple caml_ext_table_initX3dd8Seg (caml_ext_table_initX3dd8L a0 s0) lds 0x80003dd8#64 m0
    (Caml_ext_table_initX3dd8Post a0 s0 lds m0)
    (by have h : keysG (caml_ext_table_initX3dd8L a0 s0) = [10, 8] := rfl
        rw [h]; show ChainOK 0x80003dd8#64 [10, 8] caml_ext_table_initX3dd8Seg; decide)
  intro σ' i' u' hG' hi' hmem' hpc' hmi' hregs
  refine ⟨hG', hmem', ?_, hi', hmi', hregs⟩
  rw [hpc']
  show some (evalBlocksPC 0x80003dd8#64 (SegEvalState.init (caml_ext_table_initX3dd8L a0 s0) lds) caml_ext_table_initX3dd8Seg)
    = some 0x80003ddc#64
  rfl

#print axioms caml_ext_table_initX3dd8Row

end Vsa.Sim