import OCaml.Vm.Boot.Startup.Call
import Vsa.Sim.FnSummary
import Vsa.Sim.Code._findenv_r
import Vsa.Sim.ElfDecode.Part017

/-! GENERATED by scripts/gen_startup_rows.py via gen_sites.py. -/
namespace OCaml.Vm.Boot.Startup
open Vsa.Machine Vsa.Sim LeanRV64DExecutable LeanRV64DExecutable.Functions Sail

/-- 0x800374c8: `jal x1,0x80040cc8` (link `x1 := 0x800374cc`). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_800374c8_startup (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code._findenv_rLoaded σ.mem)
    (hpcv : pc = (0x800374c8#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jal σ pc vminstret (0x009800#21) Register.x1 (BitVec.addInt pc 4)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code._findenv_r_at_800374c8 hmem
  refine stepObs_jal σ i u (0x800374c8#64) vminstret (0x001090ef#32) (0x009800#21)
    (regidx.Regidx 0x01#5) Register.x1 (BitVec.addInt (0x800374c8#64) 4)
    (0xef#8) (0x90#8) (0x10#8) (0x00#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide) (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_001090ef (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide) ?_ hi
  exact wX_bits_x1 _ (BitVec.addInt (0x800374c8#64) 4)


theorem call_800374c8 (c : Config) (good : GoodState c.σ) (tick : c.tick < 2)
    (code : Vsa.Sim.Code._findenv_rLoaded c.σ.mem) :
    FnSummary 0x800374c8#64 (fun d => d = c)
      (CallPost 0x80040cc8#64 0x800374cc#64 c) := by
  constructor
  rintro d ⟨pc, eq⟩
  subst d
  obtain ⟨vm, hvm⟩ := good.minstret
  obtain ⟨σ, tick', step, bound, good', memory, obs⟩ :=
    site_800374c8_startup c.σ c.tick c.steps _ vm good pc hvm code rfl tick
  exact ⟨⟨σ, tick', c.steps + 1⟩, Steps.single step,
    CallPost.of_obs good' bound memory obs (by decide)⟩

end OCaml.Vm.Boot.Startup
