import OCaml.Vm.Boot.Startup.FsInitReturnRows

/-! GENERATED by scripts/gen_startup_rows.py via gen_fn.ocaml_literal_mline. -/
namespace OCaml.Vm.Boot.Startup
open Vsa.Sim

theorem fsinitreturn_line_800004c4 :
    mkLine 0x800004c4#64 0x04813483#32 =
      ⟨0x800004c4#64, 0x04813483#32, 0x83#8, 0x34#8, 0x81#8, 0x04#8, .ld, 9, 2, 0, 0x048#12⟩ := by rfl

theorem fsinitreturn_line_800004c8 :
    mkLine 0x800004c8#64 0x04013903#32 =
      ⟨0x800004c8#64, 0x04013903#32, 0x03#8, 0x39#8, 0x01#8, 0x04#8, .ld, 18, 2, 0, 0x040#12⟩ := by rfl

theorem fsinitreturn_line_800004cc :
    mkLine 0x800004cc#64 0x03013a03#32 =
      ⟨0x800004cc#64, 0x03013a03#32, 0x03#8, 0x3a#8, 0x01#8, 0x03#8, .ld, 20, 2, 0, 0x030#12⟩ := by rfl

theorem fsinitreturn_line_800004d0 :
    mkLine 0x800004d0#64 0x02813a83#32 =
      ⟨0x800004d0#64, 0x02813a83#32, 0x83#8, 0x3a#8, 0x81#8, 0x02#8, .ld, 21, 2, 0, 0x028#12⟩ := by rfl

theorem fsinitreturn_line_800004d4 :
    mkLine 0x800004d4#64 0x01013c03#32 =
      ⟨0x800004d4#64, 0x01013c03#32, 0x03#8, 0x3c#8, 0x01#8, 0x01#8, .ld, 24, 2, 0, 0x010#12⟩ := by rfl

theorem fsinitreturn_line_800004d8 :
    mkLine 0x800004d8#64 0x00813c83#32 =
      ⟨0x800004d8#64, 0x00813c83#32, 0x83#8, 0x3c#8, 0x81#8, 0x00#8, .ld, 25, 2, 0, 0x008#12⟩ := by rfl

theorem fsinitreturn_line_800004dc :
    mkLine 0x800004dc#64 0x05813083#32 =
      ⟨0x800004dc#64, 0x05813083#32, 0x83#8, 0x30#8, 0x81#8, 0x05#8, .ld, 1, 2, 0, 0x058#12⟩ := by rfl

theorem fsinitreturn_line_800004e0 :
    mkLine 0x800004e0#64 0x05013403#32 =
      ⟨0x800004e0#64, 0x05013403#32, 0x03#8, 0x34#8, 0x01#8, 0x05#8, .ld, 8, 2, 0, 0x050#12⟩ := by rfl

theorem fsinitreturn_line_800004e4 :
    mkLine 0x800004e4#64 0x03813983#32 =
      ⟨0x800004e4#64, 0x03813983#32, 0x83#8, 0x39#8, 0x81#8, 0x03#8, .ld, 19, 2, 0, 0x038#12⟩ := by rfl

theorem fsinitreturn_line_800004e8 :
    mkLine 0x800004e8#64 0x02013b03#32 =
      ⟨0x800004e8#64, 0x02013b03#32, 0x03#8, 0x3b#8, 0x01#8, 0x02#8, .ld, 22, 2, 0, 0x020#12⟩ := by rfl

theorem fsinitreturn_line_800004ec :
    mkLine 0x800004ec#64 0x01813b83#32 =
      ⟨0x800004ec#64, 0x01813b83#32, 0x83#8, 0x3b#8, 0x81#8, 0x01#8, .ld, 23, 2, 0, 0x018#12⟩ := by rfl

theorem fsinitreturn_line_800004f0 :
    mkLine 0x800004f0#64 0x06010113#32 =
      ⟨0x800004f0#64, 0x06010113#32, 0x13#8, 0x01#8, 0x01#8, 0x06#8, .addi, 2, 2, 0, 0x060#12⟩ := by rfl

end OCaml.Vm.Boot.Startup
