import OCaml.Vm.Boot.Startup.FsInitScanRows

/-! GENERATED by scripts/gen_startup_rows.py via gen_fn.ocaml_literal_mline. -/
namespace OCaml.Vm.Boot.Startup
open Vsa.Sim

theorem fsinitscan_line_80000434 :
    mkLine 0x80000434#64 0x00044783#32 =
      ⟨0x80000434#64, 0x00044783#32, 0x83#8, 0x47#8, 0x04#8, 0x00#8, .lbu, 15, 8, 0, 0x000#12⟩ := by rfl

theorem fsinitscan_line_80000438 :
    mkLine 0x80000438#64 0x02f00593#32 =
      ⟨0x80000438#64, 0x02f00593#32, 0x93#8, 0x05#8, 0xf0#8, 0x02#8, .addi, 11, 0, 0, 0x02f#12⟩ := by rfl

theorem fsinitscan_line_8000043c :
    mkLine 0x8000043c#64 0x00040513#32 =
      ⟨0x8000043c#64, 0x00040513#32, 0x13#8, 0x05#8, 0x04#8, 0x00#8, .addi, 10, 8, 0, 0x000#12⟩ := by rfl

end OCaml.Vm.Boot.Startup
