import OCaml.Vm.Platform
import Vsa.Sim.Code.Getenv

/-! GENERATED by scripts/gen_startup_rows.py via gen_arm_pilot.image_projection. Full-image projection. -/
namespace OCaml.Vm.Boot.Startup
open Vsa.Machine

theorem getenvPrefix_code {c : Config} (h : ExecutableImage c) :
    Vsa.Sim.Code.GetenvLoaded c.σ.mem := by
  unfold Vsa.Sim.Code.GetenvLoaded Vsa.Sim.Code.getenvChunk0
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · have hb := h.text 226320 (by decide)
    have he : Image.textByte 226320 = (0x93#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226321 (by decide)
    have he : Image.textByte 226321 = (0x05#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226322 (by decide)
    have he : Image.textByte 226322 = (0x05#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226323 (by decide)
    have he : Image.textByte 226323 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226324 (by decide)
    have he : Image.textByte 226324 = (0x17#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226325 (by decide)
    have he : Image.textByte 226325 = (0xd5#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226326 (by decide)
    have he : Image.textByte 226326 = (0x02#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226327 (by decide)
    have he : Image.textByte 226327 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226328 (by decide)
    have he : Image.textByte 226328 = (0x03#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226329 (by decide)
    have he : Image.textByte 226329 = (0x35#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226330 (by decide)
    have he : Image.textByte 226330 = (0x45#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226331 (by decide)
    have he : Image.textByte 226331 = (0x4e#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226332 (by decide)
    have he : Image.textByte 226332 = (0x13#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226333 (by decide)
    have he : Image.textByte 226333 = (0x01#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226334 (by decide)
    have he : Image.textByte 226334 = (0x01#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226335 (by decide)
    have he : Image.textByte 226335 = (0xfe#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226336 (by decide)
    have he : Image.textByte 226336 = (0x13#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226337 (by decide)
    have he : Image.textByte 226337 = (0x06#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226338 (by decide)
    have he : Image.textByte 226338 = (0xc1#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226339 (by decide)
    have he : Image.textByte 226339 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226340 (by decide)
    have he : Image.textByte 226340 = (0x23#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226341 (by decide)
    have he : Image.textByte 226341 = (0x3c#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226342 (by decide)
    have he : Image.textByte 226342 = (0x11#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226343 (by decide)
    have he : Image.textByte 226343 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226344 (by decide)
    have he : Image.textByte 226344 = (0xef#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226345 (by decide)
    have he : Image.textByte 226345 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226346 (by decide)
    have he : Image.textByte 226346 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226347 (by decide)
    have he : Image.textByte 226347 = (0x01#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226348 (by decide)
    have he : Image.textByte 226348 = (0x83#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226349 (by decide)
    have he : Image.textByte 226349 = (0x30#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226350 (by decide)
    have he : Image.textByte 226350 = (0x81#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226351 (by decide)
    have he : Image.textByte 226351 = (0x01#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226352 (by decide)
    have he : Image.textByte 226352 = (0x13#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226353 (by decide)
    have he : Image.textByte 226353 = (0x01#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226354 (by decide)
    have he : Image.textByte 226354 = (0x01#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226355 (by decide)
    have he : Image.textByte 226355 = (0x02#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226356 (by decide)
    have he : Image.textByte 226356 = (0x67#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226357 (by decide)
    have he : Image.textByte 226357 = (0x80#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226358 (by decide)
    have he : Image.textByte 226358 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 226359 (by decide)
    have he : Image.textByte 226359 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb

end OCaml.Vm.Boot.Startup
