import OCaml.Vm.Boot.Startup.HtifOpenEnoentRows

/-! GENERATED by scripts/gen_startup_rows.py via gen_fn.ocaml_literal_mline. -/
namespace OCaml.Vm.Boot.Startup
open Vsa.Sim

theorem htifopenenoent_line_80000b08 :
    mkLine 0x80000b08#64 0x00058493#32 =
      ⟨0x80000b08#64, 0x00058493#32, 0x93#8, 0x84#8, 0x05#8, 0x00#8, .addi, 9, 11, 0, 0x000#12⟩ := by rfl

end OCaml.Vm.Boot.Startup
