import Vsa.Sim.DeriveCaseRow
import Vsa.Sim.FnSummary
import Vsa.Sim.Code._open_r

/-!
# `_open_r` — GENERATED region [0x8004d7f4, 0x8004d808) summary blocks (scripts/gen_fn.py)

5 instrs, 1 blocks.
GENERATED by scripts/gen_startup_rows.py via `scripts/syi/gen_fn.py --fn _open_r --entry 0x8004d7f4`.  DO NOT hand-edit.
NO `sorry`/`axiom`/`native_decide`/`bv_decide`; no Mathlib.
-/
-- discipline: allow(R9-handrolled-fn-assembly) GENERATED by gen_fn.py

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail Vsa
open Register
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic (Triple)


namespace Vsa.Sim

/- The `open_rXd7f4` span body `0x8004d7f4 → 0x8004d804` (jr (in-model; seg+L only — symbolic end PC)-terminated, 1 block(s)), decoded from the pinned runtime ELF. -/
#derive_case open_rXd7f4Seg chain
  [(0x8004d7f4#64, 0x00813083#32),  -- ld ra,8(sp)
   (0x8004d7f8#64, 0x00f42023#32),  -- sw a5,0(s0)
   (0x8004d7fc#64, 0x00013403#32),  -- ld s0,0(sp)
   (0x8004d800#64, 0x01010113#32)]  -- addi sp,sp,16
    terminator ⟨0x8004d804#64, 0x00008067#32, 0x67#8, 0x80#8, 0x00#8, 0x00#8, .jr, 1, 0, 0#13, 0#21, 0x000#12⟩

/-- The `open_rXd7f4` entry pin list — the registers the body reads: `x2`, `x15`, `x8`. -/
def open_rXd7f4L (sp a5 s0 : BitVec 64) : GRegs := [(2, sp), (15, a5), (8, s0)]

end Vsa.Sim