import Vsa.Sim.DeriveCaseRow
import Vsa.Sim.FnSummary
import Vsa.Sim.Code.Resolve

/-!
# `resolve` — GENERATED region [0x800007e4, 0x800007f0) summary blocks (scripts/gen_fn.py)

3 instrs, 1 blocks.
GENERATED by scripts/gen_startup_rows.py via `scripts/syi/gen_fn.py --fn resolve --entry 0x800007e4`.  DO NOT hand-edit.
NO `sorry`/`axiom`/`native_decide`/`bv_decide`; no Mathlib.
-/
-- discipline: allow(R9-handrolled-fn-assembly) GENERATED by gen_fn.py

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail Vsa
open Register
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic (Triple)


namespace Vsa.Sim

/- The `resolveX07e4T` span body `0x800007e4 → 0x800007ec` (br-terminated, 1 block(s)), decoded from the pinned runtime ELF. -/
#derive_case resolveX07e4TSeg chain
  [(0x800007e4#64, 0x40e787b3#32),  -- sub a5,a5,a4
   (0x800007e8#64, 0x00100693#32)]  -- li a3,1
    terminator ⟨0x800007ec#64, 0xe0d79ce3#32, 0xe3#8, 0x9c#8, 0xd7#8, 0xe0#8, .br bop.BNE true, 15, 13, 0x1e18#13, 0#21, 0#12⟩

/-- The `resolveX07e4T` entry pin list — the registers the body reads: `x15`, `x14`. -/
def resolveX07e4TL (a5 a4 : BitVec 64) : GRegs := [(15, a5), (14, a4)]

/-- The `resolveX07e4T` row post: parked at the computed end PC `0x80000604#64`, memory = the entry memory with the seg's write-log applied (computed off `#derive_case`). -/
structure ResolveX07e4TPost (a5 : BitVec 64) (a4 : BitVec 64) (lds : List (List (BitVec 8)))
    (m0 : Std.ExtHashMap Nat (BitVec 8)) (c : Config) : Prop where
  good : GoodState c.σ
  memory : c.σ.mem = writeLog m0 (evalBlocks resolveX07e4TSeg
    (SegEvalState.init (resolveX07e4TL a5 a4) lds)).log
  pc : c.σ.regs.get? Register.PC = some 0x80000604#64
  tick : c.tick < 2
  minstret : ∃ w, c.σ.regs.get? Register.minstret = some w
  registers : GHolds c.σ (evalBlocks resolveX07e4TSeg (SegEvalState.init (resolveX07e4TL a5 a4) lds)).regs

/-- **`resolveX07e4TRow`** — the `resolveX07e4T` span as a `Triple`, via `segToTriple` over the br-terminated `resolveX07e4TSeg`.  `hwf` is the row's one kernel `decide` (`ChainOK`); `hpost` projects the computed end PC (0x80000604#64) and the write-log memory off the outcome.  Replaces the hand `site_*` `stepObs` battery for this span. -/
theorem resolveX07e4TRow (a5 : BitVec 64) (a4 : BitVec 64) (lds : List (List (BitVec 8)))
    (m0 : Std.ExtHashMap Nat (BitVec 8)) :
    Triple (SegPre resolveX07e4TSeg (resolveX07e4TL a5 a4) lds 0x800007e4#64 m0)
      (ResolveX07e4TPost a5 a4 lds m0) := by
  apply segToTriple resolveX07e4TSeg (resolveX07e4TL a5 a4) lds 0x800007e4#64 m0
    (ResolveX07e4TPost a5 a4 lds m0)
    (by have h : keysG (resolveX07e4TL a5 a4) = [15, 14] := rfl
        rw [h]; show ChainOK 0x800007e4#64 [15, 14] resolveX07e4TSeg; decide)
  intro σ' i' u' hG' hi' hmem' hpc' hmi' hregs
  refine ⟨hG', hmem', ?_, hi', hmi', hregs⟩
  rw [hpc']
  show some (evalBlocksPC 0x800007e4#64 (SegEvalState.init (resolveX07e4TL a5 a4) lds) resolveX07e4TSeg)
    = some 0x80000604#64
  rfl

#print axioms resolveX07e4TRow

/- The `resolveX07e4F` span body `0x800007e4 → 0x800007ec` (br-terminated, 1 block(s)), decoded from the pinned runtime ELF. -/
#derive_case resolveX07e4FSeg chain
  [(0x800007e4#64, 0x40e787b3#32),  -- sub a5,a5,a4
   (0x800007e8#64, 0x00100693#32)]  -- li a3,1
    terminator ⟨0x800007ec#64, 0xe0d79ce3#32, 0xe3#8, 0x9c#8, 0xd7#8, 0xe0#8, .br bop.BNE false, 15, 13, 0x1e18#13, 0#21, 0#12⟩

/-- The `resolveX07e4F` entry pin list — the registers the body reads: `x15`, `x14`. -/
def resolveX07e4FL (a5 a4 : BitVec 64) : GRegs := [(15, a5), (14, a4)]

/-- The `resolveX07e4F` row post: parked at the computed end PC `0x800007f0#64`, memory = the entry memory with the seg's write-log applied (computed off `#derive_case`). -/
structure ResolveX07e4FPost (a5 : BitVec 64) (a4 : BitVec 64) (lds : List (List (BitVec 8)))
    (m0 : Std.ExtHashMap Nat (BitVec 8)) (c : Config) : Prop where
  good : GoodState c.σ
  memory : c.σ.mem = writeLog m0 (evalBlocks resolveX07e4FSeg
    (SegEvalState.init (resolveX07e4FL a5 a4) lds)).log
  pc : c.σ.regs.get? Register.PC = some 0x800007f0#64
  tick : c.tick < 2
  minstret : ∃ w, c.σ.regs.get? Register.minstret = some w
  registers : GHolds c.σ (evalBlocks resolveX07e4FSeg (SegEvalState.init (resolveX07e4FL a5 a4) lds)).regs

/-- **`resolveX07e4FRow`** — the `resolveX07e4F` span as a `Triple`, via `segToTriple` over the br-terminated `resolveX07e4FSeg`.  `hwf` is the row's one kernel `decide` (`ChainOK`); `hpost` projects the computed end PC (0x800007f0#64) and the write-log memory off the outcome.  Replaces the hand `site_*` `stepObs` battery for this span. -/
theorem resolveX07e4FRow (a5 : BitVec 64) (a4 : BitVec 64) (lds : List (List (BitVec 8)))
    (m0 : Std.ExtHashMap Nat (BitVec 8)) :
    Triple (SegPre resolveX07e4FSeg (resolveX07e4FL a5 a4) lds 0x800007e4#64 m0)
      (ResolveX07e4FPost a5 a4 lds m0) := by
  apply segToTriple resolveX07e4FSeg (resolveX07e4FL a5 a4) lds 0x800007e4#64 m0
    (ResolveX07e4FPost a5 a4 lds m0)
    (by have h : keysG (resolveX07e4FL a5 a4) = [15, 14] := rfl
        rw [h]; show ChainOK 0x800007e4#64 [15, 14] resolveX07e4FSeg; decide)
  intro σ' i' u' hG' hi' hmem' hpc' hmi' hregs
  refine ⟨hG', hmem', ?_, hi', hmi', hregs⟩
  rw [hpc']
  show some (evalBlocksPC 0x800007e4#64 (SegEvalState.init (resolveX07e4FL a5 a4) lds) resolveX07e4FSeg)
    = some 0x800007f0#64
  rfl

#print axioms resolveX07e4FRow

end Vsa.Sim