import OCaml.Vm.Boot.Startup.Call
import Vsa.Sim.FnSummary
import Vsa.Sim.Code.Caml_search_exe_in_path
import Vsa.Sim.ElfDecode.Part205

/-! GENERATED by scripts/gen_startup_rows.py via gen_sites.py. -/
namespace OCaml.Vm.Boot.Startup
open Vsa.Machine Vsa.Sim LeanRV64DExecutable LeanRV64DExecutable.Functions Sail

/-- 0x80025574: `jal x1,0x80025404` (link `x1 := 0x80025578`). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80025574_startup (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.Caml_search_exe_in_pathLoaded σ.mem)
    (hpcv : pc = (0x80025574#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jal σ pc vminstret (0x1ffe90#21) Register.x1 (BitVec.addInt pc 4)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.caml_search_exe_in_path_at_80025574 hmem
  refine stepObs_jal σ i u (0x80025574#64) vminstret (0xe91ff0ef#32) (0x1ffe90#21)
    (regidx.Regidx 0x01#5) Register.x1 (BitVec.addInt (0x80025574#64) 4)
    (0xef#8) (0xf0#8) (0x1f#8) (0xe9#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide) (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_e91ff0ef (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide) ?_ hi
  exact wX_bits_x1 _ (BitVec.addInt (0x80025574#64) 4)


theorem call_80025574 (c : Config) (good : GoodState c.σ) (tick : c.tick < 2)
    (code : Vsa.Sim.Code.Caml_search_exe_in_pathLoaded c.σ.mem) :
    FnSummary 0x80025574#64 (fun d => d = c)
      (CallPost 0x80025404#64 0x80025578#64 c) := by
  constructor
  rintro d ⟨pc, eq⟩
  subst d
  obtain ⟨vm, hvm⟩ := good.minstret
  obtain ⟨σ, tick', step, bound, good', memory, obs⟩ :=
    site_80025574_startup c.σ c.tick c.steps _ vm good pc hvm code rfl tick
  exact ⟨⟨σ, tick', c.steps + 1⟩, Steps.single step,
    CallPost.of_obs good' bound memory obs (by decide)⟩

end OCaml.Vm.Boot.Startup
