import OCaml.Vm.Boot.Startup.SearchInPathScanRows

/-! GENERATED by scripts/gen_startup_rows.py via gen_fn.ocaml_literal_mline. -/
namespace OCaml.Vm.Boot.Startup
open Vsa.Sim

theorem searchinpathscan_line_80025434 :
    mkLine 0x80025434#64 0x00074783#32 =
      ⟨0x80025434#64, 0x00074783#32, 0x83#8, 0x47#8, 0x07#8, 0x00#8, .lbu, 15, 14, 0, 0x000#12⟩ := by rfl

theorem searchinpathscan_line_8002543c :
    mkLine 0x8002543c#64 0x00170713#32 =
      ⟨0x8002543c#64, 0x00170713#32, 0x13#8, 0x07#8, 0x17#8, 0x00#8, .addi, 14, 14, 0, 0x001#12⟩ := by rfl

end OCaml.Vm.Boot.Startup
