import OCaml.Vm.Primitives.Call
import OCaml.Vm.Boot.Startup.StrdupCopyImage
import Vsa.Sim.ElfDecode.Part121

/-! GENERATED by scripts/gen_startup_rows.py via ocaml_block_certificates.emit_call. -/
namespace OCaml.Vm.Boot.Startup
open Vsa.Machine Vsa.Sim OCaml.Vm.Primitives

def jal_8000be2c_call : CallInstr := ⟨0x8000be2c#64, 0x21d360ef#32, 0xef#8, 0x60#8, 0xd3#8, 0x21#8, 0x036a1c#21⟩
theorem jal_8000be2c_call_shape : CallShape jal_8000be2c_call := by constructor <;> decide
theorem jal_8000be2c_call_decode : CallDecode jal_8000be2c_call := by
  intro s hm hp he
  exact Vsa.Sim.ElfDecode.decode_21d360ef s hm hp he
theorem jal_8000be2c_call_target : jal_8000be2c_call.target = 0x80042848#64 := by decide
theorem jal_8000be2c_call_pins {c : Config} (h : ExecutableImage c) : CallPins jal_8000be2c_call c := by
  obtain ⟨h0, h1, h2, h3⟩ := Vsa.Sim.Code.caml_stat_strdup_at_8000be2c (strdupCopy_code h)
  exact ⟨h0, h1, h2, h3⟩

end OCaml.Vm.Boot.Startup
