import Vsa.Sim.DecodeNF

/-! GENERATED by scripts/gen_elf_decode.py. Every disassembled ELF word,
including all census-reachable functions. Statements are checked against Sail. -/

open LeanRV64DExecutable Sail ConcurrencyInterfaceV1
namespace Vsa.Sim.ElfDecode
variable (σ : SequentialState RegisterType trivialChoiceSource)
  (hmisa : σ.regs.get? Register.misa = some Vsa.Sim.initMisa)
  (hpriv : σ.regs.get? Register.cur_privilege = some Privilege.Machine)
  (hsec : σ.regs.get? Register.mseccfg = some (0#64))
include hmisa hpriv hsec

theorem decode_628070ef :
    (Functions.ext_decode 1652584687#32).run σ = .ok (instruction.JAL (30248#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_628100ef :
    (Functions.ext_decode 1652621551#32).run σ = .ok (instruction.JAL (67112#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_628120ef :
    (Functions.ext_decode 1652629743#32).run σ = .ok (instruction.JAL (75304#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_628230ef :
    (Functions.ext_decode 1652699375#32).run σ = .ok (instruction.JAL (144936#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62858593 :
    (Functions.ext_decode 1652917651#32).run σ = .ok (instruction.ITYPE (1576#12, regidx.Regidx 11#5, regidx.Regidx 11#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62873703 :
    (Functions.ext_decode 1653028611#32).run σ = .ok (instruction.LOAD (1576#12, regidx.Regidx 14#5, regidx.Regidx 14#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6287b783 :
    (Functions.ext_decode 1653061507#32).run σ = .ok (instruction.LOAD (1576#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62880813 :
    (Functions.ext_decode 1653082131#32).run σ = .ok (instruction.ITYPE (1576#12, regidx.Regidx 16#5, regidx.Regidx 16#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_629030ef :
    (Functions.ext_decode 1653616879#32).run σ = .ok (instruction.JAL (15912#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_629060ef :
    (Functions.ext_decode 1653629167#32).run σ = .ok (instruction.JAL (28200#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_629070ef :
    (Functions.ext_decode 1653633263#32).run σ = .ok (instruction.JAL (32296#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_629100ef :
    (Functions.ext_decode 1653670127#32).run σ = .ok (instruction.JAL (69160#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62ae0e1b :
    (Functions.ext_decode 1655574043#32).run σ = .ok (instruction.ADDIW (1578#12, regidx.Regidx 28#5, regidx.Regidx 28#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62c000ef :
    (Functions.ext_decode 1656750319#32).run σ = .ok (instruction.JAL (1580#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62c040ef :
    (Functions.ext_decode 1656766703#32).run σ = .ok (instruction.JAL (17964#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62c050ef :
    (Functions.ext_decode 1656770799#32).run σ = .ok (instruction.JAL (22060#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62c300ef :
    (Functions.ext_decode 1656946927#32).run σ = .ok (instruction.JAL (198188#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62c50513 :
    (Functions.ext_decode 1657079059#32).run σ = .ok (instruction.ITYPE (1580#12, regidx.Regidx 10#5, regidx.Regidx 10#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62c58593 :
    (Functions.ext_decode 1657111955#32).run σ = .ok (instruction.ITYPE (1580#12, regidx.Regidx 11#5, regidx.Regidx 11#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62c5b583 :
    (Functions.ext_decode 1657124227#32).run σ = .ok (instruction.LOAD (1580#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62c7b783 :
    (Functions.ext_decode 1657255811#32).run σ = .ok (instruction.LOAD (1580#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62cf8f93 :
    (Functions.ext_decode 1657769875#32).run σ = .ok (instruction.ITYPE (1580#12, regidx.Regidx 31#5, regidx.Regidx 31#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62d060ef :
    (Functions.ext_decode 1657823471#32).run σ = .ok (instruction.JAL (28204#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_62d1f0ef :
    (Functions.ext_decode 1657925871#32).run σ = .ok (instruction.JAL (130604#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_630000ef :
    (Functions.ext_decode 1660944623#32).run σ = .ok (instruction.JAL (1584#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63050513 :
    (Functions.ext_decode 1661273363#32).run σ = .ok (instruction.ITYPE (1584#12, regidx.Regidx 10#5, regidx.Regidx 10#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_631130ef :
    (Functions.ext_decode 1662071023#32).run σ = .ok (instruction.JAL (81456#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_631160ef :
    (Functions.ext_decode 1662083311#32).run σ = .ok (instruction.JAL (93744#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6317b223 :
    (Functions.ext_decode 1662497315#32).run σ = .ok (instruction.STORE (1572#12, regidx.Regidx 17#5, regidx.Regidx 15#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_634010ef :
    (Functions.ext_decode 1665143023#32).run σ = .ok (instruction.JAL (5684#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63498993 :
    (Functions.ext_decode 1665763731#32).run σ = .ok (instruction.ITYPE (1588#12, regidx.Regidx 19#5, regidx.Regidx 19#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_635040ef :
    (Functions.ext_decode 1666203887#32).run σ = .ok (instruction.JAL (20020#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_635060ef :
    (Functions.ext_decode 1666212079#32).run σ = .ok (instruction.JAL (28212#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6350e0ef :
    (Functions.ext_decode 1666244847#32).run σ = .ok (instruction.JAL (60980#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_638020ef :
    (Functions.ext_decode 1669341423#32).run σ = .ok (instruction.JAL (9784#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_638060ef :
    (Functions.ext_decode 1669357807#32).run σ = .ok (instruction.JAL (26168#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_638080ef :
    (Functions.ext_decode 1669365999#32).run σ = .ok (instruction.JAL (34360#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_638100ef :
    (Functions.ext_decode 1669398767#32).run σ = .ok (instruction.JAL (67128#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6381c0ef :
    (Functions.ext_decode 1669447919#32).run σ = .ok (instruction.JAL (116280#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6382a0ef :
    (Functions.ext_decode 1669505263#32).run σ = .ok (instruction.JAL (173624#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6383a0ef :
    (Functions.ext_decode 1669570799#32).run σ = .ok (instruction.JAL (239160#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6385b583 :
    (Functions.ext_decode 1669707139#32).run σ = .ok (instruction.LOAD (1592#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63868693 :
    (Functions.ext_decode 1669760659#32).run σ = .ok (instruction.ITYPE (1592#12, regidx.Regidx 13#5, regidx.Regidx 13#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_639050ef :
    (Functions.ext_decode 1670402287#32).run σ = .ok (instruction.JAL (24120#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_639060ef :
    (Functions.ext_decode 1670406383#32).run σ = .ok (instruction.JAL (28216#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6392c0ef :
    (Functions.ext_decode 1670562031#32).run σ = .ok (instruction.JAL (183864#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63bb52e3 :
    (Functions.ext_decode 1673220835#32).run σ = .ok (instruction.BTYPE (3620#13, regidx.Regidx 27#5, regidx.Regidx 22#5, bop.BGE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63c050ef :
    (Functions.ext_decode 1673548015#32).run σ = .ok (instruction.JAL (22076#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63c50513 :
    (Functions.ext_decode 1673856275#32).run σ = .ok (instruction.ITYPE (1596#12, regidx.Regidx 10#5, regidx.Regidx 10#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63c53503 :
    (Functions.ext_decode 1673868547#32).run σ = .ok (instruction.LOAD (1596#12, regidx.Regidx 10#5, regidx.Regidx 10#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63c7b783 :
    (Functions.ext_decode 1674033027#32).run σ = .ok (instruction.LOAD (1596#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63cb0b13 :
    (Functions.ext_decode 1674251027#32).run σ = .ok (instruction.ITYPE (1596#12, regidx.Regidx 22#5, regidx.Regidx 22#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63d070ef :
    (Functions.ext_decode 1674604783#32).run σ = .ok (instruction.JAL (32316#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_63d2c0ef :
    (Functions.ext_decode 1674756335#32).run σ = .ok (instruction.JAL (183868#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_640010ef :
    (Functions.ext_decode 1677725935#32).run σ = .ok (instruction.JAL (5696#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_640020ef :
    (Functions.ext_decode 1677730031#32).run σ = .ok (instruction.JAL (9792#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_640040ef :
    (Functions.ext_decode 1677738223#32).run σ = .ok (instruction.JAL (17984#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_640050ef :
    (Functions.ext_decode 1677742319#32).run σ = .ok (instruction.JAL (22080#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_640090ef :
    (Functions.ext_decode 1677758703#32).run σ = .ok (instruction.JAL (38464#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64068ce3 :
    (Functions.ext_decode 1678150883#32).run σ = .ok (instruction.BTYPE (3672#13, regidx.Regidx 0#5, regidx.Regidx 13#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64073e23 :
    (Functions.ext_decode 1678196259#32).run σ = .ok (instruction.STORE (1628#12, regidx.Regidx 0#5, regidx.Regidx 14#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64078a63 :
    (Functions.ext_decode 1678215779#32).run σ = .ok (instruction.BTYPE (1620#13, regidx.Regidx 0#5, regidx.Regidx 15#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_640a0063 :
    (Functions.ext_decode 1678377059#32).run σ = .ok (instruction.BTYPE (1600#13, regidx.Regidx 0#5, regidx.Regidx 20#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_640c10e3 :
    (Functions.ext_decode 1678512355#32).run σ = .ok (instruction.BTYPE (3648#13, regidx.Regidx 0#5, regidx.Regidx 24#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_640f8a63 :
    (Functions.ext_decode 1678740067#32).run σ = .ok (instruction.BTYPE (1620#13, regidx.Regidx 0#5, regidx.Regidx 31#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_641000ef :
    (Functions.ext_decode 1678770415#32).run σ = .ok (instruction.JAL (3648#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_641060ef :
    (Functions.ext_decode 1678794991#32).run σ = .ok (instruction.JAL (28224#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_641070ef :
    (Functions.ext_decode 1678799087#32).run σ = .ok (instruction.JAL (32320#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_641080ef :
    (Functions.ext_decode 1678803183#32).run σ = .ok (instruction.JAL (36416#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_644000ef :
    (Functions.ext_decode 1681916143#32).run σ = .ok (instruction.JAL (1604#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_644060ef :
    (Functions.ext_decode 1681940719#32).run σ = .ok (instruction.JAL (26180#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6442b0ef :
    (Functions.ext_decode 1682092271#32).run σ = .ok (instruction.JAL (177732#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6445b583 :
    (Functions.ext_decode 1682290051#32).run σ = .ok (instruction.LOAD (1604#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_645040ef :
    (Functions.ext_decode 1682981103#32).run σ = .ok (instruction.JAL (20036#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_645070ef :
    (Functions.ext_decode 1682993391#32).run σ = .ok (instruction.JAL (32324#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6480106f :
    (Functions.ext_decode 1686114415#32).run σ = .ok (instruction.JAL (5704#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_648010ef :
    (Functions.ext_decode 1686114543#32).run σ = .ok (instruction.JAL (5704#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_648050ef :
    (Functions.ext_decode 1686130927#32).run σ = .ok (instruction.JAL (22088#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6484b483 :
    (Functions.ext_decode 1686418563#32).run σ = .ok (instruction.LOAD (1608#12, regidx.Regidx 9#5, regidx.Regidx 9#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64853503 :
    (Functions.ext_decode 1686451459#32).run σ = .ok (instruction.LOAD (1608#12, regidx.Regidx 10#5, regidx.Regidx 10#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64858593 :
    (Functions.ext_decode 1686472083#32).run σ = .ok (instruction.ITYPE (1608#12, regidx.Regidx 11#5, regidx.Regidx 11#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64863603 :
    (Functions.ext_decode 1686517251#32).run σ = .ok (instruction.LOAD (1608#12, regidx.Regidx 12#5, regidx.Regidx 12#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6487bc23 :
    (Functions.ext_decode 1686617123#32).run σ = .ok (instruction.STORE (1624#12, regidx.Regidx 8#5, regidx.Regidx 15#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_648a8a93 :
    (Functions.ext_decode 1686801043#32).run σ = .ok (instruction.ITYPE (1608#12, regidx.Regidx 21#5, regidx.Regidx 21#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_649030ef :
    (Functions.ext_decode 1687171311#32).run σ = .ok (instruction.JAL (15944#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_649040ef :
    (Functions.ext_decode 1687175407#32).run σ = .ok (instruction.JAL (20040#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64c000ef :
    (Functions.ext_decode 1690304751#32).run σ = .ok (instruction.JAL (1612#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64c050ef :
    (Functions.ext_decode 1690325231#32).run σ = .ok (instruction.JAL (22092#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64c060ef :
    (Functions.ext_decode 1690329327#32).run σ = .ok (instruction.JAL (26188#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64c080ef :
    (Functions.ext_decode 1690337519#32).run σ = .ok (instruction.JAL (34380#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64c150ef :
    (Functions.ext_decode 1690390767#32).run σ = .ok (instruction.JAL (87628#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64c3006f :
    (Functions.ext_decode 1690501231#32).run σ = .ok (instruction.JAL (198220#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64c3a0ef :
    (Functions.ext_decode 1690542319#32).run σ = .ok (instruction.JAL (239180#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64c40413 :
    (Functions.ext_decode 1690567699#32).run σ = .ok (instruction.ITYPE (1612#12, regidx.Regidx 8#5, regidx.Regidx 8#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64d020ef :
    (Functions.ext_decode 1691361519#32).run σ = .ok (instruction.JAL (11852#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64d030ef :
    (Functions.ext_decode 1691365615#32).run σ = .ok (instruction.JAL (15948#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64d75663 :
    (Functions.ext_decode 1691833955#32).run σ = .ok (instruction.BTYPE (1612#13, regidx.Regidx 13#5, regidx.Regidx 14#5, bop.BGE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64d78e63 :
    (Functions.ext_decode 1691848291#32).run σ = .ok (instruction.BTYPE (1628#13, regidx.Regidx 13#5, regidx.Regidx 15#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_64f70c63 :
    (Functions.ext_decode 1693912163#32).run σ = .ok (instruction.BTYPE (1624#13, regidx.Regidx 15#5, regidx.Regidx 14#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_650020ef :
    (Functions.ext_decode 1694507247#32).run σ = .ok (instruction.JAL (9808#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_650050ef :
    (Functions.ext_decode 1694519535#32).run σ = .ok (instruction.JAL (22096#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_650100ef :
    (Functions.ext_decode 1694564591#32).run σ = .ok (instruction.JAL (67152#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_650240ef :
    (Functions.ext_decode 1694646511#32).run σ = .ok (instruction.JAL (149072#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_650330ef :
    (Functions.ext_decode 1694707951#32).run σ = .ok (instruction.JAL (210512#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6505b583 :
    (Functions.ext_decode 1694872963#32).run σ = .ok (instruction.LOAD (1616#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6507b783 :
    (Functions.ext_decode 1695004547#32).run σ = .ok (instruction.LOAD (1616#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65090913 :
    (Functions.ext_decode 1695090963#32).run σ = .ok (instruction.ITYPE (1616#12, regidx.Regidx 18#5, regidx.Regidx 18#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_651070ef :
    (Functions.ext_decode 1695576303#32).run σ = .ok (instruction.JAL (32336#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6512c0ef :
    (Functions.ext_decode 1695727855#32).run σ = .ok (instruction.JAL (183888#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6513b0ef :
    (Functions.ext_decode 1695789295#32).run σ = .ok (instruction.JAL (245328#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65159463 :
    (Functions.ext_decode 1695913059#32).run σ = .ok (instruction.BTYPE (1608#13, regidx.Regidx 17#5, regidx.Regidx 11#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6540206f :
    (Functions.ext_decode 1698701423#32).run σ = .ok (instruction.JAL (9812#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_654040ef :
    (Functions.ext_decode 1698709743#32).run σ = .ok (instruction.JAL (18004#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_654130ef :
    (Functions.ext_decode 1698771183#32).run σ = .ok (instruction.JAL (79444#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65450513 :
    (Functions.ext_decode 1699022099#32).run σ = .ok (instruction.ITYPE (1620#12, regidx.Regidx 10#5, regidx.Regidx 10#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_655030ef :
    (Functions.ext_decode 1699754223#32).run σ = .ok (instruction.JAL (15956#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_655060ef :
    (Functions.ext_decode 1699766511#32).run σ = .ok (instruction.JAL (28244#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_655b6a37 :
    (Functions.ext_decode 1700489783#32).run σ = .ok (instruction.UTYPE (415158#20, regidx.Regidx 20#5, uop.LUI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6567c663 :
    (Functions.ext_decode 1701299811#32).run σ = .ok (instruction.BTYPE (1612#13, regidx.Regidx 22#5, regidx.Regidx 15#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_658020ef :
    (Functions.ext_decode 1702895855#32).run σ = .ok (instruction.JAL (9816#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_6581b0ef :
    (Functions.ext_decode 1702998255#32).run σ = .ok (instruction.JAL (112216#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65850513 :
    (Functions.ext_decode 1703216403#32).run σ = .ok (instruction.ITYPE (1624#12, regidx.Regidx 10#5, regidx.Regidx 10#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65868693 :
    (Functions.ext_decode 1703315091#32).run σ = .ok (instruction.ITYPE (1624#12, regidx.Regidx 13#5, regidx.Regidx 13#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65890913 :
    (Functions.ext_decode 1703479571#32).run σ = .ok (instruction.ITYPE (1624#12, regidx.Regidx 18#5, regidx.Regidx 18#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65c030ef :
    (Functions.ext_decode 1707094255#32).run σ = .ok (instruction.JAL (13916#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65c50513 :
    (Functions.ext_decode 1707410707#32).run σ = .ok (instruction.ITYPE (1628#12, regidx.Regidx 10#5, regidx.Regidx 10#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65d030ef :
    (Functions.ext_decode 1708142831#32).run σ = .ok (instruction.JAL (15964#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_65d040ef :
    (Functions.ext_decode 1708146927#32).run σ = .ok (instruction.JAL (20060#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

end Vsa.Sim.ElfDecode
