import Vsa.Sim.DecodeNF

/-! GENERATED by scripts/gen_elf_decode.py. Every disassembled ELF word,
including all census-reachable functions. Statements are checked against Sail. -/

open LeanRV64DExecutable Sail ConcurrencyInterfaceV1
namespace Vsa.Sim.ElfDecode
variable (σ : SequentialState RegisterType trivialChoiceSource)
  (hmisa : σ.regs.get? Register.misa = some Vsa.Sim.initMisa)
  (hpriv : σ.regs.get? Register.cur_privilege = some Privilege.Machine)
  (hsec : σ.regs.get? Register.mseccfg = some (0#64))
include hmisa hpriv hsec

theorem decode_e1b43823 :
    (Functions.ext_decode 3786684451#32).run σ = .ok (instruction.STORE (3600#12, regidx.Regidx 27#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1c58593 :
    (Functions.ext_decode 3787818387#32).run σ = .ok (instruction.ITYPE (3612#12, regidx.Regidx 11#5, regidx.Regidx 11#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1c5b583 :
    (Functions.ext_decode 3787830659#32).run σ = .ok (instruction.LOAD (3612#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1cf20ef :
    (Functions.ext_decode 3788447983#32).run σ = .ok (instruction.JAL (2041372#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1cf30ef :
    (Functions.ext_decode 3788452079#32).run σ = .ok (instruction.JAL (2045468#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1cf50ef :
    (Functions.ext_decode 3788460271#32).run σ = .ok (instruction.JAL (2053660#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1cfe0ef :
    (Functions.ext_decode 3788497135#32).run σ = .ok (instruction.JAL (2090524#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1cff0ef :
    (Functions.ext_decode 3788501231#32).run σ = .ok (instruction.JAL (2094620#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1de40ef :
    (Functions.ext_decode 3789439215#32).run σ = .ok (instruction.JAL (1986076#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1de90ef :
    (Functions.ext_decode 3789459695#32).run σ = .ok (instruction.JAL (2006556#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1dea0ef :
    (Functions.ext_decode 3789463791#32).run σ = .ok (instruction.JAL (2010652#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1deb0ef :
    (Functions.ext_decode 3789467887#32).run σ = .ok (instruction.JAL (2014748#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1dfb0ef :
    (Functions.ext_decode 3789533423#32).run σ = .ok (instruction.JAL (2080284#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1dfd06f :
    (Functions.ext_decode 3789541487#32).run σ = .ok (instruction.JAL (2088476#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1dff06f :
    (Functions.ext_decode 3789549679#32).run σ = .ok (instruction.JAL (2096668#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1dff0ef :
    (Functions.ext_decode 3789549807#32).run σ = .ok (instruction.JAL (2096668#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1f60613 :
    (Functions.ext_decode 3790997011#32).run σ = .ok (instruction.ITYPE (3615#12, regidx.Regidx 12#5, regidx.Regidx 12#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e1f88893 :
    (Functions.ext_decode 3791161491#32).run σ = .ok (instruction.ITYPE (3615#12, regidx.Regidx 17#5, regidx.Regidx 17#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2043023 :
    (Functions.ext_decode 3791925283#32).run σ = .ok (instruction.STORE (3616#12, regidx.Regidx 0#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2043683 :
    (Functions.ext_decode 3791926915#32).run σ = .ok (instruction.LOAD (3616#12, regidx.Regidx 8#5, regidx.Regidx 13#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2043823 :
    (Functions.ext_decode 3791927331#32).run σ = .ok (instruction.STORE (3632#12, regidx.Regidx 0#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2043883 :
    (Functions.ext_decode 3791927427#32).run σ = .ok (instruction.LOAD (3616#12, regidx.Regidx 8#5, regidx.Regidx 17#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2043c23 :
    (Functions.ext_decode 3791928355#32).run σ = .ok (instruction.STORE (3640#12, regidx.Regidx 0#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20504e3 :
    (Functions.ext_decode 3791979747#32).run σ = .ok (instruction.BTYPE (7720#13, regidx.Regidx 0#5, regidx.Regidx 10#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20514e3 :
    (Functions.ext_decode 3791983843#32).run σ = .ok (instruction.BTYPE (7720#13, regidx.Regidx 0#5, regidx.Regidx 10#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20518e3 :
    (Functions.ext_decode 3791984867#32).run σ = .ok (instruction.BTYPE (7728#13, regidx.Regidx 0#5, regidx.Regidx 10#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2051a63 :
    (Functions.ext_decode 3791985251#32).run σ = .ok (instruction.BTYPE (5684#13, regidx.Regidx 0#5, regidx.Regidx 10#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2054ae3 :
    (Functions.ext_decode 3791997667#32).run σ = .ok (instruction.BTYPE (7732#13, regidx.Regidx 0#5, regidx.Regidx 10#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2071ee3 :
    (Functions.ext_decode 3792117475#32).run σ = .ok (instruction.BTYPE (7740#13, regidx.Regidx 0#5, regidx.Regidx 14#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20746e3 :
    (Functions.ext_decode 3792127715#32).run σ = .ok (instruction.BTYPE (7724#13, regidx.Regidx 0#5, regidx.Regidx 14#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2078ce3 :
    (Functions.ext_decode 3792145635#32).run σ = .ok (instruction.BTYPE (7736#13, regidx.Regidx 0#5, regidx.Regidx 15#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2078ee3 :
    (Functions.ext_decode 3792146147#32).run σ = .ok (instruction.BTYPE (7740#13, regidx.Regidx 0#5, regidx.Regidx 15#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e207b223 :
    (Functions.ext_decode 3792155171#32).run σ = .ok (instruction.STORE (3620#12, regidx.Regidx 0#5, regidx.Regidx 15#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e207b783 :
    (Functions.ext_decode 3792156547#32).run σ = .ok (instruction.LOAD (3616#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20a9ce3 :
    (Functions.ext_decode 3792346339#32).run σ = .ok (instruction.BTYPE (7736#13, regidx.Regidx 0#5, regidx.Regidx 21#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20b14e3 :
    (Functions.ext_decode 3792377059#32).run σ = .ok (instruction.BTYPE (7720#13, regidx.Regidx 0#5, regidx.Regidx 22#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20e70ef :
    (Functions.ext_decode 3792597231#32).run σ = .ok (instruction.JAL (1996320#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20fe06f :
    (Functions.ext_decode 3792691311#32).run σ = .ok (instruction.JAL (2090528#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e20ff06f :
    (Functions.ext_decode 3792695407#32).run σ = .ok (instruction.JAL (2094624#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e21fa06f :
    (Functions.ext_decode 3793723503#32).run σ = .ok (instruction.JAL (2076192#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e21fd06f :
    (Functions.ext_decode 3793735791#32).run σ = .ok (instruction.JAL (2088480#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e21ff06f :
    (Functions.ext_decode 3793743983#32).run σ = .ok (instruction.JAL (2096672#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2243c23 :
    (Functions.ext_decode 3794025507#32).run σ = .ok (instruction.STORE (3640#12, regidx.Regidx 2#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2472703 :
    (Functions.ext_decode 3796313859#32).run σ = .ok (instruction.LOAD (3620#12, regidx.Regidx 14#5, regidx.Regidx 14#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e24aaa83 :
    (Functions.ext_decode 3796544131#32).run σ = .ok (instruction.LOAD (3620#12, regidx.Regidx 21#5, regidx.Regidx 21#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e24e70ef :
    (Functions.ext_decode 3796791535#32).run σ = .ok (instruction.JAL (1996324#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e24ff0ef :
    (Functions.ext_decode 3796889839#32).run σ = .ok (instruction.JAL (2094628#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e25f80ef :
    (Functions.ext_decode 3797909743#32).run σ = .ok (instruction.JAL (2068004#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e25fb0ef :
    (Functions.ext_decode 3797922031#32).run σ = .ok (instruction.JAL (2080292#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e25fe06f :
    (Functions.ext_decode 3797934191#32).run σ = .ok (instruction.JAL (2092580#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e25ff06f :
    (Functions.ext_decode 3797938287#32).run σ = .ok (instruction.JAL (2096676#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e25ff0ef :
    (Functions.ext_decode 3797938415#32).run σ = .ok (instruction.JAL (2096676#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2740493 :
    (Functions.ext_decode 3799254163#32).run σ = .ok (instruction.ITYPE (3623#12, regidx.Regidx 8#5, regidx.Regidx 9#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2740913 :
    (Functions.ext_decode 3799255315#32).run σ = .ok (instruction.ITYPE (3623#12, regidx.Regidx 8#5, regidx.Regidx 18#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2840613 :
    (Functions.ext_decode 3800303123#32).run σ = .ok (instruction.ITYPE (3624#12, regidx.Regidx 8#5, regidx.Regidx 12#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2840713 :
    (Functions.ext_decode 3800303379#32).run σ = .ok (instruction.ITYPE (3624#12, regidx.Regidx 8#5, regidx.Regidx 14#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2840793 :
    (Functions.ext_decode 3800303507#32).run σ = .ok (instruction.ITYPE (3624#12, regidx.Regidx 8#5, regidx.Regidx 15#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2843703 :
    (Functions.ext_decode 3800315651#32).run σ = .ok (instruction.LOAD (3624#12, regidx.Regidx 8#5, regidx.Regidx 14#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2843783 :
    (Functions.ext_decode 3800315779#32).run σ = .ok (instruction.LOAD (3624#12, regidx.Regidx 8#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2853503 :
    (Functions.ext_decode 3800380675#32).run σ = .ok (instruction.LOAD (3624#12, regidx.Regidx 10#5, regidx.Regidx 10#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e287b023 :
    (Functions.ext_decode 3800543267#32).run σ = .ok (instruction.STORE (3616#12, regidx.Regidx 8#5, regidx.Regidx 15#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e287ba23 :
    (Functions.ext_decode 3800545827#32).run σ = .ok (instruction.STORE (3636#12, regidx.Regidx 8#5, regidx.Regidx 15#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e28a8a93 :
    (Functions.ext_decode 3800730259#32).run σ = .ok (instruction.ITYPE (3624#12, regidx.Regidx 21#5, regidx.Regidx 21#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e28e006f :
    (Functions.ext_decode 3800957039#32).run σ = .ok (instruction.JAL (1967656#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e28e40ef :
    (Functions.ext_decode 3800973551#32).run σ = .ok (instruction.JAL (1984040#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e28eb0ef :
    (Functions.ext_decode 3801002223#32).run σ = .ok (instruction.JAL (2012712#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e28f10ef :
    (Functions.ext_decode 3801026799#32).run σ = .ok (instruction.JAL (2037288#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e28fe06f :
    (Functions.ext_decode 3801079919#32).run σ = .ok (instruction.JAL (2090536#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e28ff0ef :
    (Functions.ext_decode 3801084143#32).run σ = .ok (instruction.JAL (2094632#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e29e50ef :
    (Functions.ext_decode 3802026223#32).run σ = .ok (instruction.JAL (1990184#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e29f50ef :
    (Functions.ext_decode 3802091759#32).run σ = .ok (instruction.JAL (2055720#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e29fc0ef :
    (Functions.ext_decode 3802120431#32).run σ = .ok (instruction.JAL (2084392#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e29ff06f :
    (Functions.ext_decode 3802132591#32).run σ = .ok (instruction.JAL (2096680#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e29ff0ef :
    (Functions.ext_decode 3802132719#32).run σ = .ok (instruction.JAL (2096680#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2b792e3 :
    (Functions.ext_decode 3803681507#32).run σ = .ok (instruction.BTYPE (7716#13, regidx.Regidx 11#5, regidx.Regidx 15#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2c5b583 :
    (Functions.ext_decode 3804607875#32).run σ = .ok (instruction.LOAD (3628#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2c70423 :
    (Functions.ext_decode 3804693539#32).run σ = .ok (instruction.STORE (3624#12, regidx.Regidx 12#5, regidx.Regidx 14#5, 1)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2c73623 :
    (Functions.ext_decode 3804706339#32).run σ = .ok (instruction.STORE (3628#12, regidx.Regidx 12#5, regidx.Regidx 14#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2c73703 :
    (Functions.ext_decode 3804706563#32).run σ = .ok (instruction.LOAD (3628#12, regidx.Regidx 14#5, regidx.Regidx 14#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2c7b783 :
    (Functions.ext_decode 3804739459#32).run σ = .ok (instruction.LOAD (3628#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2cff06f :
    (Functions.ext_decode 3805278319#32).run σ = .ok (instruction.JAL (2094636#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2d43423 :
    (Functions.ext_decode 3805557795#32).run σ = .ok (instruction.STORE (3624#12, regidx.Regidx 13#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2d78423 :
    (Functions.ext_decode 3805774883#32).run σ = .ok (instruction.STORE (3624#12, regidx.Regidx 13#5, regidx.Regidx 15#5, 1)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2deb0ef :
    (Functions.ext_decode 3806245103#32).run σ = .ok (instruction.JAL (2014764#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2dff06f :
    (Functions.ext_decode 3806326895#32).run σ = .ok (instruction.JAL (2096684#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2e43423 :
    (Functions.ext_decode 3806606371#32).run σ = .ok (instruction.STORE (3624#12, regidx.Regidx 14#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2e690e3 :
    (Functions.ext_decode 3806761187#32).run σ = .ok (instruction.BTYPE (7712#13, regidx.Regidx 14#5, regidx.Regidx 13#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2e794e3 :
    (Functions.ext_decode 3806827747#32).run σ = .ok (instruction.BTYPE (7720#13, regidx.Regidx 14#5, regidx.Regidx 15#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f31ee3 :
    (Functions.ext_decode 3807583971#32).run σ = .ok (instruction.BTYPE (7740#13, regidx.Regidx 15#5, regidx.Regidx 6#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f43023 :
    (Functions.ext_decode 3807653923#32).run σ = .ok (instruction.STORE (3616#12, regidx.Regidx 15#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f43423 :
    (Functions.ext_decode 3807654947#32).run σ = .ok (instruction.STORE (3624#12, regidx.Regidx 15#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f43823 :
    (Functions.ext_decode 3807655971#32).run σ = .ok (instruction.STORE (3632#12, regidx.Regidx 15#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f558e3 :
    (Functions.ext_decode 3807729891#32).run σ = .ok (instruction.BTYPE (7728#13, regidx.Regidx 15#5, regidx.Regidx 10#5, bop.BGE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f718e3 :
    (Functions.ext_decode 3807844579#32).run σ = .ok (instruction.BTYPE (7728#13, regidx.Regidx 15#5, regidx.Regidx 14#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f72623 :
    (Functions.ext_decode 3807847971#32).run σ = .ok (instruction.STORE (3628#12, regidx.Regidx 15#5, regidx.Regidx 14#5, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f73023 :
    (Functions.ext_decode 3807850531#32).run σ = .ok (instruction.STORE (3616#12, regidx.Regidx 15#5, regidx.Regidx 14#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e2f73a23 :
    (Functions.ext_decode 3807853091#32).run σ = .ok (instruction.STORE (3636#12, regidx.Regidx 15#5, regidx.Regidx 14#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3043503 :
    (Functions.ext_decode 3808703747#32).run σ = .ok (instruction.LOAD (3632#12, regidx.Regidx 8#5, regidx.Regidx 10#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3043703 :
    (Functions.ext_decode 3808704259#32).run σ = .ok (instruction.LOAD (3632#12, regidx.Regidx 8#5, regidx.Regidx 14#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3043783 :
    (Functions.ext_decode 3808704387#32).run σ = .ok (instruction.LOAD (3632#12, regidx.Regidx 8#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3058593 :
    (Functions.ext_decode 3808789907#32).run σ = .ok (instruction.ITYPE (3632#12, regidx.Regidx 11#5, regidx.Regidx 11#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e307b783 :
    (Functions.ext_decode 3808933763#32).run σ = .ok (instruction.LOAD (3632#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3080813 :
    (Functions.ext_decode 3808954387#32).run σ = .ok (instruction.ITYPE (3632#12, regidx.Regidx 16#5, regidx.Regidx 16#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e30e80ef :
    (Functions.ext_decode 3809378543#32).run σ = .ok (instruction.JAL (2000432#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e30f00ef :
    (Functions.ext_decode 3809411311#32).run σ = .ok (instruction.JAL (2033200#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e30ff06f :
    (Functions.ext_decode 3809472623#32).run σ = .ok (instruction.JAL (2094640#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e30ff0ef :
    (Functions.ext_decode 3809472751#32).run σ = .ok (instruction.JAL (2094640#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3143023 :
    (Functions.ext_decode 3809751075#32).run σ = .ok (instruction.STORE (3616#12, regidx.Regidx 17#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e31f00ef :
    (Functions.ext_decode 3810459887#32).run σ = .ok (instruction.JAL (2035248#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e31ff06f :
    (Functions.ext_decode 3810521199#32).run σ = .ok (instruction.JAL (2096688#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e31ff0ef :
    (Functions.ext_decode 3810521327#32).run σ = .ok (instruction.JAL (2096688#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e345a583 :
    (Functions.ext_decode 3812992387#32).run σ = .ok (instruction.LOAD (3636#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3470713 :
    (Functions.ext_decode 3813082899#32).run σ = .ok (instruction.ITYPE (3636#12, regidx.Regidx 14#5, regidx.Regidx 14#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3490913 :
    (Functions.ext_decode 3813214483#32).run σ = .ok (instruction.ITYPE (3636#12, regidx.Regidx 18#5, regidx.Regidx 18#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e34e90ef :
    (Functions.ext_decode 3813576943#32).run σ = .ok (instruction.JAL (2004532#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e34f50ef :
    (Functions.ext_decode 3813626095#32).run σ = .ok (instruction.JAL (2053684#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e34ff0ef :
    (Functions.ext_decode 3813667055#32).run σ = .ok (instruction.JAL (2094644#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3543423 :
    (Functions.ext_decode 3813946403#32).run σ = .ok (instruction.STORE (3624#12, regidx.Regidx 21#5, regidx.Regidx 8#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e35ea0ef :
    (Functions.ext_decode 3814629615#32).run σ = .ok (instruction.JAL (2010676#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e35fe06f :
    (Functions.ext_decode 3814711407#32).run σ = .ok (instruction.JAL (2092596#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e35ff06f :
    (Functions.ext_decode 3814715503#32).run σ = .ok (instruction.JAL (2096692#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e35ff0ef :
    (Functions.ext_decode 3814715631#32).run σ = .ok (instruction.JAL (2096692#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3843683 :
    (Functions.ext_decode 3817092739#32).run σ = .ok (instruction.LOAD (3640#12, regidx.Regidx 8#5, regidx.Regidx 13#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3843703 :
    (Functions.ext_decode 3817092867#32).run σ = .ok (instruction.LOAD (3640#12, regidx.Regidx 8#5, regidx.Regidx 14#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3843783 :
    (Functions.ext_decode 3817092995#32).run σ = .ok (instruction.LOAD (3640#12, regidx.Regidx 8#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e385b583 :
    (Functions.ext_decode 3817190787#32).run σ = .ok (instruction.LOAD (3640#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e3873703 :
    (Functions.ext_decode 3817289475#32).run σ = .ok (instruction.LOAD (3640#12, regidx.Regidx 14#5, regidx.Regidx 14#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_e387b783 :
    (Functions.ext_decode 3817322371#32).run σ = .ok (instruction.LOAD (3640#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

end Vsa.Sim.ElfDecode
