import Vsa.Sim.DecodeNF

/-! GENERATED by scripts/gen_elf_decode.py. Every disassembled ELF word,
including all census-reachable functions. Statements are checked against Sail. -/

open LeanRV64DExecutable Sail ConcurrencyInterfaceV1
namespace Vsa.Sim.ElfDecode
variable (σ : SequentialState RegisterType trivialChoiceSource)
  (hmisa : σ.regs.get? Register.misa = some Vsa.Sim.initMisa)
  (hpriv : σ.regs.get? Register.cur_privilege = some Privilege.Machine)
  (hsec : σ.regs.get? Register.mseccfg = some (0#64))
include hmisa hpriv hsec

theorem decode_300b7793 :
    (Functions.ext_decode 806057875#32).run σ = .ok (instruction.ITYPE (768#12, regidx.Regidx 22#5, regidx.Regidx 15#5, iop.ANDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_300b8263 :
    (Functions.ext_decode 806060643#32).run σ = .ok (instruction.BTYPE (772#13, regidx.Regidx 0#5, regidx.Regidx 23#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_300cc663 :
    (Functions.ext_decode 806143587#32).run σ = .ok (instruction.BTYPE (780#13, regidx.Regidx 0#5, regidx.Regidx 25#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_300cf713 :
    (Functions.ext_decode 806156051#32).run σ = .ok (instruction.ITYPE (768#12, regidx.Regidx 25#5, regidx.Regidx 14#5, iop.ANDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_301010ef :
    (Functions.ext_decode 806359279#32).run σ = .ok (instruction.JAL (6912#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3010206f :
    (Functions.ext_decode 806363247#32).run σ = .ok (instruction.JAL (11008#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_301020ef :
    (Functions.ext_decode 806363375#32).run σ = .ok (instruction.JAL (11008#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3010f0ef :
    (Functions.ext_decode 806416623#32).run σ = .ok (instruction.JAL (64256#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3013b0ef :
    (Functions.ext_decode 806596847#32).run σ = .ok (instruction.JAL (244480#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30160613 :
    (Functions.ext_decode 806749715#32).run σ = .ok (instruction.ITYPE (769#12, regidx.Regidx 12#5, regidx.Regidx 12#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3040006f :
    (Functions.ext_decode 809500783#32).run σ = .ok (instruction.JAL (772#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_304010ef :
    (Functions.ext_decode 809505007#32).run σ = .ok (instruction.JAL (4868#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_304080ef :
    (Functions.ext_decode 809533679#32).run σ = .ok (instruction.JAL (33540#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3045b583 :
    (Functions.ext_decode 809874819#32).run σ = .ok (instruction.LOAD (772#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3047b783 :
    (Functions.ext_decode 810006403#32).run σ = .ok (instruction.LOAD (772#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_305240ef :
    (Functions.ext_decode 810696943#32).run σ = .ok (instruction.JAL (150276#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_308040ef :
    (Functions.ext_decode 813711599#32).run σ = .ok (instruction.JAL (17160#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_308050ef :
    (Functions.ext_decode 813715695#32).run σ = .ok (instruction.JAL (21256#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_308170ef :
    (Functions.ext_decode 813789423#32).run σ = .ok (instruction.JAL (94984#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3081a0ef :
    (Functions.ext_decode 813801711#32).run σ = .ok (instruction.JAL (107272#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30830313 :
    (Functions.ext_decode 813892371#32).run σ = .ok (instruction.ITYPE (776#12, regidx.Regidx 6#5, regidx.Regidx 6#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30848493 :
    (Functions.ext_decode 813991059#32).run σ = .ok (instruction.ITYPE (776#12, regidx.Regidx 9#5, regidx.Regidx 9#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3085b583 :
    (Functions.ext_decode 814069123#32).run σ = .ok (instruction.LOAD (776#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30872703 :
    (Functions.ext_decode 814163715#32).run σ = .ok (instruction.LOAD (776#12, regidx.Regidx 14#5, regidx.Regidx 14#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30878793 :
    (Functions.ext_decode 814188435#32).run σ = .ok (instruction.ITYPE (776#12, regidx.Regidx 15#5, regidx.Regidx 15#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_309010ef :
    (Functions.ext_decode 814747887#32).run σ = .ok (instruction.JAL (6920#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3093a0ef :
    (Functions.ext_decode 814981359#32).run σ = .ok (instruction.JAL (240392#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30a04063 :
    (Functions.ext_decode 815808611#32).run σ = .ok (instruction.BTYPE (768#13, regidx.Regidx 10#5, regidx.Regidx 0#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30a7a023 :
    (Functions.ext_decode 816291875#32).run σ = .ok (instruction.STORE (768#12, regidx.Regidx 10#5, regidx.Regidx 15#5, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30a7e663 :
    (Functions.ext_decode 816309859#32).run σ = .ok (instruction.BTYPE (780#13, regidx.Regidx 10#5, regidx.Regidx 15#5, bop.BLTU)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30b48263 :
    (Functions.ext_decode 817136227#32).run σ = .ok (instruction.BTYPE (772#13, regidx.Regidx 11#5, regidx.Regidx 9#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30b72223 :
    (Functions.ext_decode 817308195#32).run σ = .ok (instruction.STORE (772#12, regidx.Regidx 11#5, regidx.Regidx 14#5, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30c0106f :
    (Functions.ext_decode 817893487#32).run σ = .ok (instruction.JAL (4876#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30c060ef :
    (Functions.ext_decode 817914095#32).run σ = .ok (instruction.JAL (25356#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30c5b583 :
    (Functions.ext_decode 818263427#32).run σ = .ok (instruction.LOAD (780#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30c60613 :
    (Functions.ext_decode 818284051#32).run σ = .ok (instruction.ITYPE (780#12, regidx.Regidx 12#5, regidx.Regidx 12#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30c68693 :
    (Functions.ext_decode 818316947#32).run σ = .ok (instruction.ITYPE (780#12, regidx.Regidx 13#5, regidx.Regidx 13#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30c76a63 :
    (Functions.ext_decode 818375267#32).run σ = .ok (instruction.BTYPE (788#13, regidx.Regidx 12#5, regidx.Regidx 14#5, bop.BLTU)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30c7dc63 :
    (Functions.ext_decode 818404451#32).run σ = .ok (instruction.BTYPE (792#13, regidx.Regidx 12#5, regidx.Regidx 15#5, bop.BGE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30c7f063 :
    (Functions.ext_decode 818409571#32).run σ = .ok (instruction.BTYPE (768#13, regidx.Regidx 12#5, regidx.Regidx 15#5, bop.BGEU)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30d0206f :
    (Functions.ext_decode 818946159#32).run σ = .ok (instruction.JAL (11020#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30d05463 :
    (Functions.ext_decode 818959459#32).run σ = .ok (instruction.BTYPE (776#13, regidx.Regidx 13#5, regidx.Regidx 0#5, bop.BGE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30d080ef :
    (Functions.ext_decode 818970863#32).run σ = .ok (instruction.JAL (35596#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30d320ef :
    (Functions.ext_decode 819142895#32).run σ = .ok (instruction.JAL (207628#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30d7aa23 :
    (Functions.ext_decode 819440163#32).run σ = .ok (instruction.STORE (788#12, regidx.Regidx 13#5, regidx.Regidx 15#5, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30e68263 :
    (Functions.ext_decode 820413027#32).run σ = .ok (instruction.BTYPE (772#13, regidx.Regidx 14#5, regidx.Regidx 13#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30e78863 :
    (Functions.ext_decode 820480099#32).run σ = .ok (instruction.BTYPE (784#13, regidx.Regidx 14#5, regidx.Regidx 15#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30f00593 :
    (Functions.ext_decode 821036435#32).run σ = .ok (instruction.ITYPE (783#12, regidx.Regidx 0#5, regidx.Regidx 11#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30f6ca63 :
    (Functions.ext_decode 821480035#32).run σ = .ok (instruction.BTYPE (788#13, regidx.Regidx 15#5, regidx.Regidx 13#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30f74863 :
    (Functions.ext_decode 821512291#32).run σ = .ok (instruction.BTYPE (784#13, regidx.Regidx 15#5, regidx.Regidx 14#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_30fb02e3 :
    (Functions.ext_decode 821756643#32).run σ = .ok (instruction.BTYPE (2820#13, regidx.Regidx 15#5, regidx.Regidx 22#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_310080ef :
    (Functions.ext_decode 822116591#32).run σ = .ok (instruction.JAL (33552#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3101a0ef :
    (Functions.ext_decode 822190319#32).run σ = .ok (instruction.JAL (107280#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3102b0ef :
    (Functions.ext_decode 822259951#32).run σ = .ok (instruction.JAL (176912#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31053503 :
    (Functions.ext_decode 822424835#32).run σ = .ok (instruction.LOAD (784#12, regidx.Regidx 10#5, regidx.Regidx 10#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3105b583 :
    (Functions.ext_decode 822457731#32).run σ = .ok (instruction.LOAD (784#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3105c463 :
    (Functions.ext_decode 822461539#32).run σ = .ok (instruction.BTYPE (776#13, regidx.Regidx 16#5, regidx.Regidx 11#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31072423 :
    (Functions.ext_decode 822551587#32).run σ = .ok (instruction.STORE (776#12, regidx.Regidx 16#5, regidx.Regidx 14#5, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31075463 :
    (Functions.ext_decode 822563939#32).run σ = .ok (instruction.BTYPE (776#13, regidx.Regidx 16#5, regidx.Regidx 14#5, bop.BGE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3107a803 :
    (Functions.ext_decode 822585347#32).run σ = .ok (instruction.LOAD (784#12, regidx.Regidx 15#5, regidx.Regidx 16#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3107a823 :
    (Functions.ext_decode 822585379#32).run σ = .ok (instruction.STORE (784#12, regidx.Regidx 16#5, regidx.Regidx 15#5, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31092783 :
    (Functions.ext_decode 822683523#32).run σ = .ok (instruction.LOAD (784#12, regidx.Regidx 18#5, regidx.Regidx 15#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_311030ef :
    (Functions.ext_decode 823144687#32).run σ = .ok (instruction.JAL (15120#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_311050ef :
    (Functions.ext_decode 823152879#32).run σ = .ok (instruction.JAL (23312#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_311060ef :
    (Functions.ext_decode 823156975#32).run σ = .ok (instruction.JAL (27408#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_311130ef :
    (Functions.ext_decode 823210223#32).run σ = .ok (instruction.JAL (80656#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3112606f :
    (Functions.ext_decode 823287919#32).run σ = .ok (instruction.JAL (158480#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3112c0ef :
    (Functions.ext_decode 823312623#32).run σ = .ok (instruction.JAL (183056#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3116a023 :
    (Functions.ext_decode 823566371#32).run σ = .ok (instruction.STORE (768#12, regidx.Regidx 17#5, regidx.Regidx 13#5, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31172023 :
    (Functions.ext_decode 823599139#32).run σ = .ok (instruction.STORE (768#12, regidx.Regidx 17#5, regidx.Regidx 14#5, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3127ce63 :
    (Functions.ext_decode 824692323#32).run σ = .ok (instruction.BTYPE (796#13, regidx.Regidx 18#5, regidx.Regidx 15#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_314030ef :
    (Functions.ext_decode 826290415#32).run σ = .ok (instruction.JAL (13076#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_314070ef :
    (Functions.ext_decode 826306799#32).run σ = .ok (instruction.JAL (29460#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_314130ef :
    (Functions.ext_decode 826355951#32).run σ = .ok (instruction.JAL (78612#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3142829b :
    (Functions.ext_decode 826442395#32).run σ = .ok (instruction.ADDIW (788#12, regidx.Regidx 5#5, regidx.Regidx 5#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3142c0ef :
    (Functions.ext_decode 826458351#32).run σ = .ok (instruction.JAL (181012#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31468693 :
    (Functions.ext_decode 826705555#32).run σ = .ok (instruction.ITYPE (788#12, regidx.Regidx 13#5, regidx.Regidx 13#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31473703 :
    (Functions.ext_decode 826750723#32).run σ = .ok (instruction.LOAD (788#12, regidx.Regidx 14#5, regidx.Regidx 14#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3147a603 :
    (Functions.ext_decode 826779139#32).run σ = .ok (instruction.LOAD (788#12, regidx.Regidx 15#5, regidx.Regidx 12#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31492783 :
    (Functions.ext_decode 826877827#32).run σ = .ok (instruction.LOAD (788#12, regidx.Regidx 18#5, regidx.Regidx 15#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_314a0a13 :
    (Functions.ext_decode 826935827#32).run σ = .ok (instruction.ITYPE (788#12, regidx.Regidx 20#5, regidx.Regidx 20#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_315010ef :
    (Functions.ext_decode 827330799#32).run σ = .ok (instruction.JAL (6932#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_315020ef :
    (Functions.ext_decode 827334895#32).run σ = .ok (instruction.JAL (11028#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3151d0ef :
    (Functions.ext_decode 827445487#32).run σ = .ok (instruction.JAL (121620#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3152c0ef :
    (Functions.ext_decode 827506927#32).run σ = .ok (instruction.JAL (183060#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_315390ef :
    (Functions.ext_decode 827560175#32).run σ = .ok (instruction.JAL (236308#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31813d83 :
    (Functions.ext_decode 830553475#32).run σ = .ok (instruction.LOAD (792#12, regidx.Regidx 2#5, regidx.Regidx 27#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3185b583 :
    (Functions.ext_decode 830846339#32).run σ = .ok (instruction.LOAD (792#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31868693 :
    (Functions.ext_decode 830899859#32).run σ = .ok (instruction.ITYPE (792#12, regidx.Regidx 13#5, regidx.Regidx 13#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3187a783 :
    (Functions.ext_decode 830973827#32).run σ = .ok (instruction.LOAD (792#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_319010ef :
    (Functions.ext_decode 831525103#32).run σ = .ok (instruction.JAL (6936#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3193a0ef :
    (Functions.ext_decode 831758575#32).run σ = .ok (instruction.JAL (240408#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31a05663 :
    (Functions.ext_decode 832591459#32).run σ = .ok (instruction.BTYPE (780#13, regidx.Regidx 26#5, regidx.Regidx 0#5, bop.BGE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31b13c23 :
    (Functions.ext_decode 833698851#32).run σ = .ok (instruction.STORE (792#12, regidx.Regidx 27#5, regidx.Regidx 2#5, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31c030ef :
    (Functions.ext_decode 834679023#32).run σ = .ok (instruction.JAL (13084#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31c040ef :
    (Functions.ext_decode 834683119#32).run σ = .ok (instruction.JAL (17180#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31c050ef :
    (Functions.ext_decode 834687215#32).run σ = .ok (instruction.JAL (21276#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31c50513 :
    (Functions.ext_decode 834995475#32).run σ = .ok (instruction.ITYPE (796#12, regidx.Regidx 10#5, regidx.Regidx 10#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31c5b583 :
    (Functions.ext_decode 835040643#32).run σ = .ok (instruction.LOAD (796#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31c7a783 :
    (Functions.ext_decode 835168131#32).run σ = .ok (instruction.LOAD (796#12, regidx.Regidx 15#5, regidx.Regidx 15#5, false, 4)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31d1b0ef :
    (Functions.ext_decode 835825903#32).run σ = .ok (instruction.JAL (113436#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_31d78863 :
    (Functions.ext_decode 836208739#32).run σ = .ok (instruction.BTYPE (784#13, regidx.Regidx 29#5, regidx.Regidx 15#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3200106f :
    (Functions.ext_decode 838865007#32).run σ = .ok (instruction.JAL (4896#21, regidx.Regidx 0#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32013d03 :
    (Functions.ext_decode 838941955#32).run σ = .ok (instruction.LOAD (800#12, regidx.Regidx 2#5, regidx.Regidx 26#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32030263 :
    (Functions.ext_decode 839058019#32).run σ = .ok (instruction.BTYPE (804#13, regidx.Regidx 0#5, regidx.Regidx 6#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_320400ef :
    (Functions.ext_decode 839123183#32).run σ = .ok (instruction.JAL (262944#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32051063 :
    (Functions.ext_decode 839192675#32).run σ = .ok (instruction.BTYPE (800#13, regidx.Regidx 0#5, regidx.Regidx 10#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32051ae3 :
    (Functions.ext_decode 839195363#32).run σ = .ok (instruction.BTYPE (2868#13, regidx.Regidx 0#5, regidx.Regidx 10#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3205b583 :
    (Functions.ext_decode 839234947#32).run σ = .ok (instruction.LOAD (800#12, regidx.Regidx 11#5, regidx.Regidx 11#5, false, 8)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32060663 :
    (Functions.ext_decode 839255651#32).run σ = .ok (instruction.BTYPE (812#13, regidx.Regidx 0#5, regidx.Regidx 12#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32060c63 :
    (Functions.ext_decode 839257187#32).run σ = .ok (instruction.BTYPE (824#13, regidx.Regidx 0#5, regidx.Regidx 12#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32068ae3 :
    (Functions.ext_decode 839289571#32).run σ = .ok (instruction.BTYPE (2868#13, regidx.Regidx 0#5, regidx.Regidx 13#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_3206ce63 :
    (Functions.ext_decode 839306851#32).run σ = .ok (instruction.BTYPE (828#13, regidx.Regidx 0#5, regidx.Regidx 13#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32070ee3 :
    (Functions.ext_decode 839323363#32).run σ = .ok (instruction.BTYPE (2876#13, regidx.Regidx 0#5, regidx.Regidx 14#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32078263 :
    (Functions.ext_decode 839352931#32).run σ = .ok (instruction.BTYPE (804#13, regidx.Regidx 0#5, regidx.Regidx 15#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32078e63 :
    (Functions.ext_decode 839356003#32).run σ = .ok (instruction.BTYPE (828#13, regidx.Regidx 0#5, regidx.Regidx 15#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_320792e3 :
    (Functions.ext_decode 839357155#32).run σ = .ok (instruction.BTYPE (2852#13, regidx.Regidx 0#5, regidx.Regidx 15#5, bop.BNE)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_32080813 :
    (Functions.ext_decode 839387155#32).run σ = .ok (instruction.ITYPE (800#12, regidx.Regidx 16#5, regidx.Regidx 16#5, iop.ADDI)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_320b4e63 :
    (Functions.ext_decode 839601763#32).run σ = .ok (instruction.BTYPE (828#13, regidx.Regidx 0#5, regidx.Regidx 22#5, bop.BLT)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_320c0863 :
    (Functions.ext_decode 839649379#32).run σ = .ok (instruction.BTYPE (816#13, regidx.Regidx 0#5, regidx.Regidx 24#5, bop.BEQ)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_321000ef :
    (Functions.ext_decode 839909615#32).run σ = .ok (instruction.JAL (2848#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_321030ef :
    (Functions.ext_decode 839921903#32).run σ = .ok (instruction.JAL (15136#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_321060ef :
    (Functions.ext_decode 839934191#32).run σ = .ok (instruction.JAL (27424#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_321080ef :
    (Functions.ext_decode 839942383#32).run σ = .ok (instruction.JAL (35616#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_321120ef :
    (Functions.ext_decode 839983343#32).run σ = .ok (instruction.JAL (76576#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_324000ef :
    (Functions.ext_decode 843055343#32).run σ = .ok (instruction.JAL (804#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_324080ef :
    (Functions.ext_decode 843088111#32).run σ = .ok (instruction.JAL (33572#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

theorem decode_324170ef :
    (Functions.ext_decode 843149551#32).run σ = .ok (instruction.JAL (95012#21, regidx.Regidx 1#5)) σ :=
  decodeW σ hmisa hpriv hsec

end Vsa.Sim.ElfDecode
