import OCaml.Vm.Boot.WhileMinLogParts.Runs971_1005
import OCaml.Vm.Boot.WhileMinLogData
import Vsa.Sim.Boot.Checks

/-! GENERATED by scripts/gen_boot_log.py. Kernel checks of observed stores only. -/
namespace OCaml.Vm.Boot.WhileMinLog
open Vsa.Sim.Boot

theorem run1005_checked : RunTree.Checked log (.leaf run1005) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1006_checked : RunTree.Checked log (.leaf run1006) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1005_1007_checked : RunTree.Checked log tree_1005_1007 :=
  RunTree.Checked.node run1005_checked run1006_checked
theorem run1007_checked : RunTree.Checked log (.leaf run1007) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1008_checked : RunTree.Checked log (.leaf run1008) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1007_1009_checked : RunTree.Checked log tree_1007_1009 :=
  RunTree.Checked.node run1007_checked run1008_checked
theorem tree_1005_1009_checked : RunTree.Checked log tree_1005_1009 :=
  RunTree.Checked.node tree_1005_1007_checked tree_1007_1009_checked
theorem run1009_checked : RunTree.Checked log (.leaf run1009) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1010_checked : RunTree.Checked log (.leaf run1010) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1009_1011_checked : RunTree.Checked log tree_1009_1011 :=
  RunTree.Checked.node run1009_checked run1010_checked
theorem run1011_checked : RunTree.Checked log (.leaf run1011) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1012_checked : RunTree.Checked log (.leaf run1012) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1011_1013_checked : RunTree.Checked log tree_1011_1013 :=
  RunTree.Checked.node run1011_checked run1012_checked
theorem tree_1009_1013_checked : RunTree.Checked log tree_1009_1013 :=
  RunTree.Checked.node tree_1009_1011_checked tree_1011_1013_checked
theorem tree_1005_1013_checked : RunTree.Checked log tree_1005_1013 :=
  RunTree.Checked.node tree_1005_1009_checked tree_1009_1013_checked
theorem run1013_checked : RunTree.Checked log (.leaf run1013) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1014_checked : RunTree.Checked log (.leaf run1014) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1013_1015_checked : RunTree.Checked log tree_1013_1015 :=
  RunTree.Checked.node run1013_checked run1014_checked
theorem run1015_checked : RunTree.Checked log (.leaf run1015) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1016_checked : RunTree.Checked log (.leaf run1016) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1015_1017_checked : RunTree.Checked log tree_1015_1017 :=
  RunTree.Checked.node run1015_checked run1016_checked
theorem tree_1013_1017_checked : RunTree.Checked log tree_1013_1017 :=
  RunTree.Checked.node tree_1013_1015_checked tree_1015_1017_checked
theorem run1017_checked : RunTree.Checked log (.leaf run1017) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1018_checked : RunTree.Checked log (.leaf run1018) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1017_1019_checked : RunTree.Checked log tree_1017_1019 :=
  RunTree.Checked.node run1017_checked run1018_checked
theorem run1019_checked : RunTree.Checked log (.leaf run1019) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1020_checked : RunTree.Checked log (.leaf run1020) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1021_checked : RunTree.Checked log (.leaf run1021) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1020_1022_checked : RunTree.Checked log tree_1020_1022 :=
  RunTree.Checked.node run1020_checked run1021_checked
theorem tree_1019_1022_checked : RunTree.Checked log tree_1019_1022 :=
  RunTree.Checked.node run1019_checked tree_1020_1022_checked
theorem tree_1017_1022_checked : RunTree.Checked log tree_1017_1022 :=
  RunTree.Checked.node tree_1017_1019_checked tree_1019_1022_checked
theorem tree_1013_1022_checked : RunTree.Checked log tree_1013_1022 :=
  RunTree.Checked.node tree_1013_1017_checked tree_1017_1022_checked
theorem tree_1005_1022_checked : RunTree.Checked log tree_1005_1022 :=
  RunTree.Checked.node tree_1005_1013_checked tree_1013_1022_checked
theorem run1022_checked : RunTree.Checked log (.leaf run1022) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1023_checked : RunTree.Checked log (.leaf run1023) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1022_1024_checked : RunTree.Checked log tree_1022_1024 :=
  RunTree.Checked.node run1022_checked run1023_checked
theorem run1024_checked : RunTree.Checked log (.leaf run1024) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1025_checked : RunTree.Checked log (.leaf run1025) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1024_1026_checked : RunTree.Checked log tree_1024_1026 :=
  RunTree.Checked.node run1024_checked run1025_checked
theorem tree_1022_1026_checked : RunTree.Checked log tree_1022_1026 :=
  RunTree.Checked.node tree_1022_1024_checked tree_1024_1026_checked
theorem run1026_checked : RunTree.Checked log (.leaf run1026) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1027_checked : RunTree.Checked log (.leaf run1027) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1026_1028_checked : RunTree.Checked log tree_1026_1028 :=
  RunTree.Checked.node run1026_checked run1027_checked
theorem run1028_checked : RunTree.Checked log (.leaf run1028) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1029_checked : RunTree.Checked log (.leaf run1029) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1028_1030_checked : RunTree.Checked log tree_1028_1030 :=
  RunTree.Checked.node run1028_checked run1029_checked
theorem tree_1026_1030_checked : RunTree.Checked log tree_1026_1030 :=
  RunTree.Checked.node tree_1026_1028_checked tree_1028_1030_checked
theorem tree_1022_1030_checked : RunTree.Checked log tree_1022_1030 :=
  RunTree.Checked.node tree_1022_1026_checked tree_1026_1030_checked
theorem run1030_checked : RunTree.Checked log (.leaf run1030) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1031_checked : RunTree.Checked log (.leaf run1031) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1030_1032_checked : RunTree.Checked log tree_1030_1032 :=
  RunTree.Checked.node run1030_checked run1031_checked
theorem run1032_checked : RunTree.Checked log (.leaf run1032) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1033_checked : RunTree.Checked log (.leaf run1033) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1032_1034_checked : RunTree.Checked log tree_1032_1034 :=
  RunTree.Checked.node run1032_checked run1033_checked
theorem tree_1030_1034_checked : RunTree.Checked log tree_1030_1034 :=
  RunTree.Checked.node tree_1030_1032_checked tree_1032_1034_checked
theorem run1034_checked : RunTree.Checked log (.leaf run1034) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1035_checked : RunTree.Checked log (.leaf run1035) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1034_1036_checked : RunTree.Checked log tree_1034_1036 :=
  RunTree.Checked.node run1034_checked run1035_checked
theorem run1036_checked : RunTree.Checked log (.leaf run1036) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1037_checked : RunTree.Checked log (.leaf run1037) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem run1038_checked : RunTree.Checked log (.leaf run1038) :=
  RunTree.Checked.leaf (by decide +kernel)
theorem tree_1037_1039_checked : RunTree.Checked log tree_1037_1039 :=
  RunTree.Checked.node run1037_checked run1038_checked
theorem tree_1036_1039_checked : RunTree.Checked log tree_1036_1039 :=
  RunTree.Checked.node run1036_checked tree_1037_1039_checked
theorem tree_1034_1039_checked : RunTree.Checked log tree_1034_1039 :=
  RunTree.Checked.node tree_1034_1036_checked tree_1036_1039_checked
theorem tree_1030_1039_checked : RunTree.Checked log tree_1030_1039 :=
  RunTree.Checked.node tree_1030_1034_checked tree_1034_1039_checked
theorem tree_1022_1039_checked : RunTree.Checked log tree_1022_1039 :=
  RunTree.Checked.node tree_1022_1030_checked tree_1030_1039_checked
theorem tree_1005_1039_checked : RunTree.Checked log tree_1005_1039 :=
  RunTree.Checked.node tree_1005_1022_checked tree_1022_1039_checked
end OCaml.Vm.Boot.WhileMinLog
