import Vsa.Sim.ValueSites
import Vsa.Sim.Code.CamlAlu
import Vsa.Sim.ElfDecode.Part019
import Vsa.Sim.ElfDecode.Part020
import Vsa.Sim.ElfDecode.Part023
import Vsa.Sim.ElfDecode.Part036
import Vsa.Sim.ElfDecode.Part049
import Vsa.Sim.ElfDecode.Part050
import Vsa.Sim.ElfDecode.Part055
import Vsa.Sim.ElfDecode.Part064
import Vsa.Sim.ElfDecode.Part137
import Vsa.Sim.ElfDecode.Part141
import Vsa.Sim.ElfDecode.Part229

/-!
GENERATED by scripts/gen_alu_pilot.py via scripts/gen_arm_pilot.py via scripts/syi/gen_sites.py from
alu.tsv against `Vsa.Sim.Code.CamlAluLoaded`.
Do not hand-edit; regenerate instead.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)



-- discipline: allow(R5-stepobs-volume) a per-site battery is one `stepObs_` per
-- site BY CONSTRUCTION; this file is machine-emitted from a TSV, not a
-- hand-threaded chain.
-- discipline: allow(R7-conj-tower-def) the existentials are the `∃ σ' i'` of each
-- site's `StepObs` conclusion (the landed shape), not new ∃/∧-tower posts.

namespace Vsa.Sim

/-- 0x80001efc: `srai`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80001efc_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v13 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx13 : σ.regs.get? Register.x13 = some v13)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80001efc#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x13 (shift_bits_right_arith v13 (Sail.BitVec.extractLsb (0x01#6) 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80001efc hmem
  exact stepObs_alu σ i u (0x80001efc#64) vminstret (0x4016d693#32)
    (instruction.SHIFTIOP ((0x001#6), (regidx.Regidx 0x0d#5), (regidx.Regidx 0x0d#5), sop.SRAI))
    Register.x13 (shift_bits_right_arith v13 (Sail.BitVec.extractLsb (0x01#6) 5 0))
    (0x93#8) (0xd6#8) (0x16#8) (0x40#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_4016d693 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_shiftiop_srai_char (0x001#6) (regidx.Regidx 0x0d#5) (regidx.Regidx 0x0d#5) v13
      (afterNextPC (afterPrelude σ) (0x80001efc#64))
      (sigma3_alu σ (0x80001efc#64) Register.x13 (shift_bits_right_arith v13 (Sail.BitVec.extractLsb (0x01#6) 5 0)))
      (rX_bits_x13 _ v13
        (by rw [get?_afterNextPC σ (0x80001efc#64) _ (by decide) (by decide)]; exact hx13))
      (wX_bits_x13 _ (shift_bits_right_arith v13 (Sail.BitVec.extractLsb (0x01#6) 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80001f00: `slli`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80001f00_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v13 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx13 : σ.regs.get? Register.x13 = some v13)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80001f00#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x13 (shift_bits_left v13 (Sail.BitVec.extractLsb (0x03#6) 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80001f00 hmem
  exact stepObs_alu σ i u (0x80001f00#64) vminstret (0x00369693#32)
    (instruction.SHIFTIOP ((0x003#6), (regidx.Regidx 0x0d#5), (regidx.Regidx 0x0d#5), sop.SLLI))
    Register.x13 (shift_bits_left v13 (Sail.BitVec.extractLsb (0x03#6) 5 0))
    (0x93#8) (0x96#8) (0x36#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00369693 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_shiftiop_slli_char (0x003#6) (regidx.Regidx 0x0d#5) (regidx.Regidx 0x0d#5) v13
      (afterNextPC (afterPrelude σ) (0x80001f00#64))
      (sigma3_alu σ (0x80001f00#64) Register.x13 (shift_bits_left v13 (Sail.BitVec.extractLsb (0x03#6) 5 0)))
      (rX_bits_x13 _ v13
        (by rw [get?_afterNextPC σ (0x80001f00#64) _ (by decide) (by decide)]; exact hx13))
      (wX_bits_x13 _ (shift_bits_left v13 (Sail.BitVec.extractLsb (0x03#6) 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002294: `srli`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002294_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80002294#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x21 (shift_bits_right v21 (Sail.BitVec.extractLsb (0x0a#6) 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80002294 hmem
  exact stepObs_alu σ i u (0x80002294#64) vminstret (0x00aada93#32)
    (instruction.SHIFTIOP ((0x00a#6), (regidx.Regidx 0x15#5), (regidx.Regidx 0x15#5), sop.SRLI))
    Register.x21 (shift_bits_right v21 (Sail.BitVec.extractLsb (0x0a#6) 5 0))
    (0x93#8) (0xda#8) (0xaa#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00aada93 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_shiftiop_srli_char (0x00a#6) (regidx.Regidx 0x15#5) (regidx.Regidx 0x15#5) v21
      (afterNextPC (afterPrelude σ) (0x80002294#64))
      (sigma3_alu σ (0x80002294#64) Register.x21 (shift_bits_right v21 (Sail.BitVec.extractLsb (0x0a#6) 5 0)))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x80002294#64) _ (by decide) (by decide)]; exact hx21))
      (wX_bits_x21 _ (shift_bits_right v21 (Sail.BitVec.extractLsb (0x0a#6) 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002870: `slliw`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002870_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v17 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx17 : σ.regs.get? Register.x17 = some v17)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80002870#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x23 (sign_extend (m := 64) (shift_bits_left (Sail.BitVec.extractLsb v17 31 0) (0x01#5)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80002870 hmem
  exact stepObs_alu σ i u (0x80002870#64) vminstret (0x00189b9b#32)
    (instruction.SHIFTIWOP ((0x001#5), (regidx.Regidx 0x11#5), (regidx.Regidx 0x17#5), sopw.SLLIW))
    Register.x23 (sign_extend (m := 64) (shift_bits_left (Sail.BitVec.extractLsb v17 31 0) (0x01#5)))
    (0x9b#8) (0x9b#8) (0x18#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00189b9b (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_shiftiwop_slliw_char (0x001#5) (regidx.Regidx 0x11#5) (regidx.Regidx 0x17#5) v17
      (afterNextPC (afterPrelude σ) (0x80002870#64))
      (sigma3_alu σ (0x80002870#64) Register.x23 (sign_extend (m := 64) (shift_bits_left (Sail.BitVec.extractLsb v17 31 0) (0x01#5))))
      (rX_bits_x17 _ v17
        (by rw [get?_afterNextPC σ (0x80002870#64) _ (by decide) (by decide)]; exact hx17))
      (wX_bits_x23 _ (sign_extend (m := 64) (shift_bits_left (Sail.BitVec.extractLsb v17 31 0) (0x01#5)))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002874: `addw`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002874_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v23 v17 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx23 : σ.regs.get? Register.x23 = some v23)
    (hx17 : σ.regs.get? Register.x17 = some v17)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80002874#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x23 (sign_extend (m := 64) ((Sail.BitVec.extractLsb v23 31 0) + (Sail.BitVec.extractLsb v17 31 0)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80002874 hmem
  exact stepObs_alu σ i u (0x80002874#64) vminstret (0x011b8bbb#32)
    (instruction.RTYPEW ((regidx.Regidx 0x11#5), (regidx.Regidx 0x17#5), (regidx.Regidx 0x17#5), ropw.ADDW))
    Register.x23 (sign_extend (m := 64) ((Sail.BitVec.extractLsb v23 31 0) + (Sail.BitVec.extractLsb v17 31 0)))
    (0xbb#8) (0x8b#8) (0x1b#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_011b8bbb (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtypew_addw_char (regidx.Regidx 0x11#5) (regidx.Regidx 0x17#5) (regidx.Regidx 0x17#5) v23 v17
      (afterNextPC (afterPrelude σ) (0x80002874#64))
      (sigma3_alu σ (0x80002874#64) Register.x23 (sign_extend (m := 64) ((Sail.BitVec.extractLsb v23 31 0) + (Sail.BitVec.extractLsb v17 31 0))))
      (rX_bits_x23 _ v23
        (by rw [get?_afterNextPC σ (0x80002874#64) _ (by decide) (by decide)]; exact hx23))
      (rX_bits_x17 _ v17
        (by rw [get?_afterNextPC σ (0x80002874#64) _ (by decide) (by decide)]; exact hx17))
      (wX_bits_x23 _ (sign_extend (m := 64) ((Sail.BitVec.extractLsb v23 31 0) + (Sail.BitVec.extractLsb v17 31 0)))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002cdc: `alu_and`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002cdc_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80002cdc#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x21 (v21 &&& v15)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80002cdc hmem
  exact stepObs_alu σ i u (0x80002cdc#64) vminstret (0x00fafab3#32)
    (instruction.RTYPE ((regidx.Regidx 0x0f#5), (regidx.Regidx 0x15#5), (regidx.Regidx 0x15#5), rop.AND))
    Register.x21 (v21 &&& v15)
    (0xb3#8) (0xfa#8) (0xfa#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00fafab3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_and_char (regidx.Regidx 0x0f#5) (regidx.Regidx 0x15#5) (regidx.Regidx 0x15#5) v21 v15
      (afterNextPC (afterPrelude σ) (0x80002cdc#64))
      (sigma3_alu σ (0x80002cdc#64) Register.x21 (v21 &&& v15))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x80002cdc#64) _ (by decide) (by decide)]; exact hx21))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80002cdc#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x21 _ (v21 &&& v15)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8000314c: `andi`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8000314c_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x8000314c#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15 (v21 &&& sign_extend (m := 64) (0x001#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_8000314c hmem
  exact stepObs_alu σ i u (0x8000314c#64) vminstret (0x001af793#32)
    (instruction.ITYPE ((0x001#12), (regidx.Regidx 0x15#5), (regidx.Regidx 0x0f#5), iop.ANDI))
    Register.x15 (v21 &&& sign_extend (m := 64) (0x001#12))
    (0x93#8) (0xf7#8) (0x1a#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_001af793 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_andi_char (0x001#12) (regidx.Regidx 0x15#5) (regidx.Regidx 0x0f#5) v21
      (afterNextPC (afterPrelude σ) (0x8000314c#64))
      (sigma3_alu σ (0x8000314c#64) Register.x15 (v21 &&& sign_extend (m := 64) (0x001#12)))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x8000314c#64) _ (by decide) (by decide)]; exact hx21))
      (wX_bits_x15 _ (v21 &&& sign_extend (m := 64) (0x001#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800032e8: `srl`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_800032e8_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x800032e8#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15 (shift_bits_right v21 (Sail.BitVec.extractLsb v15 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_800032e8 hmem
  exact stepObs_alu σ i u (0x800032e8#64) vminstret (0x00fad7b3#32)
    (instruction.RTYPE ((regidx.Regidx 0x0f#5), (regidx.Regidx 0x15#5), (regidx.Regidx 0x0f#5), rop.SRL))
    Register.x15 (shift_bits_right v21 (Sail.BitVec.extractLsb v15 5 0))
    (0xb3#8) (0xd7#8) (0xfa#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00fad7b3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_srl_char (regidx.Regidx 0x0f#5) (regidx.Regidx 0x15#5) (regidx.Regidx 0x0f#5) v21 v15
      (afterNextPC (afterPrelude σ) (0x800032e8#64))
      (sigma3_alu σ (0x800032e8#64) Register.x15 (shift_bits_right v21 (Sail.BitVec.extractLsb v15 5 0)))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x800032e8#64) _ (by decide) (by decide)]; exact hx21))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x800032e8#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x15 _ (shift_bits_right v21 (Sail.BitVec.extractLsb v15 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800032ec: `ori`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_800032ec_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x800032ec#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x21 (v15 ||| sign_extend (m := 64) (0x001#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_800032ec hmem
  exact stepObs_alu σ i u (0x800032ec#64) vminstret (0x0017ea93#32)
    (instruction.ITYPE ((0x001#12), (regidx.Regidx 0x0f#5), (regidx.Regidx 0x15#5), iop.ORI))
    Register.x21 (v15 ||| sign_extend (m := 64) (0x001#12))
    (0x93#8) (0xea#8) (0x17#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_0017ea93 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_ori_char (0x001#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x15#5) v15
      (afterNextPC (afterPrelude σ) (0x800032ec#64))
      (sigma3_alu σ (0x800032ec#64) Register.x21 (v15 ||| sign_extend (m := 64) (0x001#12)))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x800032ec#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x21 _ (v15 ||| sign_extend (m := 64) (0x001#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80003374: `sraiw`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003374_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80003374#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15 (sign_extend (m := 64) (shift_bits_right_arith (Sail.BitVec.extractLsb v15 31 0) (0x01#5)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80003374 hmem
  exact stepObs_alu σ i u (0x80003374#64) vminstret (0x4017d79b#32)
    (instruction.SHIFTIWOP ((0x001#5), (regidx.Regidx 0x0f#5), (regidx.Regidx 0x0f#5), sopw.SRAIW))
    Register.x15 (sign_extend (m := 64) (shift_bits_right_arith (Sail.BitVec.extractLsb v15 31 0) (0x01#5)))
    (0x9b#8) (0xd7#8) (0x17#8) (0x40#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_4017d79b (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_shiftiwop_sraiw_char (0x001#5) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0f#5) v15
      (afterNextPC (afterPrelude σ) (0x80003374#64))
      (sigma3_alu σ (0x80003374#64) Register.x15 (sign_extend (m := 64) (shift_bits_right_arith (Sail.BitVec.extractLsb v15 31 0) (0x01#5))))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80003374#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x15 _ (sign_extend (m := 64) (shift_bits_right_arith (Sail.BitVec.extractLsb v15 31 0) (0x01#5)))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8000344c: `alu_xor`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8000344c_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x8000344c#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15 (v21 ^^^ v15)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_8000344c hmem
  exact stepObs_alu σ i u (0x8000344c#64) vminstret (0x00fac7b3#32)
    (instruction.RTYPE ((regidx.Regidx 0x0f#5), (regidx.Regidx 0x15#5), (regidx.Regidx 0x0f#5), rop.XOR))
    Register.x15 (v21 ^^^ v15)
    (0xb3#8) (0xc7#8) (0xfa#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00fac7b3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_xor_char (regidx.Regidx 0x0f#5) (regidx.Regidx 0x15#5) (regidx.Regidx 0x0f#5) v21 v15
      (afterNextPC (afterPrelude σ) (0x8000344c#64))
      (sigma3_alu σ (0x8000344c#64) Register.x15 (v21 ^^^ v15))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x8000344c#64) _ (by decide) (by decide)]; exact hx21))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x8000344c#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x15 _ (v21 ^^^ v15)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80003540: `sll`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003540_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80003540#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x21 (shift_bits_left v21 (Sail.BitVec.extractLsb v15 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80003540 hmem
  exact stepObs_alu σ i u (0x80003540#64) vminstret (0x00fa9ab3#32)
    (instruction.RTYPE ((regidx.Regidx 0x0f#5), (regidx.Regidx 0x15#5), (regidx.Regidx 0x15#5), rop.SLL))
    Register.x21 (shift_bits_left v21 (Sail.BitVec.extractLsb v15 5 0))
    (0xb3#8) (0x9a#8) (0xfa#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00fa9ab3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_sll_char (regidx.Regidx 0x0f#5) (regidx.Regidx 0x15#5) (regidx.Regidx 0x15#5) v21 v15
      (afterNextPC (afterPrelude σ) (0x80003540#64))
      (sigma3_alu σ (0x80003540#64) Register.x21 (shift_bits_left v21 (Sail.BitVec.extractLsb v15 5 0)))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x80003540#64) _ (by decide) (by decide)]; exact hx21))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80003540#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x21 _ (shift_bits_left v21 (Sail.BitVec.extractLsb v15 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800035a0: `sra`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_800035a0_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x800035a0#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15 (shift_bits_right_arith v21 (Sail.BitVec.extractLsb v15 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_800035a0 hmem
  exact stepObs_alu σ i u (0x800035a0#64) vminstret (0x40fad7b3#32)
    (instruction.RTYPE ((regidx.Regidx 0x0f#5), (regidx.Regidx 0x15#5), (regidx.Regidx 0x0f#5), rop.SRA))
    Register.x15 (shift_bits_right_arith v21 (Sail.BitVec.extractLsb v15 5 0))
    (0xb3#8) (0xd7#8) (0xfa#8) (0x40#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_40fad7b3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_sra_char (regidx.Regidx 0x0f#5) (regidx.Regidx 0x15#5) (regidx.Regidx 0x0f#5) v21 v15
      (afterNextPC (afterPrelude σ) (0x800035a0#64))
      (sigma3_alu σ (0x800035a0#64) Register.x15 (shift_bits_right_arith v21 (Sail.BitVec.extractLsb v15 5 0)))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x800035a0#64) _ (by decide) (by decide)]; exact hx21))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x800035a0#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x15 _ (shift_bits_right_arith v21 (Sail.BitVec.extractLsb v15 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x800035b8: `alu_or`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_800035b8_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x800035b8#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x21 (v21 ||| v15)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_800035b8 hmem
  exact stepObs_alu σ i u (0x800035b8#64) vminstret (0x00faeab3#32)
    (instruction.RTYPE ((regidx.Regidx 0x0f#5), (regidx.Regidx 0x15#5), (regidx.Regidx 0x15#5), rop.OR))
    Register.x21 (v21 ||| v15)
    (0xb3#8) (0xea#8) (0xfa#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00faeab3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_or_char (regidx.Regidx 0x0f#5) (regidx.Regidx 0x15#5) (regidx.Regidx 0x15#5) v21 v15
      (afterNextPC (afterPrelude σ) (0x800035b8#64))
      (sigma3_alu σ (0x800035b8#64) Register.x21 (v21 ||| v15))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x800035b8#64) _ (by decide) (by decide)]; exact hx21))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x800035b8#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x21 _ (v21 ||| v15)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80006234: `xori`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80006234_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x80006234#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15 (v15 ^^^ sign_extend (m := 64) (0xfff#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_80006234 hmem
  exact stepObs_alu σ i u (0x80006234#64) vminstret (0xfff7c793#32)
    (instruction.ITYPE ((0xfff#12), (regidx.Regidx 0x0f#5), (regidx.Regidx 0x0f#5), iop.XORI))
    Register.x15 (v15 ^^^ sign_extend (m := 64) (0xfff#12))
    (0x93#8) (0xc7#8) (0xf7#8) (0xff#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_fff7c793 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_xori_char (0xfff#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0f#5) v15
      (afterNextPC (afterPrelude σ) (0x80006234#64))
      (sigma3_alu σ (0x80006234#64) Register.x15 (v15 ^^^ sign_extend (m := 64) (0xfff#12)))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80006234#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x15 _ (v15 ^^^ sign_extend (m := 64) (0xfff#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8000d8fc: `srliw`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8000d8fc_alu (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Vsa.Sim.Code.CamlAluLoaded σ.mem)
    (hpcv : pc = (0x8000d8fc#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15 (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb v10 31 0) (0x1f#5)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlAlu_at_8000d8fc hmem
  exact stepObs_alu σ i u (0x8000d8fc#64) vminstret (0x01f5579b#32)
    (instruction.SHIFTIWOP ((0x01f#5), (regidx.Regidx 0x0a#5), (regidx.Regidx 0x0f#5), sopw.SRLIW))
    Register.x15 (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb v10 31 0) (0x1f#5)))
    (0x9b#8) (0x57#8) (0xf5#8) (0x01#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_01f5579b (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_shiftiwop_srliw_char (0x01f#5) (regidx.Regidx 0x0a#5) (regidx.Regidx 0x0f#5) v10
      (afterNextPC (afterPrelude σ) (0x8000d8fc#64))
      (sigma3_alu σ (0x8000d8fc#64) Register.x15 (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb v10 31 0) (0x1f#5))))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x8000d8fc#64) _ (by decide) (by decide)]; exact hx10))
      (wX_bits_x15 _ (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb v10 31 0) (0x1f#5)))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

end Vsa.Sim
