import OCaml.Vm.Platform
import Vsa.Sim.Code.CamlApply1

/-! GENERATED by scripts/gen_arm_pilot.py. Full-image projection. -/
namespace OCaml.Vm.Sim
open Vsa.Machine

theorem apply1_loaded {c : Config} (h : ExecutableImage c) :
    Vsa.Sim.Code.CamlApply1Loaded c.σ.mem := by
  unfold Vsa.Sim.Code.CamlApply1Loaded Vsa.Sim.Code.camlApply1Chunk0 Vsa.Sim.Code.camlApply1Chunk1
  refine ⟨⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩, ⟨?_, ?_, ?_, ?_⟩⟩
  · have hb := h.text 11248 (by decide)
    have he : Image.textByte 11248 = (0x83#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11249 (by decide)
    have he : Image.textByte 11249 = (0xb7#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11250 (by decide)
    have he : Image.textByte 11250 = (0x04#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11251 (by decide)
    have he : Image.textByte 11251 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11252 (by decide)
    have he : Image.textByte 11252 = (0x13#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11253 (by decide)
    have he : Image.textByte 11253 = (0x19#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11254 (by decide)
    have he : Image.textByte 11254 = (0x19#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11255 (by decide)
    have he : Image.textByte 11255 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11256 (by decide)
    have he : Image.textByte 11256 = (0x13#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11257 (by decide)
    have he : Image.textByte 11257 = (0x09#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11258 (by decide)
    have he : Image.textByte 11258 = (0x19#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11259 (by decide)
    have he : Image.textByte 11259 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11260 (by decide)
    have he : Image.textByte 11260 = (0x23#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11261 (by decide)
    have he : Image.textByte 11261 = (0xb0#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11262 (by decide)
    have he : Image.textByte 11262 = (0x24#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11263 (by decide)
    have he : Image.textByte 11263 = (0x01#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11264 (by decide)
    have he : Image.textByte 11264 = (0x23#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11265 (by decide)
    have he : Image.textByte 11265 = (0xb8#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11266 (by decide)
    have he : Image.textByte 11266 = (0x74#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11267 (by decide)
    have he : Image.textByte 11267 = (0xff#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11268 (by decide)
    have he : Image.textByte 11268 = (0x23#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11269 (by decide)
    have he : Image.textByte 11269 = (0xbc#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11270 (by decide)
    have he : Image.textByte 11270 = (0x94#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11271 (by decide)
    have he : Image.textByte 11271 = (0xff#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11272 (by decide)
    have he : Image.textByte 11272 = (0x23#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11273 (by decide)
    have he : Image.textByte 11273 = (0xb4#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11274 (by decide)
    have he : Image.textByte 11274 = (0xf4#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11275 (by decide)
    have he : Image.textByte 11275 = (0xfe#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11276 (by decide)
    have he : Image.textByte 11276 = (0x03#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11277 (by decide)
    have he : Image.textByte 11277 = (0xb4#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11278 (by decide)
    have he : Image.textByte 11278 = (0x0a#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11279 (by decide)
    have he : Image.textByte 11279 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11280 (by decide)
    have he : Image.textByte 11280 = (0x93#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11281 (by decide)
    have he : Image.textByte 11281 = (0x84#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11282 (by decide)
    have he : Image.textByte 11282 = (0x84#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11283 (by decide)
    have he : Image.textByte 11283 = (0xfe#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11284 (by decide)
    have he : Image.textByte 11284 = (0x13#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11285 (by decide)
    have he : Image.textByte 11285 = (0x09#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11286 (by decide)
    have he : Image.textByte 11286 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11287 (by decide)
    have he : Image.textByte 11287 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11288 (by decide)
    have he : Image.textByte 11288 = (0x6f#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11289 (by decide)
    have he : Image.textByte 11289 = (0xf0#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11290 (by decide)
    have he : Image.textByte 11290 = (0x5f#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 11291 (by decide)
    have he : Image.textByte 11291 = (0xb6#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10108 (by decide)
    have he : Image.textByte 10108 = (0x83#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10109 (by decide)
    have he : Image.textByte 10109 = (0xb7#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10110 (by decide)
    have he : Image.textByte 10110 = (0x09#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10111 (by decide)
    have he : Image.textByte 10111 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10112 (by decide)
    have he : Image.textByte 10112 = (0x93#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10113 (by decide)
    have he : Image.textByte 10113 = (0x8c#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10114 (by decide)
    have he : Image.textByte 10114 = (0x0a#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10115 (by decide)
    have he : Image.textByte 10115 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10116 (by decide)
    have he : Image.textByte 10116 = (0x03#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10117 (by decide)
    have he : Image.textByte 10117 = (0xb7#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10118 (by decide)
    have he : Image.textByte 10118 = (0x87#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10119 (by decide)
    have he : Image.textByte 10119 = (0x09#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10120 (by decide)
    have he : Image.textByte 10120 = (0x63#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10121 (by decide)
    have he : Image.textByte 10121 = (0xe2#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10122 (by decide)
    have he : Image.textByte 10122 = (0xe4#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10123 (by decide)
    have he : Image.textByte 10123 = (0x0c#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10124 (by decide)
    have he : Image.textByte 10124 = (0x83#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10125 (by decide)
    have he : Image.textByte 10125 = (0x27#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10126 (by decide)
    have he : Image.textByte 10126 = (0x0a#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10127 (by decide)
    have he : Image.textByte 10127 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10128 (by decide)
    have he : Image.textByte 10128 = (0x63#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10129 (by decide)
    have he : Image.textByte 10129 = (0x86#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10130 (by decide)
    have he : Image.textByte 10130 = (0x07#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 10131 (by decide)
    have he : Image.textByte 10131 = (0xfc#8) := by decide +kernel
    rw [he] at hb
    exact hb

end OCaml.Vm.Sim
