import Vsa.Sim.ValueSites
import Vsa.Sim.RamReadPins
import Vsa.Sim.ExecLoadTotal
import Vsa.Sim.Code.CamlApptermSuffix
import Vsa.Sim.ElfDecode.Part007
import Vsa.Sim.ElfDecode.Part013
import Vsa.Sim.ElfDecode.Part014
import Vsa.Sim.ElfDecode.Part036
import Vsa.Sim.ElfDecode.Part095
import Vsa.Sim.ElfDecode.Part101
import Vsa.Sim.ElfDecode.Part191
import Vsa.Sim.ElfDecode.Part217

/-!
GENERATED by scripts/gen_arm_pilot.py via scripts/syi/gen_sites.py from
appterm_suffix.tsv against `Vsa.Sim.Code.CamlApptermSuffixLoaded`.
Do not hand-edit; regenerate instead.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)



-- discipline: allow(R5-stepobs-volume) a per-site battery is one `stepObs_` per
-- site BY CONSTRUCTION; this file is machine-emitted from a TSV, not a
-- hand-threaded chain.
-- discipline: allow(R7-conj-tower-def) the existentials are the `∃ σ' i'` of each
-- site's `StepObs` conclusion (the landed shape), not new ∃/∧-tower posts.

namespace Vsa.Sim

/-- 0x80002ad0: `ld x8,0x0(x21)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002ad0_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x80002ad0#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v21 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhiram : (v21 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v21 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v21 + sign_extend (m := 64) (0x000#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x8
        (sign_extend (m := 64)
          (bytesT8 σ.mem (v21 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_80002ad0 hmem
  exact stepObs_alu σ i u (0x80002ad0#64) vminstret (0x000ab403#32)
    (instruction.LOAD (0x000#12, regidx.Regidx 0x15#5, regidx.Regidx 0x08#5, false, 8))
    Register.x8 (sign_extend (m := 64) (bytesT8 σ.mem (v21 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))
    (0x03#8) (0xb4#8) (0x0a#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_000ab403 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld_ram σ (0x80002ad0#64) (0x000#12) (regidx.Regidx 0x15#5) (regidx.Regidx 0x08#5)
      (sigma3_alu σ (0x80002ad0#64) Register.x8 (sign_extend (m := 64) (bytesT8 σ.mem (v21 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
      v21 hG
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x80002ad0#64) _ (by decide) (by decide)]; exact hx21))
      (wX_bits_x8 _ (sign_extend (m := 64) (bytesT8 σ.mem (v21 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002ad4: `add x18,x18,x10`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002ad4_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v18 v10 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx18 : σ.regs.get? Register.x18 = some v18)
    (hx10 : σ.regs.get? Register.x10 = some v10)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x80002ad4#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x18 (v18 + v10)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_80002ad4 hmem
  exact stepObs_alu σ i u (0x80002ad4#64) vminstret (0x00a90933#32)
    (instruction.RTYPE (regidx.Regidx 0x0a#5, regidx.Regidx 0x12#5, regidx.Regidx 0x12#5, rop.ADD))
    Register.x18 (v18 + v10)
    (0x33#8) (0x09#8) (0xa9#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00a90933 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_add_char (regidx.Regidx 0x0a#5) (regidx.Regidx 0x12#5) (regidx.Regidx 0x12#5)
      v18 v10 (afterNextPC (afterPrelude σ) (0x80002ad4#64))
      (sigma3_alu σ (0x80002ad4#64) Register.x18 (v18 + v10))
      (rX_bits_x18 _ v18
        (by rw [get?_afterNextPC σ (0x80002ad4#64) _ (by decide) (by decide)]; exact hx18))
      (rX_bits_x10 _ v10
        (by rw [get?_afterNextPC σ (0x80002ad4#64) _ (by decide) (by decide)]; exact hx10))
      (wX_bits_x18 _ (v18 + v10)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002ad8: `addi x9,x11,0x0`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002ad8_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v11 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx11 : σ.regs.get? Register.x11 = some v11)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x80002ad8#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x9
        (v11 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_80002ad8 hmem
  exact stepObs_alu σ i u (0x80002ad8#64) vminstret (0x00058493#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x0b#5, regidx.Regidx 0x09#5, iop.ADDI))
    Register.x9 (v11 + sign_extend (m := 64) (0x000#12))
    (0x93#8) (0x84#8) (0x05#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00058493 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x0b#5) (regidx.Regidx 0x09#5) v11
      (afterNextPC (afterPrelude σ) (0x80002ad8#64))
      (sigma3_alu σ (0x80002ad8#64) Register.x9 (v11 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x11 _ v11
        (by rw [get?_afterNextPC σ (0x80002ad8#64) _ (by decide) (by decide)]; exact hx11))
      (wX_bits_x9 _ (v11 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002adc: `j 0x8000277c`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002adc_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x80002adc#64 : BitVec 64))
    (htgt : (pc + sign_extend (m := 64) (0x1ffca0#21)).toNat % 4 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jump_x0 σ pc vminstret (pc + sign_extend (m := 64) (0x1ffca0#21))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_80002adc hmem
  exact stepObs_j σ i u (0x80002adc#64) vminstret (0xca1ff06f#32) (0x1ffca0#21)
    (0x6f#8) (0xf0#8) (0x1f#8) (0xca#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_ca1ff06f (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    htgt hi

/-- 0x8000277c: `ld x15,0x0(x19)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8000277c_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v19 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx19 : σ.regs.get? Register.x19 = some v19)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x8000277c#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v19 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhiram : (v19 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v19 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v19 + sign_extend (m := 64) (0x000#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        (sign_extend (m := 64)
          (bytesT8 σ.mem (v19 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_8000277c hmem
  exact stepObs_alu σ i u (0x8000277c#64) vminstret (0x0009b783#32)
    (instruction.LOAD (0x000#12, regidx.Regidx 0x13#5, regidx.Regidx 0x0f#5, false, 8))
    Register.x15 (sign_extend (m := 64) (bytesT8 σ.mem (v19 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))
    (0x83#8) (0xb7#8) (0x09#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_0009b783 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld_ram σ (0x8000277c#64) (0x000#12) (regidx.Regidx 0x13#5) (regidx.Regidx 0x0f#5)
      (sigma3_alu σ (0x8000277c#64) Register.x15 (sign_extend (m := 64) (bytesT8 σ.mem (v19 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
      v19 hG
      (rX_bits_x19 _ v19
        (by rw [get?_afterNextPC σ (0x8000277c#64) _ (by decide) (by decide)]; exact hx19))
      (wX_bits_x15 _ (sign_extend (m := 64) (bytesT8 σ.mem (v19 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002780: `addi x25,x21,0x0`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002780_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v21 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx21 : σ.regs.get? Register.x21 = some v21)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x80002780#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x25
        (v21 + sign_extend (m := 64) (0x000#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_80002780 hmem
  exact stepObs_alu σ i u (0x80002780#64) vminstret (0x000a8c93#32)
    (instruction.ITYPE (0x000#12, regidx.Regidx 0x15#5, regidx.Regidx 0x19#5, iop.ADDI))
    Register.x25 (v21 + sign_extend (m := 64) (0x000#12))
    (0x93#8) (0x8c#8) (0x0a#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_000a8c93 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x000#12) (regidx.Regidx 0x15#5) (regidx.Regidx 0x19#5) v21
      (afterNextPC (afterPrelude σ) (0x80002780#64))
      (sigma3_alu σ (0x80002780#64) Register.x25 (v21 + sign_extend (m := 64) (0x000#12)))
      (rX_bits_x21 _ v21
        (by rw [get?_afterNextPC σ (0x80002780#64) _ (by decide) (by decide)]; exact hx21))
      (wX_bits_x25 _ (v21 + sign_extend (m := 64) (0x000#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002784: `ld x14,0x98(x15)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002784_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x80002784#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v15 + sign_extend (m := 64) (0x098#12)).toNat)
    (hhiram : (v15 + sign_extend (m := 64) (0x098#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v15 + sign_extend (m := 64) (0x098#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v15 + sign_extend (m := 64) (0x098#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x14
        (sign_extend (m := 64)
          (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x098#12)).toNat : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_80002784 hmem
  exact stepObs_alu σ i u (0x80002784#64) vminstret (0x0987b703#32)
    (instruction.LOAD (0x098#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x0e#5, false, 8))
    Register.x14 (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x098#12)).toNat : BitVec (8 * 8)))
    (0x03#8) (0xb7#8) (0x87#8) (0x09#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_0987b703 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld_ram σ (0x80002784#64) (0x098#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0e#5)
      (sigma3_alu σ (0x80002784#64) Register.x14 (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x098#12)).toNat : BitVec (8 * 8))))
      v15 hG
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80002784#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x14 _ (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x098#12)).toNat : BitVec (8 * 8))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80002788: `bltu x9,x14` (NOT taken). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002788_nottaken_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v9 v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx9 : σ.regs.get? Register.x9 = some v9)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x80002788#64 : BitVec 64))
    (hv : zopz0zI_u v9 v14 = false) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_nottaken σ pc vminstret) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_80002788 hmem
  exact stepObs_branch_nottaken σ i u (0x80002788#64) vminstret (0x00c4#13)
    (regidx.Regidx 0x09#5) (regidx.Regidx 0x0e#5) bop.BLTU (0x0ce4e263#32)
    (0x63#8) (0xe2#8) (0xe4#8) (0x0c#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_0ce4e263 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_bltu_nottaken (0x00c4#13) (regidx.Regidx 0x09#5) (regidx.Regidx 0x0e#5)
      v9 v14 (afterNextPC (afterPrelude σ) (0x80002788#64))
      (rX_bits_x9 _ v9
        (by rw [get?_afterNextPC σ (0x80002788#64) _ (by decide) (by decide)]; exact hx9))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x80002788#64) _ (by decide) (by decide)]; exact hx14))
      hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8000278c: `lw x15,0x0(x20)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8000278c_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v20 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx20 : σ.regs.get? Register.x20 = some v20)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x8000278c#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v20 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhiram : (v20 + sign_extend (m := 64) (0x000#12)).toNat + 4 ≤ 0x100000000)
    (hhtif : (v20 + sign_extend (m := 64) (0x000#12)).toNat + 4 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v20 + sign_extend (m := 64) (0x000#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        (sign_extend (m := 64)
          (bytesT4 σ.mem (v20 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 4)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_8000278c hmem
  exact stepObs_alu σ i u (0x8000278c#64) vminstret (0x000a2783#32)
    (instruction.LOAD (0x000#12, regidx.Regidx 0x14#5, regidx.Regidx 0x0f#5, false, 4))
    Register.x15 (sign_extend (m := 64) (bytesT4 σ.mem (v20 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 4)))
    (0x83#8) (0x27#8) (0x0a#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_000a2783 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_lw_ram σ (0x8000278c#64) (0x000#12) (regidx.Regidx 0x14#5) (regidx.Regidx 0x0f#5)
      (sigma3_alu σ (0x8000278c#64) Register.x15 (sign_extend (m := 64) (bytesT4 σ.mem (v20 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 4))))
      v20 hG
      (rX_bits_x20 _ v20
        (by rw [get?_afterNextPC σ (0x8000278c#64) _ (by decide) (by decide)]; exact hx20))
      (wX_bits_x15 _ (sign_extend (m := 64) (bytesT4 σ.mem (v20 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 4))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- Branch target of the taken site at 0x80002790. -/
theorem site_80002790_taken_appterm_suffix_tgt :
    (0x80002790#64 + sign_extend (m := 64) (0x17cc#13)) = (0x80001f5c#64 : BitVec 64) := by
  apply BitVec.eq_of_toNat_eq; decide

/-- 0x80002790: `beq x15,x0 → 0x80001f5c` (TAKEN). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80002790_taken_appterm_suffix (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlApptermSuffixLoaded σ.mem)
    (hpcv : pc = (0x80002790#64 : BitVec 64))
    (hv : (v15 == (0#64)) = true) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_taken σ pc vminstret (0x17cc#13)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlApptermSuffix_at_80002790 hmem
  exact stepObs_branch_taken σ i u (0x80002790#64) vminstret (0x17cc#13)
    (regidx.Regidx 0x0f#5) (regidx.Regidx 0x00#5) bop.BEQ (0xfc078663#32)
    (0x63#8) (0x86#8) (0x07#8) (0xfc#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_fc078663 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_beq_taken (0x17cc#13) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x00#5)
      v15 (0#64) (0x80002790#64) initMisa (afterNextPC (afterPrelude σ) (0x80002790#64))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80002790#64) _ (by decide) (by decide)]; exact hx15))
      (rX_bits_zero _)
      (by rw [get?_afterNextPC σ (0x80002790#64) _ (by decide) (by decide)]; exact hpc)
      (by rw [get?_afterNextPC σ (0x80002790#64) _ (by decide) (by decide)]; exact hG.misa)
      (by rw [site_80002790_taken_appterm_suffix_tgt]; decide) hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

end Vsa.Sim
