import OCaml.Vm.Platform
import Vsa.Sim.Code.CamlBleintNext

/-! GENERATED by scripts/gen_arm_pilot.py. Full-image projection. -/
namespace OCaml.Vm.Sim
open Vsa.Machine

theorem bleint_next_loaded {c : Config} (h : ExecutableImage c) :
    Vsa.Sim.Code.CamlBleintNextLoaded c.σ.mem := by
  unfold Vsa.Sim.Code.CamlBleintNextLoaded Vsa.Sim.Code.camlBleintNextChunk0
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · have hb := h.text 13648 (by decide)
    have he : Image.textByte 13648 = (0x03#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13649 (by decide)
    have he : Image.textByte 13649 = (0x27#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13650 (by decide)
    have he : Image.textByte 13650 = (0x44#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13651 (by decide)
    have he : Image.textByte 13651 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13652 (by decide)
    have he : Image.textByte 13652 = (0x93#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13653 (by decide)
    have he : Image.textByte 13653 = (0xd7#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13654 (by decide)
    have he : Image.textByte 13654 = (0x1a#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13655 (by decide)
    have he : Image.textByte 13655 = (0x40#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13656 (by decide)
    have he : Image.textByte 13656 = (0x63#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13657 (by decide)
    have he : Image.textByte 13657 = (0xc2#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13658 (by decide)
    have he : Image.textByte 13658 = (0xe7#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13659 (by decide)
    have he : Image.textByte 13659 = (0x10#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13916 (by decide)
    have he : Image.textByte 13916 = (0x13#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13917 (by decide)
    have he : Image.textByte 13917 = (0x04#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13918 (by decide)
    have he : Image.textByte 13918 = (0xc4#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13919 (by decide)
    have he : Image.textByte 13919 = (0x00#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13920 (by decide)
    have he : Image.textByte 13920 = (0x6f#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13921 (by decide)
    have he : Image.textByte 13921 = (0xe0#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13922 (by decide)
    have he : Image.textByte 13922 = (0xdf#8) := by decide +kernel
    rw [he] at hb
    exact hb
  · have hb := h.text 13923 (by decide)
    have he : Image.textByte 13923 = (0x8f#8) := by decide +kernel
    rw [he] at hb
    exact hb

end OCaml.Vm.Sim
