import Vsa.Sim.ValueSites
import Vsa.Sim.RamReadPins
import Vsa.Sim.ExecLoadTotal
import Vsa.Sim.Code.CamlBranch
import Vsa.Sim.ElfDecode.Part021
import Vsa.Sim.ElfDecode.Part025
import Vsa.Sim.ElfDecode.Part032
import Vsa.Sim.ElfDecode.Part203

/-!
GENERATED by scripts/gen_arm_pilot.py via scripts/syi/gen_sites.py from
branch.tsv against `Vsa.Sim.Code.CamlBranchLoaded`.
Do not hand-edit; regenerate instead.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)



-- discipline: allow(R5-stepobs-volume) a per-site battery is one `stepObs_` per
-- site BY CONSTRUCTION; this file is machine-emitted from a TSV, not a
-- hand-threaded chain.
-- discipline: allow(R7-conj-tower-def) the existentials are the `∃ σ' i'` of each
-- site's `StepObs` conclusion (the landed shape), not new ∃/∧-tower posts.

namespace Vsa.Sim

/-- 0x80003104: `lw x8,0x4(x8)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003104_branch (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v8 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx8 : σ.regs.get? Register.x8 = some v8)
    (hmem : Vsa.Sim.Code.CamlBranchLoaded σ.mem)
    (hpcv : pc = (0x80003104#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v8 + sign_extend (m := 64) (0x004#12)).toNat)
    (hhiram : (v8 + sign_extend (m := 64) (0x004#12)).toNat + 4 ≤ 0x100000000)
    (hhtif : (v8 + sign_extend (m := 64) (0x004#12)).toNat + 4 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v8 + sign_extend (m := 64) (0x004#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x8
        (sign_extend (m := 64)
          (bytesT4 σ.mem (v8 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlBranch_at_80003104 hmem
  exact stepObs_alu σ i u (0x80003104#64) vminstret (0x00442403#32)
    (instruction.LOAD (0x004#12, regidx.Regidx 0x08#5, regidx.Regidx 0x08#5, false, 4))
    Register.x8 (sign_extend (m := 64) (bytesT4 σ.mem (v8 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4)))
    (0x03#8) (0x24#8) (0x44#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00442403 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_lw_ram σ (0x80003104#64) (0x004#12) (regidx.Regidx 0x08#5) (regidx.Regidx 0x08#5)
      (sigma3_alu σ (0x80003104#64) Register.x8 (sign_extend (m := 64) (bytesT4 σ.mem (v8 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))))
      v8 hG
      (rX_bits_x8 _ v8
        (by rw [get?_afterNextPC σ (0x80003104#64) _ (by decide) (by decide)]; exact hx8))
      (wX_bits_x8 _ (sign_extend (m := 64) (bytesT4 σ.mem (v8 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80003108: `slli`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003108_branch (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v8 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx8 : σ.regs.get? Register.x8 = some v8)
    (hmem : Vsa.Sim.Code.CamlBranchLoaded σ.mem)
    (hpcv : pc = (0x80003108#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x8 (shift_bits_left v8 (Sail.BitVec.extractLsb (0x02#6) 5 0))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlBranch_at_80003108 hmem
  exact stepObs_alu σ i u (0x80003108#64) vminstret (0x00241413#32)
    (instruction.SHIFTIOP ((0x002#6), (regidx.Regidx 0x08#5), (regidx.Regidx 0x08#5), sop.SLLI))
    Register.x8 (shift_bits_left v8 (Sail.BitVec.extractLsb (0x02#6) 5 0))
    (0x13#8) (0x14#8) (0x24#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00241413 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_shiftiop_slli_char (0x002#6) (regidx.Regidx 0x08#5) (regidx.Regidx 0x08#5) v8
      (afterNextPC (afterPrelude σ) (0x80003108#64))
      (sigma3_alu σ (0x80003108#64) Register.x8 (shift_bits_left v8 (Sail.BitVec.extractLsb (0x02#6) 5 0)))
      (rX_bits_x8 _ v8
        (by rw [get?_afterNextPC σ (0x80003108#64) _ (by decide) (by decide)]; exact hx8))
      (wX_bits_x8 _ (shift_bits_left v8 (Sail.BitVec.extractLsb (0x02#6) 5 0))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8000310c: `add x8,x23,x8`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8000310c_branch (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v23 v8 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx23 : σ.regs.get? Register.x23 = some v23)
    (hx8 : σ.regs.get? Register.x8 = some v8)
    (hmem : Vsa.Sim.Code.CamlBranchLoaded σ.mem)
    (hpcv : pc = (0x8000310c#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x8 (v23 + v8)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlBranch_at_8000310c hmem
  exact stepObs_alu σ i u (0x8000310c#64) vminstret (0x008b8433#32)
    (instruction.RTYPE (regidx.Regidx 0x08#5, regidx.Regidx 0x17#5, regidx.Regidx 0x08#5, rop.ADD))
    Register.x8 (v23 + v8)
    (0x33#8) (0x84#8) (0x8b#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_008b8433 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_rtype_add_char (regidx.Regidx 0x08#5) (regidx.Regidx 0x17#5) (regidx.Regidx 0x08#5)
      v23 v8 (afterNextPC (afterPrelude σ) (0x8000310c#64))
      (sigma3_alu σ (0x8000310c#64) Register.x8 (v23 + v8))
      (rX_bits_x23 _ v23
        (by rw [get?_afterNextPC σ (0x8000310c#64) _ (by decide) (by decide)]; exact hx23))
      (rX_bits_x8 _ v8
        (by rw [get?_afterNextPC σ (0x8000310c#64) _ (by decide) (by decide)]; exact hx8))
      (wX_bits_x8 _ (v23 + v8)))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80003110: `j 0x80001f5c`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003110_branch (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hmem : Vsa.Sim.Code.CamlBranchLoaded σ.mem)
    (hpcv : pc = (0x80003110#64 : BitVec 64))
    (htgt : (pc + sign_extend (m := 64) (0x1fee4c#21)).toNat % 4 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_jump_x0 σ pc vminstret (pc + sign_extend (m := 64) (0x1fee4c#21))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlBranch_at_80003110 hmem
  exact stepObs_j σ i u (0x80003110#64) vminstret (0xe4dfe06f#32) (0x1fee4c#21)
    (0x6f#8) (0xe0#8) (0xdf#8) (0xe4#8)
    hG hpc hminstret hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) (by decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_e4dfe06f (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    htgt hi

end Vsa.Sim
