-- GENERATED by scripts/gen_forward_copy.py; do not edit.
import OCaml.Vm.Sim.ClosurerecCopyMore
import OCaml.Vm.Sim.ClosurerecCopyLast

namespace OCaml.Vm.Sim
set_option autoImplicit false
open Vsa.Machine Vsa.Sim

/-- The actual CLOSUREREC cursor loop copies every word using its generated native branches. -/
theorem closurerec_copy_run {source target : Nat} {words : List (BitVec 64)} {initial : Config}
    (region : ClosurerecCopyRegion source target words initial)
    (base : gpr initial 10 = some (BitVec.ofNat 64 target)) :
    Vsa.Logic.Triple (ClosurerecCopyAt source target words initial 0)
      (ClosurerecCopyAt source target words initial words.length) :=
  cursor_copy_run_of_branches region
    (fun _ _ h bound more => closurerec_copy_more region base h bound more)
    (fun _ _ h bound last => closurerec_copy_last region base h bound last)

end OCaml.Vm.Sim
