-- GENERATED by scripts/gen_forward_copy.py; do not edit.
import OCaml.Vm.Sim.CursorCopyMore
import OCaml.Vm.Sim.CursorCopyLast

namespace OCaml.Vm.Sim
set_option autoImplicit false
open Vsa.Machine Vsa.Sim

/-- The actual GRAB cursor loop copies every word using its generated native branches. -/
theorem cursor_copy_run {source target : Nat} {words : List (BitVec 64)} {initial : Config}
    (region : CursorCopyRegion source target words initial) :
    Vsa.Logic.Triple (CursorCopyAt source target words initial 0)
      (CursorCopyAt source target words initial words.length) :=
  cursor_copy_run_of_branches region
    (fun _ _ h bound more => cursor_copy_more region h bound more)
    (fun _ _ h bound last => cursor_copy_last region h bound last)

end OCaml.Vm.Sim
