import Vsa.Sim.ValueSites
import Vsa.Sim.RamReadPins
import Vsa.Sim.ExecLoadTotal
import Vsa.Sim.Code.CamlGrabCopyMore
import Vsa.Sim.ElfDecode.Part012
import Vsa.Sim.ElfDecode.Part030
import Vsa.Sim.ElfDecode.Part031
import Vsa.Sim.ElfDecode.Part222
import Vsa.Sim.ElfDecode.Part223

/-!
GENERATED by scripts/gen_arm_pilot.py via scripts/syi/gen_sites.py from
grab_copy_more.tsv against `Vsa.Sim.Code.CamlGrabCopyMoreLoaded`.
Do not hand-edit; regenerate instead.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)



-- discipline: allow(R5-stepobs-volume) a per-site battery is one `stepObs_` per
-- site BY CONSTRUCTION; this file is machine-emitted from a TSV, not a
-- hand-threaded chain.
-- discipline: allow(R7-conj-tower-def) the existentials are the `∃ σ' i'` of each
-- site's `StepObs` conclusion (the landed shape), not new ∃/∧-tower posts.

namespace Vsa.Sim

/-- 0x80003700: `ld x13,0x0(x15)` — TOTAL (no byte-presence hypothesis). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003700_grab_copy_more (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlGrabCopyMoreLoaded σ.mem)
    (hpcv : pc = (0x80003700#64 : BitVec 64))
    (hlo : 0x80000000 ≤ (v15 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhiram : (v15 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hhtif : (v15 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr
      ∨ tohostAddr + 8 ≤ (v15 + sign_extend (m := 64) (0x000#12)).toNat)
    (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x13
        (sign_extend (m := 64)
          (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlGrabCopyMore_at_80003700 hmem
  exact stepObs_alu σ i u (0x80003700#64) vminstret (0x0007b683#32)
    (instruction.LOAD (0x000#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x0d#5, false, 8))
    Register.x13 (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8)))
    (0x83#8) (0xb6#8) (0x07#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_0007b683 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_ld_ram σ (0x80003700#64) (0x000#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0d#5)
      (sigma3_alu σ (0x80003700#64) Register.x13 (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
      v15 hG
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80003700#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x13 _ (sign_extend (m := 64) (bytesT8 σ.mem (v15 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
      hlo hhiram hhtif)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80003704: `addi x15,x15,0x8`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003704_grab_copy_more (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlGrabCopyMoreLoaded σ.mem)
    (hpcv : pc = (0x80003704#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x15
        (v15 + sign_extend (m := 64) (0x008#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlGrabCopyMore_at_80003704 hmem
  exact stepObs_alu σ i u (0x80003704#64) vminstret (0x00878793#32)
    (instruction.ITYPE (0x008#12, regidx.Regidx 0x0f#5, regidx.Regidx 0x0f#5, iop.ADDI))
    Register.x15 (v15 + sign_extend (m := 64) (0x008#12))
    (0x93#8) (0x87#8) (0x87#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00878793 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x008#12) (regidx.Regidx 0x0f#5) (regidx.Regidx 0x0f#5) v15
      (afterNextPC (afterPrelude σ) (0x80003704#64))
      (sigma3_alu σ (0x80003704#64) Register.x15 (v15 + sign_extend (m := 64) (0x008#12)))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80003704#64) _ (by decide) (by decide)]; exact hx15))
      (wX_bits_x15 _ (v15 + sign_extend (m := 64) (0x008#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x80003708: `addi x14,x14,0x8`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003708_grab_copy_more (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v14 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hmem : Vsa.Sim.Code.CamlGrabCopyMoreLoaded σ.mem)
    (hpcv : pc = (0x80003708#64 : BitVec 64)) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_alu σ pc vminstret Register.x14
        (v14 + sign_extend (m := 64) (0x008#12))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlGrabCopyMore_at_80003708 hmem
  exact stepObs_alu σ i u (0x80003708#64) vminstret (0x00870713#32)
    (instruction.ITYPE (0x008#12, regidx.Regidx 0x0e#5, regidx.Regidx 0x0e#5, iop.ADDI))
    Register.x14 (v14 + sign_extend (m := 64) (0x008#12))
    (0x13#8) (0x07#8) (0x87#8) (0x00#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_00870713 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_itype_addi_char (0x008#12) (regidx.Regidx 0x0e#5) (regidx.Regidx 0x0e#5) v14
      (afterNextPC (afterPrelude σ) (0x80003708#64))
      (sigma3_alu σ (0x80003708#64) Register.x14 (v14 + sign_extend (m := 64) (0x008#12)))
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x80003708#64) _ (by decide) (by decide)]; exact hx14))
      (wX_bits_x14 _ (v14 + sign_extend (m := 64) (0x008#12))))
    (by decide) (by decide) (by decide) (by decide) (by decide)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- 0x8000370c: `sd x13,0xff8(x14)`. -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_8000370c_grab_copy_more (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v14 v13 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx14 : σ.regs.get? Register.x14 = some v14)
    (hx13 : σ.regs.get? Register.x13 = some v13)
    (hmem : Vsa.Sim.Code.CamlGrabCopyMoreLoaded σ.mem)
    (hpcv : pc = (0x8000370c#64 : BitVec 64))
    (halo : 0x80000000 ≤ (v14 + sign_extend (m := 64) (0xff8#12)).toNat)
    (hahiram : (v14 + sign_extend (m := 64) (0xff8#12)).toNat + 8 ≤ 0x100000000)
    (hahiwin : tohostAddr + 16 ≤ (v14 + sign_extend (m := 64) (0xff8#12)).toNat)
    (haalign : (v14 + sign_extend (m := 64) (0xff8#12)).toNat % 8 = 0) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = writeMap8 (afterNextPC (afterPrelude σ) (0x8000370c#64)).mem
        (v14 + sign_extend (m := 64) (0xff8#12)).toNat (sdData_val v13) ∧
      ReadsLikePost σ' (sigmaPost_store σ pc vminstret
        (writeMap8 (afterNextPC (afterPrelude σ) (0x8000370c#64)).mem (v14 + sign_extend (m := 64) (0xff8#12)).toNat (sdData_val v13))) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlGrabCopyMore_at_8000370c hmem
  exact stepObs_store σ i u (0x8000370c#64) vminstret (0xfed73c23#32)
    (instruction.STORE (0xff8#12, regidx.Regidx 0x0d#5, regidx.Regidx 0x0e#5, 8))
    (writeMap8 (afterNextPC (afterPrelude σ) (0x8000370c#64)).mem (v14 + sign_extend (m := 64) (0xff8#12)).toNat (sdData_val v13))
    (0x23#8) (0x3c#8) (0xd7#8) (0xfe#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_fed73c23 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (exec_sd_val σ (0x8000370c#64) (0xff8#12) (regidx.Regidx 0x0d#5) (regidx.Regidx 0x0e#5)
      v14 v13 hG
      (rX_bits_x14 _ v14
        (by rw [get?_afterNextPC σ (0x8000370c#64) _ (by decide) (by decide)]; exact hx14))
      (rX_bits_x13 _ v13
        (by rw [get?_afterNextPC σ (0x8000370c#64) _ (by decide) (by decide)]; exact hx13))
      halo hahiram hahiwin haalign)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

/-- Branch target of the taken site at 0x80003710. -/
theorem site_80003710_taken_grab_copy_more_tgt :
    (0x80003710#64 + sign_extend (m := 64) (0x1ff0#13)) = (0x80003700#64 : BitVec 64) := by
  apply BitVec.eq_of_toNat_eq; decide

/-- 0x80003710: `bne x12,x15 → 0x80003700` (TAKEN). -/
-- discipline: allow(R1-site-battery) machine-emitted from a TSV by scripts/gen_sites.py; R1 targets HAND-written batteries
theorem site_80003710_taken_grab_copy_more (σ : MState) (i u : Nat) (pc : BitVec 64) (vminstret v12 v15 : BitVec 64)
    (hG : GoodState σ) (hpc : σ.regs.get? Register.PC = some pc)
    (hminstret : σ.regs.get? Register.minstret = some vminstret)
    (hx12 : σ.regs.get? Register.x12 = some v12)
    (hx15 : σ.regs.get? Register.x15 = some v15)
    (hmem : Vsa.Sim.Code.CamlGrabCopyMoreLoaded σ.mem)
    (hpcv : pc = (0x80003710#64 : BitVec 64))
    (hv : (v12 != v15) = true) (hi : i < 2) :
    ∃ (σ' : MState) (i' : Nat),
      Vsa.Machine.Step ⟨σ, i, u⟩ ⟨σ', i', u + 1⟩ ∧ i' < 2 ∧ GoodState σ' ∧
      σ'.mem = σ.mem ∧
      ReadsLikePost σ' (sigmaPost_branch_taken σ pc vminstret (0x1ff0#13)) := by
  subst hpcv
  obtain ⟨hb0, hb1, hb2, hb3⟩ := Vsa.Sim.Code.camlGrabCopyMore_at_80003710 hmem
  exact stepObs_branch_taken σ i u (0x80003710#64) vminstret (0x1ff0#13)
    (regidx.Regidx 0x0c#5) (regidx.Regidx 0x0f#5) bop.BNE (0xfef618e3#32)
    (0xe3#8) (0x18#8) (0xf6#8) (0xfe#8)
    hG hpc hminstret (by apply BitVec.eq_of_toNat_eq; decide)
    (by apply BitVec.eq_of_toNat_eq; decide)
    (Vsa.Sim.ElfDecode.decode_fef618e3 (afterPrelude σ)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.misa)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.cur_privilege)
      (by rw [get?_afterPrelude σ _ (by decide)]; exact hG.mseccfg))
    (execute_btype_bne_taken (0x1ff0#13) (regidx.Regidx 0x0c#5) (regidx.Regidx 0x0f#5)
      v12 v15 (0x80003710#64) initMisa (afterNextPC (afterPrelude σ) (0x80003710#64))
      (rX_bits_x12 _ v12
        (by rw [get?_afterNextPC σ (0x80003710#64) _ (by decide) (by decide)]; exact hx12))
      (rX_bits_x15 _ v15
        (by rw [get?_afterNextPC σ (0x80003710#64) _ (by decide) (by decide)]; exact hx15))
      (by rw [get?_afterNextPC σ (0x80003710#64) _ (by decide) (by decide)]; exact hpc)
      (by rw [get?_afterNextPC σ (0x80003710#64) _ (by decide) (by decide)]; exact hG.misa)
      (by rw [site_80003710_taken_grab_copy_more_tgt]; decide) hv)
    hb0 hb1 hb2 hb3 (by decide) (by decide) (by decide) hi

end Vsa.Sim
