-- GENERATED by scripts/gen_makeblock_fixed.py; do not edit.
import OCaml.Vm.Sim.MakeblockInput
import OCaml.Vm.Sim.Makeblock3FastSegment
import OCaml.Vm.Sim.Makeblock3FastPins
import OCaml.Vm.Sim.Makeblock3FastLayout
import OCaml.Vm.Sim.Immediate
import OCaml.Vm.Sim.StackPush

namespace OCaml.Vm.Sim
set_option autoImplicit false
open OCaml.Bytecode Vsa.Machine Vsa.Sim LeanRV64DExecutable LeanRV64DExecutable.Functions
open OCaml.Vm.Primitives

/-- MAKEBLOCK3 initializes a fresh nursery block through the generated body. -/
theorem makeblock3_arm {L : OCaml.Layout} {P : Prog} {s : St} {c : Config}
    {pl : Place} {cp : ChanPlace} {sp high a domain limit : Nat} {accu : BitVec 64} {tag : BitVec 32}
    (runtime : AllocationRuntime L.runtimeOk c (makeblockLog c sp 3 tag.toInt.toNat a domain accu))
    (h : ArmInput L P s .MAKEBLOCK3 c pl cp sp high)
    (operand : OperandAt P pl (s.pc + 1) tag) (nonnegative : 0 ≤ tag.toInt)
    (value : valWord pl s.accu = some accu)
    (space : MakeblockInput P s c pl cp sp high 3 tag.toInt.toNat a domain limit accu) :
    ∃ after, Plus c after ∧ Running L P (makeblockState s 2 3 tag.toInt.toNat) after := by
  have room := space.room
  have logEq : makeblockLog c sp 3 tag.toInt.toNat a domain accu = [(domain + Layout.off_young_ptr, 8, BitVec.ofNat 64 (a - 8)), (a - 8, 8, blockHeader 3 tag.toInt.toNat), (a, 8, accu), (a + 8, 8, word c (sp)), (a + 16, 8, word c (sp + 8))] := by
    simp [makeblockLog, grabReserveLog, blockLog, makeblockWords, valueLog, indexedLog, valueEntries,
      stackWords, List.range_succ]
  have domainRead : RamReadAt Layout.sym_Caml_state 8 := ⟨by decide, by decide, by decide⟩
  have youngRead := space.youngWrite.read
  have limitRead : RamReadAt domain 8 := by simpa only [Layout.off_young_limit, Nat.add_zero] using space.limitRead
  have headerWord : (((Sail.shift_bits_right (Sail.shift_bits_left (sign_extend (m := 64) tag) (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x7ff#12)) + sign_extend (m := 64) (0x401#12)) = blockHeader 3 tag.toInt.toNat := by
    rw [makeblock_tag_word tag nonnegative space.tagBound]
    try rw [BitVec.add_assoc]
    exact makeblock_header_word 3 tag.toInt.toNat
  have youngAddress : BitVec.ofNat 64 domain + sign_extend (m := 64) (0x008#12) =
      BitVec.ofNat 64 (domain + Layout.off_young_ptr) := by rw [BitVec.ofNat_add]; rfl
  have reserveAddress : BitVec.ofNat 64 (a + 24) + sign_extend (m := 64) (0xfe0#12) =
      BitVec.ofNat 64 (a - 8) := by
    have raw := stack_decrement (sp := a + 24) (n := 32) (by omega) (by decide)
      (show sign_extend (m := 64) (0xfe0#12) = -BitVec.ofNat 64 32 from by decide)
    simpa only [show a + 24 - 32 = a - 8 by omega] using raw
  have nextCode : BitVec.ofNat 64 (pl.codeBase + 4 * s.pc) + sign_extend (m := 64) (0x008#12) =
      BitVec.ofNat 64 (pl.codeBase + 4 * (s.pc + 2)) := codePc_add _ _ 2
  have fieldWrite0 : RamWriteAt (a) 8 := by
    simpa using space.fieldWrites 0 (by decide)
  have fieldAddress0 : BitVec.ofNat 64 (a - 8) + sign_extend (m := 64) (0x008#12) =
      BitVec.ofNat 64 (a) := by
    change BitVec.ofNat 64 (a - 8) + BitVec.ofNat 64 8 = _
    rw [← BitVec.ofNat_add]; congr 1; omega
  have fieldWrite1 : RamWriteAt (a + 8) 8 := by
    simpa using space.fieldWrites 1 (by decide)
  have fieldAddress1 : BitVec.ofNat 64 (a - 8) + sign_extend (m := 64) (0x010#12) =
      BitVec.ofNat 64 (a + 8) := by
    change BitVec.ofNat 64 (a - 8) + BitVec.ofNat 64 16 = _
    rw [← BitVec.ofNat_add]; congr 1; omega
  have fieldWrite2 : RamWriteAt (a + 16) 8 := by
    simpa using space.fieldWrites 2 (by decide)
  have fieldAddress2 : BitVec.ofNat 64 (a - 8) + sign_extend (m := 64) (0x018#12) =
      BitVec.ofNat 64 (a + 16) := by
    change BitVec.ofNat 64 (a - 8) + BitVec.ofNat 64 24 = _
    rw [← BitVec.ofNat_add]; congr 1; omega
  have newSp : BitVec.ofNat 64 sp + sign_extend (m := 64) (0x010#12) =
      BitVec.ofNat 64 (sp + 16) := by rw [BitVec.ofNat_add]; rfl
  have read0 : RamReadAt (sp) 8 := by simpa using space.reads 0 (by decide)
  have sourceAddress0 : BitVec.ofNat 64 (sp + 16) + sign_extend (m := 64) (0xff0#12) =
      BitVec.ofNat 64 (sp) := by
    have raw := stack_decrement (sp := sp + 16) (n := 16) (by omega) (by decide)
      (show sign_extend (m := 64) (0xff0#12) = -BitVec.ofNat 64 16 from by decide)
    simpa only [show sp + 16 - 16 = sp by omega] using raw
  have read1 : RamReadAt (sp + 8) 8 := by simpa using space.reads 1 (by decide)
  have sourceAddress1 : BitVec.ofNat 64 (sp + 16) + sign_extend (m := 64) (0xff8#12) =
      BitVec.ofNat 64 (sp + 8) := by
    have raw := stack_decrement (sp := sp + 16) (n := 8) (by omega) (by decide)
      (show sign_extend (m := 64) (0xff8#12) = -BitVec.ofNat 64 8 from by decide)
    simpa only [show sp + 16 - 8 = sp + 8 by omega] using raw
  have member1 : (domain + Layout.off_young_ptr, 8, BitVec.ofNat 64 (a - 8)) ∈ makeblockLog c sp 3 tag.toInt.toNat a domain accu := by rw [logEq]; simp
  have member2 : (a - 8, 8, blockHeader 3 tag.toInt.toNat) ∈ makeblockLog c sp 3 tag.toInt.toNat a domain accu := by rw [logEq]; simp
  have member3 : (a, 8, accu) ∈ makeblockLog c sp 3 tag.toInt.toNat a domain accu := by rw [logEq]; simp
  have member4 : (a + 8, 8, word c (sp)) ∈ makeblockLog c sp 3 tag.toInt.toNat a domain accu := by rw [logEq]; simp
  have member5 : (a + 16, 8, word c (sp + 8)) ∈ makeblockLog c sp 3 tag.toInt.toNat a domain accu := by rw [logEq]; simp
  have limitNat : (BitVec.ofNat 64 limit).toNat = limit :=
    Nat.mod_eq_of_lt (by have upper := space.headerWrite.upper; have capacity := space.capacity; omega)
  have capacity : zopz0zKzJ_u (BitVec.ofNat 64 (a - 8)) (BitVec.ofNat 64 limit) = true := by
    apply bgeu_of_le
    rw [space.headerWrite.read.toNat, limitNat]
    exact space.capacity
  apply dispatch_compose h.dispatch
  intro d dp
  obtain ⟨m1, hm1⟩ : ∃ m : Std.ExtHashMap Nat (BitVec 8),
      m = writeMap8 d.σ.mem (domain + Layout.off_young_ptr) (sdData_val (BitVec.ofNat 64 (a - 8))) := ⟨_, rfl⟩
  have memory1 : m1 = writeLog c.σ.mem ((makeblockLog c sp 3 tag.toInt.toNat a domain accu).take 1) := by
    rw [logEq, hm1, dp.memory]; rfl
  obtain ⟨m2, hm2⟩ : ∃ m : Std.ExtHashMap Nat (BitVec 8),
      m = writeMap8 m1 (a - 8) (sdData_val (blockHeader 3 tag.toInt.toNat)) := ⟨_, rfl⟩
  have memory2 : m2 = writeLog c.σ.mem ((makeblockLog c sp 3 tag.toInt.toNat a domain accu).take 2) := by
    rw [logEq, hm2, hm1, dp.memory]; rfl
  obtain ⟨m3, hm3⟩ : ∃ m : Std.ExtHashMap Nat (BitVec 8),
      m = writeMap8 m2 (a) (sdData_val (accu)) := ⟨_, rfl⟩
  have memory3 : m3 = writeLog c.σ.mem ((makeblockLog c sp 3 tag.toInt.toNat a domain accu).take 3) := by
    rw [logEq, hm3, hm2, hm1, dp.memory]; rfl
  obtain ⟨m4, hm4⟩ : ∃ m : Std.ExtHashMap Nat (BitVec 8),
      m = writeMap8 m3 (a + 8) (sdData_val (word c (sp))) := ⟨_, rfl⟩
  have memory4 : m4 = writeLog c.σ.mem ((makeblockLog c sp 3 tag.toInt.toNat a domain accu).take 4) := by
    rw [logEq, hm4, hm3, hm2, hm1, dp.memory]; rfl
  obtain ⟨m5, hm5⟩ : ∃ m : Std.ExtHashMap Nat (BitVec 8),
      m = writeMap8 m4 (a + 16) (sdData_val (word c (sp + 8))) := ⟨_, rfl⟩
  have memory5 : m5 = writeLog c.σ.mem ((makeblockLog c sp 3 tag.toInt.toNat a domain accu).take 5) := by
    rw [logEq, hm5, hm4, hm3, hm2, hm1, dp.memory]; rfl
  have fullMemory : m5 = writeLog c.σ.mem (makeblockLog c sp 3 tag.toInt.toNat a domain accu) := by
    rw [logEq, hm5, hm4, hm3, hm2, hm1, dp.memory]; rfl
  have youngAfter : sign_extend (m := 64) (bytesT8 m2 (domain + Layout.off_young_ptr)) = BitVec.ofNat 64 (a - 8) := by
    have read : bytesT m2 (domain + Layout.off_young_ptr) 8 = BitVec.ofNat 64 (a - 8) := by
      rw [memory2, logEq]
      exact word_writeLog_at c.σ.mem _ 0 _ _ rfl space.headerYoungOutside
    simpa only [bytesT_eight_eq, sign_extend, Sail.BitVec.signExtend, BitVec.signExtend_eq] using read
  have bp : SegSt (0x80002540#64)
      [⟨Register.x8, (BitVec.ofNat 64 (pl.codeBase + 4 * s.pc))⟩, ⟨Register.x9, (BitVec.ofNat 64 sp)⟩, ⟨Register.x21, accu⟩]
      (fun σ => Vsa.Sim.Code.CamlMakeblock3FastLoaded σ.mem ∧ σ.mem = d.σ.mem ∧ σ = d.σ) d :=
    ⟨dp.good, dp.pc, ⟨(dp.frame.frame Register.x8 (by decide)).trans h.pc, (dp.frame.frame Register.x9 (by decide)).trans h.spReg, (dp.frame.frame Register.x21 (by decide)).trans (represented_register h.accu value), trivial⟩,
      dp.good.minstret, dp.tick, makeblock3_fast_loaded (dp.image h.dispatch.image), rfl, rfl⟩
  have run0 := tr_makeblock3_fast (BitVec.ofNat 64 (pl.codeBase + 4 * s.pc)) (BitVec.ofNat 64 sp) accu d.σ.mem d.σ
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run0
  have run1 := run0 domainRead.lower domainRead.upper domainRead.htif (BitVec.ofNat 64 domain)
    (((word_read_writeLog_out (log := []) trivial dp.memory).trans space.domainValue).symm)
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run1
  have run2 := run1 operand.geometry.lower operand.geometry.upper operand.geometry.htif
    (sign_extend (m := 64) tag) (by rw [operand.read32 h.code dp.memory])
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run2
  have run3 := run2 youngRead.lower youngRead.upper youngRead.htif (BitVec.ofNat 64 (a + 24))
    (((word_read_writeLog_out (log := []) trivial dp.memory).trans space.youngValue).symm)
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run3
  have run4 := run3 limitRead.lower limitRead.upper limitRead.htif (BitVec.ofNat 64 limit)
    ((by simpa only [Layout.off_young_limit, Nat.add_zero] using ((word_read_writeLog_out (log := []) trivial dp.memory).trans space.limitValue).symm))
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run4
  have run5 := run4 space.youngWrite.lower space.youngWrite.upper space.youngWrite.htif space.youngWrite.aligned
    (image_entry_code space.image member1 (by decide) (by decide)) m1 hm1
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run5
  have run6 := run5 capacity
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run6
  have run7 := run6 space.headerWrite.lower space.headerWrite.upper space.headerWrite.htif space.headerWrite.aligned
    (image_entry_code space.image member2 (by decide) (by decide)) m2 hm2
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run7
  have run8 := run7 domainRead.lower domainRead.upper domainRead.htif (BitVec.ofNat 64 domain)
    (((word_read_writeLog_out (outLRange_sublist (List.take_sublist 2 _) space.payload.domain) memory2).trans space.domainValue).symm)
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run8
  have run9 := run8 youngRead.lower youngRead.upper youngRead.htif (BitVec.ofNat 64 (a - 8))
    (youngAfter.symm)
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run9
  have run10 := run9 fieldWrite0.lower fieldWrite0.upper fieldWrite0.htif fieldWrite0.aligned
    (image_entry_code space.image member3 (by decide) (by decide)) m3 hm3
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run10
  have run11 := run10 read0.lower read0.upper read0.htif (word c (sp))
    ((word_read_writeLog_out (outLRange_sublist (List.take_sublist 3 _) (payload_stack_outside space.payload (by have bound := space.bound; omega : 0 < s.stack.length))) memory3).symm)
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run11
  have run12 := run11 fieldWrite1.lower fieldWrite1.upper fieldWrite1.htif fieldWrite1.aligned
    (image_entry_code space.image member4 (by decide) (by decide)) m4 hm4
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run12
  have run13 := run12 read1.lower read1.upper read1.htif (word c (sp + 8))
    ((word_read_writeLog_out (outLRange_sublist (List.take_sublist 4 _) (payload_stack_outside space.payload (by have bound := space.bound; omega : 1 < s.stack.length))) memory4).symm)
  try simp only [makeblock3_fast_domain0, makeblock3_fast_domain1, youngAddress, reserveAddress, headerWord, nextCode, codePc_succ, show sign_extend (m := 64) (0x004#12) = 4#64 from by decide, show sign_extend (m := 64) (0x000#12) = 0#64 from by decide, BitVec.add_zero, domainRead.toNat, youngRead.toNat, limitRead.toNat, operand.geometry.toNat, space.headerWrite.read.toNat, fieldAddress0, fieldWrite0.read.toNat, fieldAddress1, fieldWrite1.read.toNat, fieldAddress2, fieldWrite2.read.toNat, newSp, sourceAddress0, read0.toNat, sourceAddress1, read1.toNat] at run13
  have run14 := run13 fieldWrite2.lower fieldWrite2.upper fieldWrite2.htif fieldWrite2.aligned
    (image_entry_code space.image member5 (by decide) (by decide)) m5 hm5
  obtain ⟨nb, after, _, steps, post⟩ := run14 d bp
  obtain ⟨_, memory, rawFrame⟩ := post.extra
  have frame := rawFrame.widenChecked (allowed := [Register.x13, Register.x14, Register.x15, Register.x16, Register.x21, Register.x23, Register.x8, Register.x9] ++ noiseRegs) (by decide)
  have observed : MakeblockPost c s pl sp 2 3 tag.toInt.toNat a domain accu after := by
    refine ⟨⟨post.pcAt, PinsHold.get post.pins ⟨5, by simp⟩, ?_, ⟨BitVec.ofNat 64 a, PinsHold.get post.pins ⟨1, by simp⟩, ?_⟩, ?_, ?_⟩,
      post.good, memory.trans fullMemory, frame.out.trans dp.frame.out, ?_,
      (frame.frame (gprReg 2) (by decide)).trans (dp.frame.frame (gprReg 2) (by decide))⟩
    · exact PinsHold.get post.pins ⟨3, by simp⟩
    · simp only [makeblockState, valWord, space.placed, Option.map_some, Nat.mul_zero, Nat.add_zero]
    · obtain ⟨w, reg, value⟩ := h.env
      exact ⟨w, (frame.frame Register.x25 (by decide)).trans ((dp.frame.frame Register.x25 (by decide)).trans reg), value⟩
    · exact (frame.frame Register.x18 (by decide)).trans ((dp.frame.frame Register.x18 (by decide)).trans h.extra)
    · exact loopRegisters_frame (fun r hr =>
        (frame.frame r (by revert r; decide)).trans (dp.frame.frame r (by revert r; decide))) h.dispatch.loop
  exact ⟨nb, after, steps, makeblock_restore runtime h.toVmReprAt h.running.platform value space.toMakeblockWriteOk observed h.geometry h.native⟩

/-- The successful fixed-arity bytecode constructor selects this represented block. -/
theorem makeblock3_step_arm {L : OCaml.Layout} {P : Prog} {s s' : St} {c : Config}
    {pl : Place} {cp : ChanPlace} {sp high a domain limit : Nat} {accu : BitVec 64} {tag : BitVec 32}
    (runtime : AllocationRuntime L.runtimeOk c (makeblockLog c sp 3 tag.toInt.toNat a domain accu))
    (h : ArmInput L P s .MAKEBLOCK3 c pl cp sp high)
    (operand : OperandAt P pl (s.pc + 1) tag) (nonnegative : 0 ≤ tag.toInt)
    (value : valWord pl s.accu = some accu)
    (space : MakeblockInput P s c pl cp sp high 3 tag.toInt.toNat a domain limit accu)
    (step : stepI P s ⟨.MAKEBLOCK3, [tag.toInt]⟩ = .next s') :
    ∃ after, Plus c after ∧ Running L P s' after := by
  have enough : ¬ s.stack.length < 3 - 1 := by have bound := space.bound; omega
  have state : makeblockState s 2 3 tag.toInt.toNat = s' := by
    simpa only [stepI, makeBlock, show ¬ (3 : Nat) = 0 by decide, enough, ite_false,
      makeblockState, makeblockObject, Res.next.injEq] using Res.unguard (Res.unguard step)
  rw [← state]
  exact makeblock3_arm runtime h operand nonnegative value space

end OCaml.Vm.Sim
