import OCaml.Vm.Sim.Makeblock1FastSites
import Vsa.Sim.SegState
import Vsa.Sim.StepCount
import Vsa.Sim.ChainFrameOut
import OCaml.Vm.Sim.Makeblock1FastStoreFrame
import Vsa.Sim.PinLookup

/-!
GENERATED by scripts/gen_arm_pilot.py via scripts/syi/gen_segment.py — do not hand-edit; regenerate instead.
MAKEBLOCK1_FAST arm body, generated from the census. This is a machine segment, not yet ArmSim.next.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic



namespace Vsa.Sim

/-- MAKEBLOCK1_FAST arm body, generated from the census. This is a machine segment, not yet ArmSim.next. -/
theorem tr_makeblock1_fast
    (v8 v21 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (σ0 : MState)
    (hlo_800025f0 : 0x80000000 ≤ ((((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12)) + sign_extend (m := 64) (0x000#12)).toNat)
    (hhi_800025f0 : ((((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12)) + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hhtif_800025f0 : ((((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12)) + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ ((((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12)) + sign_extend (m := 64) (0x000#12)).toNat)
    (loaded_800025f0 : BitVec 64)
    (hvalue_800025f0 : loaded_800025f0 = (sign_extend (m := 64) (bytesT8 m0 ((((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12)) + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
    (hlo_800025f4 : 0x80000000 ≤ (v8 + sign_extend (m := 64) (0x004#12)).toNat)
    (hhi_800025f4 : (v8 + sign_extend (m := 64) (0x004#12)).toNat + 4 ≤ 0x100000000)
    (hhtif_800025f4 : (v8 + sign_extend (m := 64) (0x004#12)).toNat + 4 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (v8 + sign_extend (m := 64) (0x004#12)).toNat)
    (loaded_800025f4 : BitVec 64)
    (hvalue_800025f4 : loaded_800025f4 = (sign_extend (m := 64) (bytesT4 m0 (v8 + sign_extend (m := 64) (0x004#12)).toNat : BitVec (8 * 4))))
    (hlo_800025fc : 0x80000000 ≤ (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhi_800025fc : (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x100000000)
    (hhtif_800025fc : (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat)
    (loaded_800025fc : BitVec 64)
    (hvalue_800025fc : loaded_800025fc = (sign_extend (m := 64) (bytesT8 m0 (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 8))))
    (hlo_80002600 : 0x80000000 ≤ (loaded_800025f0 + sign_extend (m := 64) (0x000#12)).toNat)
    (hhi_80002600 : (loaded_800025f0 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hhtif_80002600 : (loaded_800025f0 + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (loaded_800025f0 + sign_extend (m := 64) (0x000#12)).toNat)
    (loaded_80002600 : BitVec 64)
    (hvalue_80002600 : loaded_80002600 = (sign_extend (m := 64) (bytesT8 m0 (loaded_800025f0 + sign_extend (m := 64) (0x000#12)).toNat : BitVec (8 * 8))))
    (hlo_80002608 : 0x80000000 ≤ (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhi_80002608 : (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x100000000)
    (hhtif_80002608 : tohostAddr + 16 ≤ (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat)
    (halign_80002608 : (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat % 8 = 0)
    (hcode_80002608 : (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x800025e8 ∨ 0x8000263c ≤ (loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat)
    (m_80002608 : Std.ExtHashMap Nat (BitVec 8))
    (hstore_80002608 : m_80002608 = writeMap8 (m0) ((loaded_800025f0 + sign_extend (m := 64) (0x008#12)).toNat) (sdData_val (loaded_800025fc + sign_extend (m := 64) (0xff0#12))))
    (hguard_8000260c : zopz0zKzJ_u (loaded_800025fc + sign_extend (m := 64) (0xff0#12)) loaded_80002600 = true)
    (hlo_80002620 : 0x80000000 ≤ ((loaded_800025fc + sign_extend (m := 64) (0xff0#12)) + sign_extend (m := 64) (0x000#12)).toNat)
    (hhi_80002620 : ((loaded_800025fc + sign_extend (m := 64) (0xff0#12)) + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x100000000)
    (hhtif_80002620 : tohostAddr + 16 ≤ ((loaded_800025fc + sign_extend (m := 64) (0xff0#12)) + sign_extend (m := 64) (0x000#12)).toNat)
    (halign_80002620 : ((loaded_800025fc + sign_extend (m := 64) (0xff0#12)) + sign_extend (m := 64) (0x000#12)).toNat % 8 = 0)
    (hcode_80002620 : ((loaded_800025fc + sign_extend (m := 64) (0xff0#12)) + sign_extend (m := 64) (0x000#12)).toNat + 8 ≤ 0x800025e8 ∨ 0x8000263c ≤ ((loaded_800025fc + sign_extend (m := 64) (0xff0#12)) + sign_extend (m := 64) (0x000#12)).toNat)
    (m_80002620 : Std.ExtHashMap Nat (BitVec 8))
    (hstore_80002620 : m_80002620 = writeMap8 (m_80002608) (((loaded_800025fc + sign_extend (m := 64) (0xff0#12)) + sign_extend (m := 64) (0x000#12)).toNat) (sdData_val ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))))
    (hlo_80002628 : 0x80000000 ≤ (((0x80002624#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x6e4#12)).toNat)
    (hhi_80002628 : (((0x80002624#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x6e4#12)).toNat + 8 ≤ 0x100000000)
    (hhtif_80002628 : (((0x80002624#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x6e4#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (((0x80002624#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x6e4#12)).toNat)
    (loaded_80002628 : BitVec 64)
    (hvalue_80002628 : loaded_80002628 = (sign_extend (m := 64) (bytesT8 (m_80002620) (((0x80002624#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x6e4#12)).toNat : BitVec (8 * 8))))
    (hlo_8000262c : 0x80000000 ≤ (loaded_80002628 + sign_extend (m := 64) (0x008#12)).toNat)
    (hhi_8000262c : (loaded_80002628 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x100000000)
    (hhtif_8000262c : (loaded_80002628 + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ tohostAddr ∨ tohostAddr + 8 ≤ (loaded_80002628 + sign_extend (m := 64) (0x008#12)).toNat)
    (loaded_8000262c : BitVec 64)
    (hvalue_8000262c : loaded_8000262c = (sign_extend (m := 64) (bytesT8 (m_80002620) (loaded_80002628 + sign_extend (m := 64) (0x008#12)).toNat : BitVec (8 * 8))))
    (hlo_80002630 : 0x80000000 ≤ (loaded_8000262c + sign_extend (m := 64) (0x008#12)).toNat)
    (hhi_80002630 : (loaded_8000262c + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x100000000)
    (hhtif_80002630 : tohostAddr + 16 ≤ (loaded_8000262c + sign_extend (m := 64) (0x008#12)).toNat)
    (halign_80002630 : (loaded_8000262c + sign_extend (m := 64) (0x008#12)).toNat % 8 = 0)
    (hcode_80002630 : (loaded_8000262c + sign_extend (m := 64) (0x008#12)).toNat + 8 ≤ 0x800025e8 ∨ 0x8000263c ≤ (loaded_8000262c + sign_extend (m := 64) (0x008#12)).toNat)
    (m_80002630 : Std.ExtHashMap Nat (BitVec 8))
    (hstore_80002630 : m_80002630 = writeMap8 (m_80002620) ((loaded_8000262c + sign_extend (m := 64) (0x008#12)).toNat) (sdData_val v21))
    : TripleN 20 (SegSt (0x800025e8#64) [⟨Register.x8, v8⟩, ⟨Register.x21, v21⟩]
      (fun σ => Vsa.Sim.Code.CamlMakeblock1FastLoaded σ.mem ∧ σ.mem = m0 ∧ σ = σ0)) (SegSt (0x80001f5c#64) [⟨Register.x21, (loaded_8000262c + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x15, loaded_8000262c⟩, ⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩]
      (fun σ => Vsa.Sim.Code.CamlMakeblock1FastLoaded σ.mem ∧ σ.mem = m_80002630 ∧ StepFrameOut ((Register.x16 :: noiseRegs) ++ (Register.x16 :: noiseRegs) ++ (Register.x14 :: noiseRegs) ++ (Register.x23 :: noiseRegs) ++ (Register.x8 :: noiseRegs) ++ (Register.x15 :: noiseRegs) ++ (Register.x13 :: noiseRegs) ++ (Register.x15 :: noiseRegs) ++ noiseRegs ++ noiseRegs ++ (Register.x14 :: noiseRegs) ++ (Register.x14 :: noiseRegs) ++ (Register.x14 :: noiseRegs) ++ noiseRegs ++ (Register.x15 :: noiseRegs) ++ (Register.x15 :: noiseRegs) ++ (Register.x15 :: noiseRegs) ++ noiseRegs ++ (Register.x21 :: noiseRegs) ++ noiseRegs) σ0 σ)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq, hinitial⟩⟩ := hPre
  -- === step 1: 0x800025e8 `site_800025e8_makeblock1_fast` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_800025e8_makeblock1_fast c.σ c.tick (c.steps) (0x800025e8#64)
      vmi  hgood hpc hmi  hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x800025ec#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x800025e8#64) 4 = (0x800025ec#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x16 = some ((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x16, ((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12)))⟩, ⟨Register.x8, v8⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x800025ec `site_800025ec_makeblock1_fast` (alu) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_800025ec_makeblock1_fast σ1 i1 (c.steps + 1) (0x800025ec#64)
      vmi1 ((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) hG1 hpc1 hmi1 (PinsHold.get hp1 ⟨0, by simp⟩) hload1 rfl hi1
  have hpc2 : σ2.regs.get? Register.PC = some (0x800025f0#64 : BitVec 64) := by
    have := obs_alu_pc hobs2
    rwa [show BitVec.addInt (0x800025ec#64) 4 = (0x800025f0#64 : BitVec 64) from by decide] at this
  have hrd2 : σ2.regs.get? Register.x16 = some (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12)) :=
    obs_alu_rd hobs2 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq2 : PinsHold σ1 [⟨Register.x8, v8⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp1 ⟨1, by simp⟩), (PinsHold.get hp1 ⟨2, by simp⟩), trivial⟩
  have hp2 : PinsHold σ2 [⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x8, v8⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd2, pins_alu hobs2 (by rfl) hq2⟩
  obtain ⟨vmi2, hmi2⟩ := obs_alu_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  -- === step 3: 0x800025f0 `site_800025f0_makeblock1_fast` (alu) ===
  obtain ⟨σ3, i3, hs3, hi3, hG3, hmem3, hobs3⟩ :=
    site_800025f0_makeblock1_fast σ2 i2 (c.steps + 1 + 1) (0x800025f0#64)
      vmi2 (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12)) hG2 hpc2 hmi2 (PinsHold.get hp2 ⟨0, by simp⟩) hload2 rfl hlo_800025f0 hhi_800025f0 hhtif_800025f0 hi2
  have hpc3 : σ3.regs.get? Register.PC = some (0x800025f4#64 : BitVec 64) := by
    have := obs_alu_pc hobs3
    rwa [show BitVec.addInt (0x800025f0#64) 4 = (0x800025f4#64 : BitVec 64) from by decide] at this
  have hrd3 : σ3.regs.get? Register.x14 = some loaded_800025f0 := by
    have := obs_alu_rd hobs3 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE2, ← hvalue_800025f0] at this
  have hp3 : PinsHold σ3 [⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x8, v8⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd3, pins_alu hobs3 (by rfl) hp2⟩
  obtain ⟨vmi3, hmi3⟩ := obs_alu_minstret hobs3
  have hmemE3 : σ3.mem = m0 := by
    rw [hmem3]; exact hmemE2
  have hload3 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ3.mem := by
    rw [hmem3]; exact hload2
  -- === step 4: 0x800025f4 `site_800025f4_makeblock1_fast` (alu) ===
  obtain ⟨σ4, i4, hs4, hi4, hG4, hmem4, hobs4⟩ :=
    site_800025f4_makeblock1_fast σ3 i3 (c.steps + 1 + 1 + 1) (0x800025f4#64)
      vmi3 v8 hG3 hpc3 hmi3 (PinsHold.get hp3 ⟨2, by simp⟩) hload3 rfl hlo_800025f4 hhi_800025f4 hhtif_800025f4 hi3
  have hpc4 : σ4.regs.get? Register.PC = some (0x800025f8#64 : BitVec 64) := by
    have := obs_alu_pc hobs4
    rwa [show BitVec.addInt (0x800025f4#64) 4 = (0x800025f8#64 : BitVec 64) from by decide] at this
  have hrd4 : σ4.regs.get? Register.x23 = some loaded_800025f4 := by
    have := obs_alu_rd hobs4 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE3, ← hvalue_800025f4] at this
  have hp4 : PinsHold σ4 [⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x8, v8⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd4, pins_alu hobs4 (by rfl) hp3⟩
  obtain ⟨vmi4, hmi4⟩ := obs_alu_minstret hobs4
  have hmemE4 : σ4.mem = m0 := by
    rw [hmem4]; exact hmemE3
  have hload4 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ4.mem := by
    rw [hmem4]; exact hload3
  -- === step 5: 0x800025f8 `site_800025f8_makeblock1_fast` (alu) ===
  obtain ⟨σ5, i5, hs5, hi5, hG5, hmem5, hobs5⟩ :=
    site_800025f8_makeblock1_fast σ4 i4 (c.steps + 1 + 1 + 1 + 1) (0x800025f8#64)
      vmi4 v8 hG4 hpc4 hmi4 (PinsHold.get hp4 ⟨3, by simp⟩) hload4 rfl hi4
  have hpc5 : σ5.regs.get? Register.PC = some (0x800025fc#64 : BitVec 64) := by
    have := obs_alu_pc hobs5
    rwa [show BitVec.addInt (0x800025f8#64) 4 = (0x800025fc#64 : BitVec 64) from by decide] at this
  have hrd5 : σ5.regs.get? Register.x8 = some (v8 + sign_extend (m := 64) (0x008#12)) :=
    obs_alu_rd hobs5 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq5 : PinsHold σ4 [⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp4 ⟨0, by simp⟩), (PinsHold.get hp4 ⟨1, by simp⟩), (PinsHold.get hp4 ⟨2, by simp⟩), (PinsHold.get hp4 ⟨4, by simp⟩), trivial⟩
  have hp5 : PinsHold σ5 [⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd5, pins_alu hobs5 (by rfl) hq5⟩
  obtain ⟨vmi5, hmi5⟩ := obs_alu_minstret hobs5
  have hmemE5 : σ5.mem = m0 := by
    rw [hmem5]; exact hmemE4
  have hload5 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ5.mem := by
    rw [hmem5]; exact hload4
  -- === step 6: 0x800025fc `site_800025fc_makeblock1_fast` (alu) ===
  obtain ⟨σ6, i6, hs6, hi6, hG6, hmem6, hobs6⟩ :=
    site_800025fc_makeblock1_fast σ5 i5 (c.steps + 1 + 1 + 1 + 1 + 1) (0x800025fc#64)
      vmi5 loaded_800025f0 hG5 hpc5 hmi5 (PinsHold.get hp5 ⟨2, by simp⟩) hload5 rfl hlo_800025fc hhi_800025fc hhtif_800025fc hi5
  have hpc6 : σ6.regs.get? Register.PC = some (0x80002600#64 : BitVec 64) := by
    have := obs_alu_pc hobs6
    rwa [show BitVec.addInt (0x800025fc#64) 4 = (0x80002600#64 : BitVec 64) from by decide] at this
  have hrd6 : σ6.regs.get? Register.x15 = some loaded_800025fc := by
    have := obs_alu_rd hobs6 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE5, ← hvalue_800025fc] at this
  have hp6 : PinsHold σ6 [⟨Register.x15, loaded_800025fc⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd6, pins_alu hobs6 (by rfl) hp5⟩
  obtain ⟨vmi6, hmi6⟩ := obs_alu_minstret hobs6
  have hmemE6 : σ6.mem = m0 := by
    rw [hmem6]; exact hmemE5
  have hload6 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ6.mem := by
    rw [hmem6]; exact hload5
  -- === step 7: 0x80002600 `site_80002600_makeblock1_fast` (alu) ===
  obtain ⟨σ7, i7, hs7, hi7, hG7, hmem7, hobs7⟩ :=
    site_80002600_makeblock1_fast σ6 i6 (c.steps + 1 + 1 + 1 + 1 + 1 + 1) (0x80002600#64)
      vmi6 loaded_800025f0 hG6 hpc6 hmi6 (PinsHold.get hp6 ⟨3, by simp⟩) hload6 rfl hlo_80002600 hhi_80002600 hhtif_80002600 hi6
  have hpc7 : σ7.regs.get? Register.PC = some (0x80002604#64 : BitVec 64) := by
    have := obs_alu_pc hobs7
    rwa [show BitVec.addInt (0x80002600#64) 4 = (0x80002604#64 : BitVec 64) from by decide] at this
  have hrd7 : σ7.regs.get? Register.x13 = some loaded_80002600 := by
    have := obs_alu_rd hobs7 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE6, ← hvalue_80002600] at this
  have hp7 : PinsHold σ7 [⟨Register.x13, loaded_80002600⟩, ⟨Register.x15, loaded_800025fc⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd7, pins_alu hobs7 (by rfl) hp6⟩
  obtain ⟨vmi7, hmi7⟩ := obs_alu_minstret hobs7
  have hmemE7 : σ7.mem = m0 := by
    rw [hmem7]; exact hmemE6
  have hload7 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ7.mem := by
    rw [hmem7]; exact hload6
  -- === step 8: 0x80002604 `site_80002604_makeblock1_fast` (alu) ===
  obtain ⟨σ8, i8, hs8, hi8, hG8, hmem8, hobs8⟩ :=
    site_80002604_makeblock1_fast σ7 i7 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002604#64)
      vmi7 loaded_800025fc hG7 hpc7 hmi7 (PinsHold.get hp7 ⟨1, by simp⟩) hload7 rfl hi7
  have hpc8 : σ8.regs.get? Register.PC = some (0x80002608#64 : BitVec 64) := by
    have := obs_alu_pc hobs8
    rwa [show BitVec.addInt (0x80002604#64) 4 = (0x80002608#64 : BitVec 64) from by decide] at this
  have hrd8 : σ8.regs.get? Register.x15 = some (loaded_800025fc + sign_extend (m := 64) (0xff0#12)) :=
    obs_alu_rd hobs8 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq8 : PinsHold σ7 [⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp7 ⟨0, by simp⟩), (PinsHold.get hp7 ⟨2, by simp⟩), (PinsHold.get hp7 ⟨3, by simp⟩), (PinsHold.get hp7 ⟨4, by simp⟩), (PinsHold.get hp7 ⟨5, by simp⟩), (PinsHold.get hp7 ⟨6, by simp⟩), trivial⟩
  have hp8 : PinsHold σ8 [⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd8, pins_alu hobs8 (by rfl) hq8⟩
  obtain ⟨vmi8, hmi8⟩ := obs_alu_minstret hobs8
  have hmemE8 : σ8.mem = m0 := by
    rw [hmem8]; exact hmemE7
  have hload8 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ8.mem := by
    rw [hmem8]; exact hload7
  -- === step 9: 0x80002608 `site_80002608_makeblock1_fast` (sd) ===
  obtain ⟨σ9, i9, hs9, hi9, hG9, hmem9, hobs9⟩ :=
    site_80002608_makeblock1_fast σ8 i8 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002608#64)
      vmi8 loaded_800025f0 (loaded_800025fc + sign_extend (m := 64) (0xff0#12)) hG8 hpc8 hmi8 (PinsHold.get hp8 ⟨4, by simp⟩) (PinsHold.get hp8 ⟨0, by simp⟩) hload8 rfl hlo_80002608 hhi_80002608 hhtif_80002608 halign_80002608 hi8
  have hpc9 : σ9.regs.get? Register.PC = some (0x8000260c#64 : BitVec 64) := by
    have := obs_store_pc hobs9
    rwa [show BitVec.addInt (0x80002608#64) 4 = (0x8000260c#64 : BitVec 64) from by decide] at this
  have hp9 : PinsHold σ9 [⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    pins_store hobs9 (by rfl) hp8
  obtain ⟨vmi9, hmi9⟩ := obs_store_minstret hobs9
  have hmemE9 : σ9.mem = m_80002608 := by
    rw [hmem9, mem_afterNextPC, hmemE8, ← hstore_80002608]
  have hload9 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ9.mem := by
    rw [hmemE9, hstore_80002608]
    exact makeblock1_fast_code_store _ _ _ hcode_80002608 (hmemE8 ▸ hload8)
  -- === step 10: 0x8000260c `site_8000260c_taken_makeblock1_fast` (btaken) ===
  obtain ⟨σ10, i10, hs10, hi10, hG10, hmem10, hobs10⟩ :=
    site_8000260c_taken_makeblock1_fast σ9 i9 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8000260c#64)
      vmi9 (loaded_800025fc + sign_extend (m := 64) (0xff0#12)) loaded_80002600 hG9 hpc9 hmi9 (PinsHold.get hp9 ⟨0, by simp⟩) (PinsHold.get hp9 ⟨1, by simp⟩) hload9 rfl hguard_8000260c hi9
  have hpc10 : σ10.regs.get? Register.PC = some (0x80002614#64 : BitVec 64) := by
    rw [obs_btaken_pc hobs10,
      show (0x8000260c#64 : BitVec 64) + sign_extend (m := 64) (0x0008#13) = (0x80002614#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp10 : PinsHold σ10 [⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x14, loaded_800025f0⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    pins_btaken hobs10 (by rfl) hp9
  obtain ⟨vmi10, hmi10⟩ := obs_btaken_minstret hobs10
  have hmemE10 : σ10.mem = m_80002608 := by
    rw [hmem10]; exact hmemE9
  have hload10 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ10.mem := by
    rw [hmem10]; exact hload9
  -- === step 11: 0x80002614 `site_80002614_makeblock1_fast` (alu) ===
  obtain ⟨σ11, i11, hs11, hi11, hG11, hmem11, hobs11⟩ :=
    site_80002614_makeblock1_fast σ10 i10 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002614#64)
      vmi10 loaded_800025f4 hG10 hpc10 hmi10 (PinsHold.get hp10 ⟨3, by simp⟩) hload10 rfl hi10
  have hpc11 : σ11.regs.get? Register.PC = some (0x80002618#64 : BitVec 64) := by
    have := obs_alu_pc hobs11
    rwa [show BitVec.addInt (0x80002614#64) 4 = (0x80002618#64 : BitVec 64) from by decide] at this
  have hrd11 : σ11.regs.get? Register.x14 = some (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) :=
    obs_alu_rd hobs11 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq11 : PinsHold σ10 [⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp10 ⟨0, by simp⟩), (PinsHold.get hp10 ⟨1, by simp⟩), (PinsHold.get hp10 ⟨2, by simp⟩), (PinsHold.get hp10 ⟨3, by simp⟩), (PinsHold.get hp10 ⟨5, by simp⟩), (PinsHold.get hp10 ⟨6, by simp⟩), trivial⟩
  have hp11 : PinsHold σ11 [⟨Register.x14, (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0))⟩, ⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd11, pins_alu hobs11 (by rfl) hq11⟩
  obtain ⟨vmi11, hmi11⟩ := obs_alu_minstret hobs11
  have hmemE11 : σ11.mem = m_80002608 := by
    rw [hmem11]; exact hmemE10
  have hload11 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ11.mem := by
    rw [hmem11]; exact hload10
  -- === step 12: 0x80002618 `site_80002618_makeblock1_fast` (alu) ===
  obtain ⟨σ12, i12, hs12, hi12, hG12, hmem12, hobs12⟩ :=
    site_80002618_makeblock1_fast σ11 i11 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002618#64)
      vmi11 (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) hG11 hpc11 hmi11 (PinsHold.get hp11 ⟨0, by simp⟩) hload11 rfl hi11
  have hpc12 : σ12.regs.get? Register.PC = some (0x8000261c#64 : BitVec 64) := by
    have := obs_alu_pc hobs12
    rwa [show BitVec.addInt (0x80002618#64) 4 = (0x8000261c#64 : BitVec 64) from by decide] at this
  have hrd12 : σ12.regs.get? Register.x14 = some (shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) :=
    obs_alu_rd hobs12 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq12 : PinsHold σ11 [⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp11 ⟨1, by simp⟩), (PinsHold.get hp11 ⟨2, by simp⟩), (PinsHold.get hp11 ⟨3, by simp⟩), (PinsHold.get hp11 ⟨4, by simp⟩), (PinsHold.get hp11 ⟨5, by simp⟩), (PinsHold.get hp11 ⟨6, by simp⟩), trivial⟩
  have hp12 : PinsHold σ12 [⟨Register.x14, (shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0))⟩, ⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd12, pins_alu hobs12 (by rfl) hq12⟩
  obtain ⟨vmi12, hmi12⟩ := obs_alu_minstret hobs12
  have hmemE12 : σ12.mem = m_80002608 := by
    rw [hmem12]; exact hmemE11
  have hload12 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ12.mem := by
    rw [hmem12]; exact hload11
  -- === step 13: 0x8000261c `site_8000261c_makeblock1_fast` (alu) ===
  obtain ⟨σ13, i13, hs13, hi13, hG13, hmem13, hobs13⟩ :=
    site_8000261c_makeblock1_fast σ12 i12 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8000261c#64)
      vmi12 (shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) hG12 hpc12 hmi12 (PinsHold.get hp12 ⟨0, by simp⟩) hload12 rfl hi12
  have hpc13 : σ13.regs.get? Register.PC = some (0x80002620#64 : BitVec 64) := by
    have := obs_alu_pc hobs13
    rwa [show BitVec.addInt (0x8000261c#64) 4 = (0x80002620#64 : BitVec 64) from by decide] at this
  have hrd13 : σ13.regs.get? Register.x14 = some ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12)) :=
    obs_alu_rd hobs13 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq13 : PinsHold σ12 [⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp12 ⟨1, by simp⟩), (PinsHold.get hp12 ⟨2, by simp⟩), (PinsHold.get hp12 ⟨3, by simp⟩), (PinsHold.get hp12 ⟨4, by simp⟩), (PinsHold.get hp12 ⟨5, by simp⟩), (PinsHold.get hp12 ⟨6, by simp⟩), trivial⟩
  have hp13 : PinsHold σ13 [⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd13, pins_alu hobs13 (by rfl) hq13⟩
  obtain ⟨vmi13, hmi13⟩ := obs_alu_minstret hobs13
  have hmemE13 : σ13.mem = m_80002608 := by
    rw [hmem13]; exact hmemE12
  have hload13 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ13.mem := by
    rw [hmem13]; exact hload12
  -- === step 14: 0x80002620 `site_80002620_makeblock1_fast` (sd) ===
  obtain ⟨σ14, i14, hs14, hi14, hG14, hmem14, hobs14⟩ :=
    site_80002620_makeblock1_fast σ13 i13 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002620#64)
      vmi13 (loaded_800025fc + sign_extend (m := 64) (0xff0#12)) ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12)) hG13 hpc13 hmi13 (PinsHold.get hp13 ⟨1, by simp⟩) (PinsHold.get hp13 ⟨0, by simp⟩) hload13 rfl hlo_80002620 hhi_80002620 hhtif_80002620 halign_80002620 hi13
  have hpc14 : σ14.regs.get? Register.PC = some (0x80002624#64 : BitVec 64) := by
    have := obs_store_pc hobs14
    rwa [show BitVec.addInt (0x80002620#64) 4 = (0x80002624#64 : BitVec 64) from by decide] at this
  have hp14 : PinsHold σ14 [⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x15, (loaded_800025fc + sign_extend (m := 64) (0xff0#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    pins_store hobs14 (by rfl) hp13
  obtain ⟨vmi14, hmi14⟩ := obs_store_minstret hobs14
  have hmemE14 : σ14.mem = m_80002620 := by
    rw [hmem14, mem_afterNextPC, hmemE13, ← hstore_80002620]
  have hload14 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ14.mem := by
    rw [hmemE14, hstore_80002620]
    exact makeblock1_fast_code_store _ _ _ hcode_80002620 (hmemE13 ▸ hload13)
  -- === step 15: 0x80002624 `site_80002624_makeblock1_fast` (alu) ===
  obtain ⟨σ15, i15, hs15, hi15, hG15, hmem15, hobs15⟩ :=
    site_80002624_makeblock1_fast σ14 i14 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002624#64)
      vmi14  hG14 hpc14 hmi14  hload14 rfl hi14
  have hpc15 : σ15.regs.get? Register.PC = some (0x80002628#64 : BitVec 64) := by
    have := obs_alu_pc hobs15
    rwa [show BitVec.addInt (0x80002624#64) 4 = (0x80002628#64 : BitVec 64) from by decide] at this
  have hrd15 : σ15.regs.get? Register.x15 = some ((0x80002624#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) :=
    obs_alu_rd hobs15 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq15 : PinsHold σ14 [⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp14 ⟨0, by simp⟩), (PinsHold.get hp14 ⟨2, by simp⟩), (PinsHold.get hp14 ⟨3, by simp⟩), (PinsHold.get hp14 ⟨4, by simp⟩), (PinsHold.get hp14 ⟨5, by simp⟩), (PinsHold.get hp14 ⟨6, by simp⟩), trivial⟩
  have hp15 : PinsHold σ15 [⟨Register.x15, ((0x80002624#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12)))⟩, ⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd15, pins_alu hobs15 (by rfl) hq15⟩
  obtain ⟨vmi15, hmi15⟩ := obs_alu_minstret hobs15
  have hmemE15 : σ15.mem = m_80002620 := by
    rw [hmem15]; exact hmemE14
  have hload15 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ15.mem := by
    rw [hmem15]; exact hload14
  -- === step 16: 0x80002628 `site_80002628_makeblock1_fast` (alu) ===
  obtain ⟨σ16, i16, hs16, hi16, hG16, hmem16, hobs16⟩ :=
    site_80002628_makeblock1_fast σ15 i15 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002628#64)
      vmi15 ((0x80002624#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) hG15 hpc15 hmi15 (PinsHold.get hp15 ⟨0, by simp⟩) hload15 rfl hlo_80002628 hhi_80002628 hhtif_80002628 hi15
  have hpc16 : σ16.regs.get? Register.PC = some (0x8000262c#64 : BitVec 64) := by
    have := obs_alu_pc hobs16
    rwa [show BitVec.addInt (0x80002628#64) 4 = (0x8000262c#64 : BitVec 64) from by decide] at this
  have hrd16 : σ16.regs.get? Register.x15 = some loaded_80002628 := by
    have := obs_alu_rd hobs16 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE15, ← hvalue_80002628] at this
  have hq16 : PinsHold σ15 [⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp15 ⟨1, by simp⟩), (PinsHold.get hp15 ⟨2, by simp⟩), (PinsHold.get hp15 ⟨3, by simp⟩), (PinsHold.get hp15 ⟨4, by simp⟩), (PinsHold.get hp15 ⟨5, by simp⟩), (PinsHold.get hp15 ⟨6, by simp⟩), trivial⟩
  have hp16 : PinsHold σ16 [⟨Register.x15, loaded_80002628⟩, ⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd16, pins_alu hobs16 (by rfl) hq16⟩
  obtain ⟨vmi16, hmi16⟩ := obs_alu_minstret hobs16
  have hmemE16 : σ16.mem = m_80002620 := by
    rw [hmem16]; exact hmemE15
  have hload16 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ16.mem := by
    rw [hmem16]; exact hload15
  -- === step 17: 0x8000262c `site_8000262c_makeblock1_fast` (alu) ===
  obtain ⟨σ17, i17, hs17, hi17, hG17, hmem17, hobs17⟩ :=
    site_8000262c_makeblock1_fast σ16 i16 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x8000262c#64)
      vmi16 loaded_80002628 hG16 hpc16 hmi16 (PinsHold.get hp16 ⟨0, by simp⟩) hload16 rfl hlo_8000262c hhi_8000262c hhtif_8000262c hi16
  have hpc17 : σ17.regs.get? Register.PC = some (0x80002630#64 : BitVec 64) := by
    have := obs_alu_pc hobs17
    rwa [show BitVec.addInt (0x8000262c#64) 4 = (0x80002630#64 : BitVec 64) from by decide] at this
  have hrd17 : σ17.regs.get? Register.x15 = some loaded_8000262c := by
    have := obs_alu_rd hobs17 (by decide) (by decide) (by decide) (by decide) (by decide)
    rwa [hmemE16, ← hvalue_8000262c] at this
  have hq17 : PinsHold σ16 [⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨(PinsHold.get hp16 ⟨1, by simp⟩), (PinsHold.get hp16 ⟨2, by simp⟩), (PinsHold.get hp16 ⟨3, by simp⟩), (PinsHold.get hp16 ⟨4, by simp⟩), (PinsHold.get hp16 ⟨5, by simp⟩), (PinsHold.get hp16 ⟨6, by simp⟩), trivial⟩
  have hp17 : PinsHold σ17 [⟨Register.x15, loaded_8000262c⟩, ⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    ⟨hrd17, pins_alu hobs17 (by rfl) hq17⟩
  obtain ⟨vmi17, hmi17⟩ := obs_alu_minstret hobs17
  have hmemE17 : σ17.mem = m_80002620 := by
    rw [hmem17]; exact hmemE16
  have hload17 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ17.mem := by
    rw [hmem17]; exact hload16
  -- === step 18: 0x80002630 `site_80002630_makeblock1_fast` (sd) ===
  obtain ⟨σ18, i18, hs18, hi18, hG18, hmem18, hobs18⟩ :=
    site_80002630_makeblock1_fast σ17 i17 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002630#64)
      vmi17 loaded_8000262c v21 hG17 hpc17 hmi17 (PinsHold.get hp17 ⟨0, by simp⟩) (PinsHold.get hp17 ⟨6, by simp⟩) hload17 rfl hlo_80002630 hhi_80002630 hhtif_80002630 halign_80002630 hi17
  have hpc18 : σ18.regs.get? Register.PC = some (0x80002634#64 : BitVec 64) := by
    have := obs_store_pc hobs18
    rwa [show BitVec.addInt (0x80002630#64) 4 = (0x80002634#64 : BitVec 64) from by decide] at this
  have hp18 : PinsHold σ18 [⟨Register.x15, loaded_8000262c⟩, ⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩, ⟨Register.x21, v21⟩] :=
    pins_store hobs18 (by rfl) hp17
  obtain ⟨vmi18, hmi18⟩ := obs_store_minstret hobs18
  have hmemE18 : σ18.mem = m_80002630 := by
    rw [hmem18, mem_afterNextPC, hmemE17, ← hstore_80002630]
  have hload18 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ18.mem := by
    rw [hmemE18, hstore_80002630]
    exact makeblock1_fast_code_store _ _ _ hcode_80002630 (hmemE17 ▸ hload17)
  -- === step 19: 0x80002634 `site_80002634_makeblock1_fast` (alu) ===
  obtain ⟨σ19, i19, hs19, hi19, hG19, hmem19, hobs19⟩ :=
    site_80002634_makeblock1_fast σ18 i18 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002634#64)
      vmi18 loaded_8000262c hG18 hpc18 hmi18 (PinsHold.get hp18 ⟨0, by simp⟩) hload18 rfl hi18
  have hpc19 : σ19.regs.get? Register.PC = some (0x80002638#64 : BitVec 64) := by
    have := obs_alu_pc hobs19
    rwa [show BitVec.addInt (0x80002634#64) 4 = (0x80002638#64 : BitVec 64) from by decide] at this
  have hrd19 : σ19.regs.get? Register.x21 = some (loaded_8000262c + sign_extend (m := 64) (0x008#12)) :=
    obs_alu_rd hobs19 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hq19 : PinsHold σ18 [⟨Register.x15, loaded_8000262c⟩, ⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩] :=
    ⟨(PinsHold.get hp18 ⟨0, by simp⟩), (PinsHold.get hp18 ⟨1, by simp⟩), (PinsHold.get hp18 ⟨2, by simp⟩), (PinsHold.get hp18 ⟨3, by simp⟩), (PinsHold.get hp18 ⟨4, by simp⟩), (PinsHold.get hp18 ⟨5, by simp⟩), trivial⟩
  have hp19 : PinsHold σ19 [⟨Register.x21, (loaded_8000262c + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x15, loaded_8000262c⟩, ⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩] :=
    ⟨hrd19, pins_alu hobs19 (by rfl) hq19⟩
  obtain ⟨vmi19, hmi19⟩ := obs_alu_minstret hobs19
  have hmemE19 : σ19.mem = m_80002630 := by
    rw [hmem19]; exact hmemE18
  have hload19 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ19.mem := by
    rw [hmem19]; exact hload18
  -- === step 20: 0x80002638 `site_80002638_makeblock1_fast` (j) ===
  obtain ⟨σ20, i20, hs20, hi20, hG20, hmem20, hobs20⟩ :=
    site_80002638_makeblock1_fast σ19 i19 (c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) (0x80002638#64)
      vmi19 hG19 hpc19 hmi19 hload19 rfl (by decide) hi19
  have hpc20 : σ20.regs.get? Register.PC = some (0x80001f5c#64 : BitVec 64) := by
    rw [obs_jr_pc hobs20,
      show (0x80002638#64 : BitVec 64) + sign_extend (m := 64) (0x1ff924#21) = (0x80001f5c#64 : BitVec 64) from by apply BitVec.eq_of_toNat_eq; decide]
  have hp20 : PinsHold σ20 [⟨Register.x21, (loaded_8000262c + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x15, loaded_8000262c⟩, ⟨Register.x14, ((shift_bits_right (shift_bits_left loaded_800025f4 (Sail.BitVec.extractLsb (0x20#6) 5 0)) (Sail.BitVec.extractLsb (0x20#6) 5 0)) + sign_extend (m := 64) (0x400#12))⟩, ⟨Register.x13, loaded_80002600⟩, ⟨Register.x8, (v8 + sign_extend (m := 64) (0x008#12))⟩, ⟨Register.x23, loaded_800025f4⟩, ⟨Register.x16, (((0x800025e8#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x720#12))⟩] :=
    pins_jr hobs20 (by rfl) hp19
  obtain ⟨vmi20, hmi20⟩ := obs_jr_minstret hobs20
  have hmemE20 : σ20.mem = m_80002630 := by
    rw [hmem20]; exact hmemE19
  have hload20 : Vsa.Sim.Code.CamlMakeblock1FastLoaded σ20.mem := by
    rw [hmem20]; exact hload19
  have hsteps20 : Steps c ⟨σ20, i20, c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1⟩ :=
    (((((((((((((((((((Steps.single hs1).trans (Steps.single hs2)).trans (Steps.single hs3)).trans (Steps.single hs4)).trans (Steps.single hs5)).trans (Steps.single hs6)).trans (Steps.single hs7)).trans (Steps.single hs8)).trans (Steps.single hs9)).trans (Steps.single hs10)).trans (Steps.single hs11)).trans (Steps.single hs12)).trans (Steps.single hs13)).trans (Steps.single hs14)).trans (Steps.single hs15)).trans (Steps.single hs16)).trans (Steps.single hs17)).trans (Steps.single hs18)).trans (Steps.single hs19)).trans (Steps.single hs20)
  have hwhole : StepFrameOut ((Register.x16 :: noiseRegs) ++ (Register.x16 :: noiseRegs) ++ (Register.x14 :: noiseRegs) ++ (Register.x23 :: noiseRegs) ++ (Register.x8 :: noiseRegs) ++ (Register.x15 :: noiseRegs) ++ (Register.x13 :: noiseRegs) ++ (Register.x15 :: noiseRegs) ++ noiseRegs ++ noiseRegs ++ (Register.x14 :: noiseRegs) ++ (Register.x14 :: noiseRegs) ++ (Register.x14 :: noiseRegs) ++ noiseRegs ++ (Register.x15 :: noiseRegs) ++ (Register.x15 :: noiseRegs) ++ (Register.x15 :: noiseRegs) ++ noiseRegs ++ (Register.x21 :: noiseRegs) ++ noiseRegs) σ0 σ20 := by
    rw [← hinitial]
    chain_frame_out [hobs1, hobs2, hobs3, hobs4, hobs5, hobs6, hobs7, hobs8, hobs9, hobs10, hobs11, hobs12, hobs13, hobs14, hobs15, hobs16, hobs17, hobs18, hobs19, hobs20]
  have hcount : Vsa.Machine.StepsN 20 c ⟨σ20, i20, c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1⟩ :=
    hsteps20.toN_of_stepsEq rfl
  exact ⟨20, ⟨σ20, i20, c.steps + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1⟩, Nat.le_refl _, hcount,
    ⟨hG20, hpc20, hp20, ⟨vmi20, hmi20⟩, hi20, ⟨hload20, hmemE20, hwhole⟩⟩⟩

end Vsa.Sim
