import OCaml.Vm.Sim.RaiseQuietState
import OCaml.Vm.Sim.ReraiseQuietSegment
import OCaml.Vm.Sim.ReraiseQuietPins

/-! GENERATED by scripts/gen_raise_quiet.py. Quiet caught-exception caller composition. -/
namespace OCaml.Vm.Sim
set_option autoImplicit false
open OCaml.Bytecode Vsa.Machine Vsa.Sim OCaml.Vm.Primitives LeanRV64DExecutable LeanRV64DExecutable.Functions

/-- The native quiet path reaches the common caught-handler check. -/
theorem reraise_quiet_setup {L : OCaml.Layout} {P : Prog} {s : St} {pl : Place} {cp : ChanPlace}
    {sp high dest : Nat} {link extra : BitVec 63} {env : Val} {rest : List Val} {c d : Config}
    (h : ArmInput L P s .RERAISE c pl cp sp high) (frame : RaiseFrame s dest link env extra rest)
    (quiet : RaiseQuietReady high c) (stable : MemoryStable L.runtimeOk)
    (dp : DispatchPost c .RERAISE (BitVec.ofNat 64 (pl.codeBase + 4 * s.pc)) d) :
    ∃ count after, StepsN count d after ∧ RaiseReadPost (0x80001ed4#64) c L P s pl cp sp high dest link env extra rest after := by
  have context := raise_context h frame
  have load (a : Nat) : sign_extend (m := 64) (bytesT8 d.σ.mem a) = word c a :=
    word_read_writeLog_out (log := []) trivial dp.memory
  have globalAddress : ((((0x80002c48#64) + (sign_extend (m := 64) ((0x00062#20) +++ 0x000#12))) + sign_extend (m := 64) (0x0c0#12)) + sign_extend (m := 64) (0x000#12)) = BitVec.ofNat 64 Layout.sym_Caml_state := by decide
  have bp : SegSt (0x80002c48#64) []
      (fun σ => Vsa.Sim.Code.CamlReraiseQuietLoaded σ.mem ∧ σ.mem = d.σ.mem ∧ σ = d.σ) d :=
    ⟨dp.good, dp.pc, trivial, dp.good.minstret, dp.tick, reraise_quiet_loaded (dp.image h.dispatch.image), rfl, rfl⟩
  have native := tr_reraise_quiet d.σ.mem d.σ
  simp only [globalAddress, show (BitVec.ofNat 64 Layout.sym_Caml_state).toNat = Layout.sym_Caml_state from by decide] at native
  have domainStep := native (by decide) (by decide) (by decide) (word c Layout.sym_Caml_state) (load _).symm
  simp only [show sign_extend (m := 64) (0x0a8#12) = BitVec.ofNat 64 Layout.off_trapsp from by decide,
    show sign_extend (m := 64) (0x0b0#12) = BitVec.ofNat 64 Layout.off_trap_barrier from by decide,
    show sign_extend (m := 64) (0x0e8#12) = BitVec.ofNat 64 Layout.off_backtrace_active from by decide,
    domain_field_address, quiet.trapRead.toNat, quiet.barrierRead.toNat, quiet.backtraceRead.toNat] at domainStep
  have below : zopz0zI_u (BitVec.ofNat 64 (high - 8 * s.trap)) (word c ((word c Layout.sym_Caml_state).toNat + Layout.off_trap_barrier)) = true := by
    simpa only [native_ult, BitVec.ule_eq_not_ult, Bool.not_not] using quiet.below context.caught_guard
  obtain ⟨count, after, _, run, post⟩ := domainStep quiet.trapRead.lower quiet.trapRead.upper quiet.trapRead.htif (BitVec.ofNat 64 (high - 8 * s.trap)) (by rw [load, context.trap_word]) quiet.barrierRead.lower quiet.barrierRead.upper quiet.barrierRead.htif (word c ((word c Layout.sym_Caml_state).toNat + Layout.off_trap_barrier)) (load _).symm (by simp only [native_uge, quiet.below context.caught_guard, Bool.not_true]) quiet.backtraceRead.lower quiet.backtraceRead.upper quiet.backtraceRead.htif 0#64 (by rw [load, quiet.backtrace]) (by decide) quiet.trapRead.lower quiet.trapRead.upper quiet.trapRead.htif (BitVec.ofNat 64 (high - 8 * s.trap)) (by rw [load, context.trap_word]) d bp
  obtain ⟨_, memory, nativeFrame⟩ := post.extra
  have trapReg : gpr after 14 = some (BitVec.ofNat 64 (high - 8 * s.trap)) := PinsHold.get post.pins ⟨0, by simp⟩
  have domainReg : gpr after 15 = some (word c Layout.sym_Caml_state) := PinsHold.get post.pins ⟨2, by simp⟩
  have memoryAll := memory.trans dp.memory
  refine ⟨count, after, run, ?_, memoryAll,
    (nativeFrame.frame Register.x2 (by decide)).trans (dp.frame.frame Register.x2 (by decide))⟩
  refine {
    toRaiseContext := context.after_read stable post.good post.tick memoryAll (nativeFrame.out.trans dp.frame.out)
      ((nativeFrame.frame _ (by decide)).trans (dp.frame.frame _ (by decide)))
      ((nativeFrame.frame (gprReg 2) (by decide)).trans (dp.frame.frame (gprReg 2) (by decide)))
    pc := post.pcAt, trapReg := trapReg, domainReg := ?_ }
  simpa only [word, memoryAll] using domainReg

/-- Execute the quiet caught exception, including handler selection and restoration. -/
theorem reraise_quiet_arm {L : OCaml.Layout} {P : Prog} {s : St} {pl : Place} {cp : ChanPlace}
    {sp high dest nativeSp : Nat} {link extra : BitVec 63} {env : Val} {rest : List Val} {c : Config}
    (h : ArmInput L P s .RERAISE c pl cp sp high) (frame : RaiseFrame s dest link env extra rest)
    (quiet : RaiseQuietReady high c) (stable : MemoryStable L.runtimeOk)
    (saved : RaiseStackFrame nativeSp c) (nonnegative : 0 ≤ extra.toInt)
    (writeStable : WindowStable L.runtimeOk [⟨(word c Layout.sym_Caml_state).toNat + Layout.off_trapsp,
      (word c Layout.sym_Caml_state).toNat + Layout.off_trapsp + 8⟩])
    (reads : RaiseFrameReads (high - 8 * s.trap))
    (space : TrapWriteOk P s c pl cp sp high (s.trap - link.toNat)) :
    ∃ after, Plus c after ∧ Running L P {s with pc := dest, env := env, extra := extra.toNat, stack := rest, trap := s.trap - link.toNat} after := by
  apply dispatch_compose h.dispatch
  intro d dp
  obtain ⟨prefixCount, check, prefixRun, entered⟩ := reraise_quiet_setup h frame quiet stable dp
  have highRead : RamReadAt ((word check Layout.sym_Caml_state).toNat + Layout.off_stack_high) 8 := by
    simpa only [word, entered.memory] using quiet.highRead
  obtain ⟨checkCount, handler, checkRun, checked⟩ := raise_check entered.state stable
    (saved.frame entered.memory entered.nativeStack) highRead
  have memory := checked.memory.trans entered.memory
  have runtime : WindowStable L.runtimeOk [⟨(word handler Layout.sym_Caml_state).toNat + Layout.off_trapsp,
      (word handler Layout.sym_Caml_state).toNat + Layout.off_trapsp + 8⟩] := by
    simpa only [word, memory] using writeStable
  obtain ⟨handlerCount, after, handlerRun, result⟩ := raise_handler checked.state nonnegative runtime reads (space.frame memory)
  exact ⟨prefixCount + checkCount + handlerCount, after, (prefixRun.append checkRun).append handlerRun, result⟩

/-- Match the actual bytecode raise rule to the represented caught path. -/
theorem reraise_quiet_step_arm {L : OCaml.Layout} {P : Prog} {s s' : St} {pl : Place} {cp : ChanPlace}
    {sp high dest nativeSp : Nat} {link extra : BitVec 63} {env : Val} {rest : List Val} {c : Config}
    (h : ArmInput L P s .RERAISE c pl cp sp high) (frame : RaiseFrame s dest link env extra rest)
    (quiet : RaiseQuietReady high c) (stable : MemoryStable L.runtimeOk)
    (saved : RaiseStackFrame nativeSp c) (nonnegative : 0 ≤ extra.toInt)
    (writeStable : WindowStable L.runtimeOk [⟨(word c Layout.sym_Caml_state).toNat + Layout.off_trapsp,
      (word c Layout.sym_Caml_state).toNat + Layout.off_trapsp + 8⟩])
    (reads : RaiseFrameReads (high - 8 * s.trap))
    (space : TrapWriteOk P s c pl cp sp high (s.trap - link.toNat))
    (step : stepI P s ⟨.RERAISE, []⟩ = .next s') :
    ∃ after, Plus c after ∧ Running L P s' after := by
  have state := frame.state_of_step (by simpa only [stepI] using step)
  rw [← state]
  exact reraise_quiet_arm h frame quiet stable saved nonnegative writeStable reads space

end OCaml.Vm.Sim
