import Vsa.Sim.LibraryFacts
import Vsa.Sim.Code.CamlRestartCopyMore

/-! GENERATED by scripts/gen_arm_pilot.py. Store frame for local fetch pins. -/
namespace Vsa.Sim

theorem restart_copy_more_code_store (m : Std.ExtHashMap Nat (BitVec 8))
    (a : Nat) (v : BitVec 64)
    (outside : a + 8 ≤ 0x80002b94 ∨ 0x80002bb0 ≤ a)
    (loaded : Vsa.Sim.Code.CamlRestartCopyMoreLoaded m) :
    Vsa.Sim.Code.CamlRestartCopyMoreLoaded (writeMap8 m a (sdData_val v)) := by
  unfold Vsa.Sim.Code.CamlRestartCopyMoreLoaded Code.camlRestartCopyMoreChunk0 at loaded ⊢
  simpa only [
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b94 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b95 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b96 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b97 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b98 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b99 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b9a (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b9b (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b9c (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b9d (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b9e (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002b9f (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba0 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba1 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba2 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba3 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba4 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba5 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba6 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba7 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba8 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002ba9 (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002baa (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002bab (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002bac (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002bad (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002bae (by omega),
    getElem?_writeMap8_out m a (sdData_val v) 0x80002baf (by omega)] using loaded

end Vsa.Sim
