import OCaml.Vm.Sim.SmodPosReturnSites
import Vsa.Sim.SegState
import Vsa.Sim.StepCount
import Vsa.Sim.ChainFrameOut
import Vsa.Sim.PinLookup

/-!
GENERATED by scripts/gen_arm_pilot.py via scripts/syi/gen_segment.py — do not hand-edit; regenerate instead.
SMOD_POS_RETURN arm body, generated from the census. This is a machine segment, not yet ArmSim.next.
-/

open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail ConcurrencyInterfaceV1 Vsa
open Register
open Sail.ConcurrencyInterfaceV1.PreSail
open Vsa.Machine (MState Config Step Steps)
open Vsa.Logic



namespace Vsa.Sim

/-- SMOD_POS_RETURN arm body, generated from the census. This is a machine segment, not yet ArmSim.next. -/
theorem tr_smod_pos_return
    (v11 v5 : BitVec 64)
    (m0 : Std.ExtHashMap Nat (BitVec 8))
    (σ0 : MState)
    (htgt_80037330 : (BitVec.update (v5 + sign_extend (m := 64) (0x000#12)) 0 0#1).toNat % 4 = 0)
    : TripleN 2 (SegSt (0x8003732c#64) [⟨Register.x11, v11⟩, ⟨Register.x5, v5⟩]
      (fun σ => Vsa.Sim.Code.CamlSmodPosReturnLoaded σ.mem ∧ σ.mem = m0 ∧ σ = σ0)) (SegSt ((BitVec.update (v5 + sign_extend (m := 64) (0x000#12)) 0 0#1)) [⟨Register.x10, (v11 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, v11⟩, ⟨Register.x5, v5⟩]
      (fun σ => Vsa.Sim.Code.CamlSmodPosReturnLoaded σ.mem ∧ σ.mem = m0 ∧ StepFrameOut ((Register.x10 :: noiseRegs) ++ noiseRegs) σ0 σ)) := by
  intro c hPre
  obtain ⟨hgood, hpc, hp0, ⟨vmi, hmi⟩, htick, ⟨hloaded, hmemeq, hinitial⟩⟩ := hPre
  -- === step 1: 0x8003732c `site_8003732c_smod_pos_return` (alu) ===
  obtain ⟨σ1, i1, hs1, hi1, hG1, hmem1, hobs1⟩ :=
    site_8003732c_smod_pos_return c.σ c.tick (c.steps) (0x8003732c#64)
      vmi v11 hgood hpc hmi (PinsHold.get hp0 ⟨0, by simp⟩) hloaded rfl htick
  have hpc1 : σ1.regs.get? Register.PC = some (0x80037330#64 : BitVec 64) := by
    have := obs_alu_pc hobs1
    rwa [show BitVec.addInt (0x8003732c#64) 4 = (0x80037330#64 : BitVec 64) from by decide] at this
  have hrd1 : σ1.regs.get? Register.x10 = some (v11 + sign_extend (m := 64) (0x000#12)) :=
    obs_alu_rd hobs1 (by decide) (by decide) (by decide) (by decide) (by decide)
  have hp1 : PinsHold σ1 [⟨Register.x10, (v11 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, v11⟩, ⟨Register.x5, v5⟩] :=
    ⟨hrd1, pins_alu hobs1 (by rfl) hp0⟩
  obtain ⟨vmi1, hmi1⟩ := obs_alu_minstret hobs1
  have hmemE1 : σ1.mem = m0 := by
    rw [hmem1]; exact hmemeq
  have hload1 : Vsa.Sim.Code.CamlSmodPosReturnLoaded σ1.mem := by
    rw [hmem1]; exact hloaded
  -- === step 2: 0x80037330 `site_80037330_smod_pos_return` (jr) ===
  obtain ⟨σ2, i2, hs2, hi2, hG2, hmem2, hobs2⟩ :=
    site_80037330_smod_pos_return σ1 i1 (c.steps + 1) (0x80037330#64)
      vmi1 v5 hG1 hpc1 hmi1 (PinsHold.get hp1 ⟨2, by simp⟩) hload1 rfl htgt_80037330 hi1
  have hpc2 : σ2.regs.get? Register.PC = some (BitVec.update (v5 + sign_extend (m := 64) (0x000#12)) 0 0#1) := obs_jr_pc hobs2
  have hp2 : PinsHold σ2 [⟨Register.x10, (v11 + sign_extend (m := 64) (0x000#12))⟩, ⟨Register.x11, v11⟩, ⟨Register.x5, v5⟩] :=
    pins_jr hobs2 (by rfl) hp1
  obtain ⟨vmi2, hmi2⟩ := obs_jr_minstret hobs2
  have hmemE2 : σ2.mem = m0 := by
    rw [hmem2]; exact hmemE1
  have hload2 : Vsa.Sim.Code.CamlSmodPosReturnLoaded σ2.mem := by
    rw [hmem2]; exact hload1
  have hsteps2 : Steps c ⟨σ2, i2, c.steps + 1 + 1⟩ :=
    (Steps.single hs1).trans (Steps.single hs2)
  have hwhole : StepFrameOut ((Register.x10 :: noiseRegs) ++ noiseRegs) σ0 σ2 := by
    rw [← hinitial]
    chain_frame_out [hobs1, hobs2]
  have hcount : Vsa.Machine.StepsN 2 c ⟨σ2, i2, c.steps + 1 + 1⟩ :=
    hsteps2.toN_of_stepsEq rfl
  exact ⟨2, ⟨σ2, i2, c.steps + 1 + 1⟩, Nat.le_refl _, hcount,
    ⟨hG2, hpc2, hp2, ⟨vmi2, hmi2⟩, hi2, ⟨hload2, hmemE2, hwhole⟩⟩⟩

end Vsa.Sim
