#!/usr/bin/env python3
"""Project the allocator's balanced byte table from code and one loader word."""
import argparse
import re
from census import ROOT, symbols
from gen_ocaml_image import sections
from boot_certificate import emit_finite_family


def output():
    elf = ROOT / 'c/ocamlrun-riscv-htif.elf'
    address, size = symbols(elf)['_impure_ptr']
    if size != 8:
        raise ValueError('_impure_ptr is not an eight-byte word')
    raw = next(data[address-base:address-base+8] for base, data in sections(elf.read_bytes()).values()
               if base <= address and address+8 <= base+len(data))
    source = (ROOT / 'VsaIris/Vsa/AllocCode.lean').read_text()
    chunks = re.findall(r'^def (allocChunk\d+) :', source, re.M)
    nodes = re.findall(r'^def (allocNode\w+) : List \(Nat × BitVec 8\) :=\s+(\w+) \+\+ (\w+)$', source, re.M)
    root = re.search(r'^def allocText : List \(Nat × BitVec 8\) := (\w+)$', source, re.M).group(1)
    out = ['import OCaml.Vm.Boot.WhileMinImage', 'import OCaml.Vm.Platform',
           'import VsaIris.Vsa.AllocCode', '',
           '/-! GENERATED by scripts/gen_boot_allocator_pins.py. Bounded byte certificates. -/',
           'namespace OCaml.Vm.Boot.Startup',
           'open Vsa.Sim Vsa.Sim.Boot VsaIris.Sym', '',
           f'def allocatorImpureAddr : Nat := {address:#x}',
           'def allocatorImpureByte (i : Nat) : BitVec 8 :=', '  match i with']
    out += [f'  | {i} => {v:#x}#8' for i, v in enumerate(raw)] + ['  | _ => 0#8', '',
        '/-- Source of an allocator read-only pin: executable text or the fixed reentrancy pointer. -/',
        'def AllocatorByteSource (p : Nat × BitVec 8) : Prop :=',
        '  if p.1 < Image.textBase + Image.textSize then',
        '    Image.textBase ≤ p.1 ∧ Image.textByte (p.1 - Image.textBase) = p.2',
        '  else allocatorImpureAddr ≤ p.1 ∧ p.1 < allocatorImpureAddr + 8 ∧',
        '    allocatorImpureByte (p.1 - allocatorImpureAddr) = p.2', '',
        'instance (p : Nat × BitVec 8) : Decidable (AllocatorByteSource p) := by',
        '  unfold AllocatorByteSource', '  split <;> infer_instance', '',
        'private theorem covered_append {a b : List (Nat × BitVec 8)}',
        '    (ha : ∀ p ∈ a, AllocatorByteSource p) (hb : ∀ p ∈ b, AllocatorByteSource p) :',
        '    ∀ p ∈ a ++ b, AllocatorByteSource p := by',
        '  intro p hp', '  rcases List.mem_append.mp hp with hp | hp',
        '  · exact ha p hp', '  · exact hb p hp', '']
    for name in chunks:
        out += [f'private theorem {name}_covered : ∀ p ∈ {name}, AllocatorByteSource p := by',
                f'  have checked : {name}.all (fun p => decide (AllocatorByteSource p)) = true := by decide +kernel',
                '  exact fun p hp => of_decide_eq_true (List.all_eq_true.mp checked p hp)', '']
    for name, left, right in nodes:
        out += [f'private theorem {name}_covered : ∀ p ∈ {name}, AllocatorByteSource p :=',
                f'  covered_append {left}_covered {right}_covered', '']
    out += [f'theorem allocator_sources : ∀ p ∈ allocText, AllocatorByteSource p := {root}_covered', '']
    for i in range(8):
        out += [f'theorem allocator_impure_{i} :',
                f'    WhileMinImage.initialMem[allocatorImpureAddr + {i}]? = some (allocatorImpureByte {i}) :=',
                f'  (loaderMem_get WhileMinImage.pieces WhileMinImage.imageByte (allocatorImpureAddr + {i})).trans (by decide +kernel)', '']
    emit_finite_family(out, 'allocator_initial_impure', [f'allocator_impure_{i}' for i in range(8)],
                      lambda i: f'WhileMinImage.initialMem[allocatorImpureAddr + {i}]? = some (allocatorImpureByte {i})')
    out += ['end OCaml.Vm.Boot.Startup', '']
    return '\n'.join(out)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'OCaml/Vm/Boot/Startup/AllocatorPins.lean'
    text = output()
    if args.check:
        if not path.exists() or path.read_text() != text:
            raise SystemExit('allocator image projection drift')
    else:
        path.write_text(text)
