#!/usr/bin/env python3
"""Generate the F1 arm table (OCaml/Vm/Sim/F1Table.lean) from the row theorems.

Every F1 opcode's row is a theorem `<op>_row ... : OCaml.OpArm P (OCaml.LoopAt L P) .<OP>`
somewhere under OCaml/. This script finds each row, reads its parameters, and
emits:

* `F1Premises P`: the program-level premises the rows name (types copied from
  the row signatures, specialised to the pinned layout and budget), plus one
  field per F1 opcode that has no row yet;
* `f1_table`: `F1Arms P c (LoopAt Gc.f1Layout P)` from `Loaded`, `GoodF1`,
  `Fits` and `F1Premises`, dispatching every opcode to its row.

`--check` fails on drift (check_all stage a5).
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'OCaml/Vm/Sim/F1Table.lean'

NON_F1 = set('MAKEFLOATBLOCK GETFLOATFIELD SETFLOATFIELD VECTLENGTH GETVECTITEM SETVECTITEM '
             'GETBYTESCHAR SETBYTESCHAR GETSTRINGCHAR C_CALLN GETMETHOD GETPUBMET GETDYNMET '
             'EVENT BREAK'.split())

# Layout-level parameters: proved once for the pinned layout and budget.
FIXED = {
    'stable': 'f1_memoryStable',
    'rf': 'f1_runtimeFrame',
    'allocFrame': 'f1_allocFrame',
    'field': ('(fun s c reach h => f1_fieldWriteReady h.running.platform.runtime'
              ' (by simpa using stack_fits fits g1_capacity reach (k := 0)))'),
    'budgetSmall': 'f1_budgetSmall',
    'fits': 'fits',
    'capacity': 'g1_capacity',
    'good': 'good',
}
# Program-level parameters shared by several rows: one premise field each.
SHARED = {'values': 'values', 'ints': 'ints', 'extra': 'extra', 'extraBounded': 'extra',
          'raises': 'raises', 'exotic': 'exotic', 'trapBounded': 'trapBounded',
          'scratch': 'scratch', 'field': 'field'}
SUBST = [(r'\bL\b', 'Gc.f1Layout'), (r'\bB\b', 'Gc.g1Budget'),
         (r'\bhigh0\b', 'Gc.f1High'), (r'\bdom0\b', 'Gc.f1Domain')]


def opcodes():
    text = (ROOT / 'OCaml/Bytecode/Opcode.lean').read_text()
    ops = re.findall(r'^\s*\|\s*([A-Z_0-9]+)\s*$', text, re.M)
    return list(dict.fromkeys(ops))


def params(sig):
    """Explicit `(name : type)` binders of a signature, with balanced parens."""
    out, i = [], 0
    while True:
        j = sig.find('(', i)
        if j < 0:
            return out
        depth, k = 0, j
        while True:
            if sig[k] == '(':
                depth += 1
            elif sig[k] == ')':
                depth -= 1
                if depth == 0:
                    break
            k += 1
        body = sig[j + 1:k]
        m = re.match(r'(\w+) : (.*)$', body, re.S)
        if m:
            out.append((m.group(1), ' '.join(m.group(2).split())))
        i = k + 1


def rows():
    found = {}
    for f in sorted((ROOT / 'OCaml').rglob('*.lean')):
        if f == OUT:
            continue
        text = f.read_text()
        for m in re.finditer(r'^theorem ([A-Za-z0-9_.]+)((?:(?!^theorem).)*?)'
                             r'OCaml\.OpArm P \(OCaml\.LoopAt L P\) \.([A-Z_0-9]+)', text, re.M | re.S):
            name, sig, op = m.groups()
            if name.endswith('_row') and op not in found:
                mod = str(f.relative_to(ROOT))[:-5].replace('/', '.')
                found[op] = (name, params(sig), mod)
    return found


def spec(ty):
    for a, b in SUBST:
        ty = re.sub(a, b, ty)
    return ty


def render():
    ops = opcodes()
    found = rows()
    f1 = [o for o in ops if o not in NON_F1]
    fields, users, args, imports = {}, {}, {}, set()
    for op in f1:
        if op == 'STOP':
            args[op] = 'stop_row_f1 good'
            imports.add('OCaml.Vm.Sim.StopRow')
            continue
        if op not in found:
            fname = 'row_' + op
            fields[fname] = f'OCaml.OpArm P (OCaml.LoopAt Gc.f1Layout P) .{op}'
            users.setdefault(fname, []).append(op)
            args[op] = f'pre.{fname} (by simp [h])'
            continue
        name, ps, mod = found[op]
        imports.add(mod)
        call = [name]
        for p, ty in ps:
            if p in FIXED:
                call.append(FIXED[p])
            else:
                fname = SHARED.get(p, f'{op.lower()}_{p}')
                fields.setdefault(fname, spec(ty))
                users.setdefault(fname, []).append(op)
                call.append(f'(pre.{fname} (by simp [h]))')
        args[op] = ' '.join(call)
    lines = ['import ' + m for m in sorted(imports | {'OCaml.Vm.Sim.EntryF1', 'OCaml.Vm.Sim.F1Frame'})]
    lines += ['', '/-! GENERATED by scripts/gen_f1_table.py from the row theorems. The F1 arm',
              'table for the pinned layout: entry (`f1_entry`), and every F1 opcode dispatched',
              'to its row. Program-level premises the rows name, and the rows still open,',
              'are the named fields of `F1PremisesFor keep`, each needed only when an opcode',
              'using it is kept; opcodes the program never reaches (`keep` false) have',
              'vacuous rows (`OpArm.of_unreached`). -/', '',
              'namespace OCaml.Vm.Sim', 'set_option autoImplicit false',
              'open OCaml.Bytecode Vsa.Machine OCaml.Vm.Primitives', '',
              '/-- The G1 budget leaves both thresholds of slack on the VM stack. -/',
              'theorem g1_capacity : StackCapacity Gc.g1Budget := by unfold StackCapacity; decide', '',
              '/-- **Program-level premises of the F1 rows**, each guarded by the kept',
              'opcodes that use it, and the rows still open. -/',
              'structure F1PremisesFor (keep : Opcode → Bool) (P : Prog) : Prop where']
    for fname, ty in fields.items():
        guard = ' || '.join(f'keep .{o}' for o in users[fname])
        lines.append(f'  {fname} : ({guard}) = true → {ty}')
    lines += ['', '/-- All rows kept: the premises of the general F1 statement. -/',
              'abbrev F1Premises (P : Prog) : Prop := F1PremisesFor (fun _ => true) P', '',
              '/-- **The F1 arm table** for the pinned layout, for a program that only',
              'reaches kept opcodes. -/',
              'theorem f1_table_for {keep : Opcode → Bool} {P : Prog} {c : Config}',
              '    (loaded : OCaml.Loaded Gc.f1Layout P c) (good : OCaml.GoodF1 P)',
              '    (fits : OCaml.Fits Gc.g1Budget P)',
              '    (reached : ∀ s i, Reach P s → decodeAt P.code s.pc = some i → keep i.op = true)',
              '    (pre : F1PremisesFor keep P) :',
              '    OCaml.F1Arms P c (OCaml.LoopAt Gc.f1Layout P) where',
              '  entry := f1_entry loaded',
              '  arm op hop := match op, hop with']
    for op in ops:
        if op in NON_F1:
            lines.append(f'    | .{op}, h => absurd h (by decide)')
        elif op == 'STOP':
            lines.append(f'    | .{op}, _ => {args[op]}')
        else:
            lines.append(f'    | .{op}, _ => if h : keep .{op} = true then {args[op]}')
            lines.append(f'        else OCaml.OpArm.of_unreached fun s i r d e => h (e ▸ reached s i r d)')
    lines += ['', '/-- **The F1 arm table** for the pinned layout. -/',
              'theorem f1_table {P : Prog} {c : Config} (loaded : OCaml.Loaded Gc.f1Layout P c)',
              '    (good : OCaml.GoodF1 P) (fits : OCaml.Fits Gc.g1Budget P) (pre : F1Premises P) :',
              '    OCaml.F1Arms P c (OCaml.LoopAt Gc.f1Layout P) :=',
              '  f1_table_for loaded good fits (fun _ _ _ _ => rfl) pre', '',
              'end OCaml.Vm.Sim', '']
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    text = render()
    if a.check:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit('F1 table generator drift: OCaml/Vm/Sim/F1Table.lean')
        print('F1 table current')
    else:
        OUT.write_text(text)
        print('wrote', OUT.relative_to(ROOT))


if __name__ == '__main__':
    main()
