#!/usr/bin/env python3
"""Generate the shared GETBYTESCHAR/GETSTRINGCHAR represented byte-read pattern."""
import argparse
import json
from census import ROOT


def outputs():
    result = {}
    for op in ['GETBYTESCHAR', 'GETSTRINGCHAR']:
        stem, lower = op.title(), op.lower()
        spec = json.loads((ROOT / f'scripts/syi/segments/{lower}.json').read_text())
        result[ROOT / f'OCaml/Vm/Sim/{stem}.lean'] = f'''import OCaml.Vm.Sim.StackConsume
import OCaml.Vm.Sim.ByteRead
import OCaml.Vm.Sim.ValueIndex
import OCaml.Vm.Sim.{stem}Segment
import OCaml.Vm.Sim.{stem}Pins

/-! GENERATED by scripts/gen_byte_arms.py. Represented byte-indexed load. -/
namespace OCaml.Vm.Sim
set_option autoImplicit false
open OCaml.Bytecode Vsa.Machine Vsa.Sim LeanRV64DExecutable LeanRV64DExecutable.Functions
open OCaml.Vm.Primitives

/-- {op} consumes its index and returns the represented unsigned byte.
The byte read window itself bounds the native untagged index. -/
theorem {lower}_arm {{L : OCaml.Layout}} {{P : Prog}} {{s : St}} {{c : Config}}
    {{pl : Place}} {{cp : ChanPlace}} {{sp high l a : Nat}} {{n : BitVec 63}}
    {{b : UInt8}} {{bs : List UInt8}} {{rest : List Val}}
    (stable : MemoryStable L.runtimeOk)
    (h : ArmInput L P s .{op} c pl cp sp high)
    (stack : s.stack = .int n :: rest)
    (selected : ByteSelection s.heap pl s.accu n.toNat b l a bs)
    (stackRead : RamReadAt sp 8)
    (byteRead : RamReadAt (a + n.toNat) 1) :
    ∃ c', Plus c c' ∧ Running L P
      {{s with pc := s.pc + 1, accu := .int (BitVec.ofNat 63 b.toNat), stack := rest}} c' := by
  have value := ByteSelection.read h.toVmReprAt (by simp [roots]) selected
  have source := represented_register h.accu selected.sourceWord
  have slot := stack_integer_word h.toVmReprAt stack
  have small : n.toNat < 2^62 := by have upper := byteRead.upper; omega
  have bound : 1 ≤ s.stack.length := by simp [stack]
  have dropped : s.stack.drop 1 = rest := by simp [stack]
  rw [← dropped]
  apply consume_arm stable h bound
  intro d dp
  have loaded : sign_extend (m := 64) (bytesT8 d.σ.mem sp) = tag64 n := by
    simpa only [dp.memory, word, bytesT_eight_eq, sign_extend,
      Sail.BitVec.signExtend, BitVec.signExtend_eq] using slot
  have loadedByte : bytesT1 d.σ.mem (a + n.toNat) = BitVec.ofNat 8 b.toNat := by
    rw [dp.memory]
    change (c.σ.mem[a + n.toNat]?).getD 0 = _
    rw [← byte_total]
    exact value
  have byteNat : (BitVec.ofNat 8 b.toNat).toNat = b.toNat :=
    Nat.mod_eq_of_lt b.toBitVec.isLt
  have address : BitVec.ofNat 64 n.toNat + BitVec.ofNat 64 a =
      BitVec.ofNat 64 (a + n.toNat) := by
    rw [BitVec.add_comm, BitVec.ofNat_add]
  have bp : SegSt ({spec['entry']}#64)
      [⟨Register.x9, BitVec.ofNat 64 sp⟩,
       ⟨Register.x23, BitVec.ofNat 64 (pl.codeBase + 4 * s.pc) + 4#64⟩,
       ⟨Register.x21, BitVec.ofNat 64 a⟩]
      (fun σ => Vsa.Sim.Code.Caml{stem}Loaded σ.mem ∧ σ.mem = d.σ.mem ∧ σ = d.σ) d :=
    ⟨dp.good, dp.pc,
      ⟨(dp.frame.frame Register.x9 (by decide)).trans h.spReg, dp.nextCode,
       (dp.frame.frame Register.x21 (by decide)).trans source, trivial⟩,
      dp.good.minstret, dp.tick, {lower}_loaded (dp.image h.dispatch.image), rfl, rfl⟩
  have run := tr_{lower} (BitVec.ofNat 64 sp)
    (BitVec.ofNat 64 (pl.codeBase + 4 * s.pc) + 4#64)
    (BitVec.ofNat 64 a) d.σ.mem d.σ
  simp only [show sign_extend (m := 64) (0x000#12) = 0#64 from by decide,
    show sign_extend (m := 64) (0x008#12) = 8#64 from by decide,
    show sign_extend (m := 64) (0x001#12) = 1#64 from by decide,
    BitVec.add_zero, stackRead.toNat, loaded, value_byte_index n small,
    address, byteRead.toNat, loadedByte, byte_tag, byteNat] at run
  obtain ⟨nb, after, _, hb, post⟩ := run stackRead.lower stackRead.upper stackRead.htif
    byteRead.lower byteRead.upper byteRead.htif d bp
  obtain ⟨_, hm, frame⟩ := post.extra
  refine ⟨nb, after, hb, post.good, post.pcAt, ?_, ?_, ?_, hm, frame.out, ?_⟩
  · have hp : gpr after Layout.reg_pc = some
        (BitVec.ofNat 64 (pl.codeBase + 4 * s.pc) + 4#64) :=
      PinsHold.get post.pins ⟨3, by simp⟩
    simpa only [codePc_succ] using hp
  · have hp : gpr after Layout.reg_sp = some (BitVec.ofNat 64 sp + 8#64) :=
      PinsHold.get post.pins ⟨2, by simp⟩
    simpa only [Nat.mul_one, BitVec.ofNat_add] using hp
  · exact PinsHold.get post.pins ⟨0, by simp⟩
  · intro r hr
    exact frame.frame r (by revert r; decide)

end OCaml.Vm.Sim
'''
    return result


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    for p, text in outputs().items():
        if args.check:
            if not p.exists() or p.read_text() != text:
                raise SystemExit(f'byte arm drift: {p.relative_to(ROOT)}')
        else:
            p.write_text(text)
    print('Byte-read arm bridges current')
