#!/usr/bin/env python3
"""Generate the initial while_min image from the emulator's ELF-piece dump.

Capture input with the capped command:
  lake env lean --run scripts/boot_elf_pieces.lean ELF > pieces.json
Then run --capture ELF --pieces pieces.json. The default/check paths use
that archived dump, and cross-check immutable bytes against the pinned ELF.
"""
import argparse
import gzip
import hashlib
import json
from pathlib import Path
from gen_ocaml_image import sections
from packed_bytes import emit_packed_bytes

ROOT=Path(__file__).resolve().parents[1]
ap=argparse.ArgumentParser(description=__doc__)
ap.add_argument('--capture',type=Path)
ap.add_argument('--pieces',type=Path)
ap.add_argument('--check',action='store_true')
ap.add_argument('--expected-memory',type=Path,help='write sorted address/byte rows for bootdump validation')
args=ap.parse_args()
archive=ROOT/'results/boot/while_min-initial.json.gz'
cut=json.loads((ROOT/'results/boot/while_min-cut.json').read_text())
if args.capture:
    assert args.pieces and not args.check
    sha=hashlib.sha256(args.capture.read_bytes()).hexdigest()
    assert sha==cut['elf_sha256']
    data={'elf_sha256':sha,'pieces':json.loads(args.pieces.read_text())}
    archive.write_bytes(gzip.compress(json.dumps(data,separators=(',',':')).encode(),mtime=0))
data=json.loads(gzip.decompress(archive.read_bytes()))
assert data['elf_sha256']==cut['elf_sha256']
pieces=[(a,bytes(bs)) for a,bs in data['pieces'] if bs]
for i,(a,bs) in enumerate(pieces):
    assert all(a+len(bs)<=b or b+len(cs)<=a for b,cs in pieces[:i])
fixed=sections((ROOT/'c/ocamlrun-riscv-htif.elf').read_bytes())
for name in ['.text','.rodata']:
    base,bs=fixed[name]
    matches=[body[base-a:base-a+len(bs)] for a,body in pieces if a<=base and base+len(bs)<=a+len(body)]
    assert matches==[bs],f'{name} differs from pinned runtime'
out=['import OCaml.Vm.ImageData','import Vsa.Sim.Boot.Image','',
     '/-! GENERATED by scripts/gen_boot_image.py from the emulator ELF loader dump.',
     f'Observed ELF SHA256: {data["elf_sha256"]}. No execution claim. -/',
     'namespace OCaml.Vm.Boot.WhileMinImage','open Vsa.Sim.Boot','']
for k,(base,raw) in enumerate(pieces):
    body=bytearray(raw)
    for name in ['.text','.rodata']:
        b,bs=fixed[name]
        if base<=b and b+len(bs)<=base+len(body):body[b-base:b-base+len(bs)]=bytes(len(bs))
    emit_packed_bytes(out, f'piece{k}', body)
out += ['def pieces : List (Nat × Nat) := ['+', '.join(f'({a:#x}, {len(b)})' for a,b in pieces)+']',
        'def imageByte (a : Nat) : BitVec 8 :=',
        '  if Image.textBase ≤ a ∧ a < Image.textBase + Image.textSize then Image.textByte (a - Image.textBase)',
        '  else if Image.rodataBase ≤ a ∧ a < Image.rodataBase + Image.rodataSize then Image.rodataByte (a - Image.rodataBase)']
for k,(a,bs) in enumerate(pieces):
    out.append(f'  else if {a:#x} ≤ a ∧ a < {a+len(bs):#x} then piece{k}Byte (a - {a:#x})')
out += ['  else 0','', 'def initialMem : Vsa.MemRepr.Mem := loaderMem pieces imageByte',
        'end OCaml.Vm.Boot.WhileMinImage','']
path=ROOT/'OCaml/Vm/Boot/WhileMinImageData.lean'
text='\n'.join(out)
if args.check:
    if not path.exists() or path.read_text()!=text:raise SystemExit('boot image data drift')
elif not path.exists() or path.read_text()!=text:path.write_text(text)
print(f'Initial image: {len(pieces)} pieces, {sum(len(b) for _,b in pieces)} bytes')

# Small startup observations from the same loader view, checked independently
# of both the execution trace and the captured cut state.
import re
layout = (ROOT / 'OCaml/Vm/Layout.lean').read_text()
header = int(re.search(r'def sym_embedded_env : Nat := (0x[0-9a-fA-F]+|[0-9]+)', layout).group(1), 0)
def image_read(a, n):
    return next(body[a-base:a-base+n] for base, body in pieces if base <= a and a+n <= base+len(body))
env = int.from_bytes(image_read(header, 8), 'little')
entry = int.from_bytes(image_read(env, 8), 'little')
name = b'OCAMLRUNPARAM='
assert image_read(entry, len(name)+1) == name + b'\0'
assert int.from_bytes(image_read(env+8, 8), 'little') == 0
cert = ['import OCaml.Vm.Boot.WhileMinImageData', 'import OCaml.Vm.Layout',
        'import Vsa.Sim.Boot.Bytes', '',
        '/-! GENERATED by scripts/gen_boot_image.py. Bounded environment reads, no run evaluation. -/',
        'namespace OCaml.Vm.Boot.WhileMinImage', 'open Vsa.Sim Vsa.Sim.Boot', '',
        f'def envArray : Nat := {env:#x}', f'def envEntry : Nat := {entry:#x}',
        f'def envValue : Nat := {entry+len(name):#x}', '']
for stem, address, width, value in [('env_header', 'Layout.sym_embedded_env', 8, env),
                                  ('env_first', 'envArray', 8, entry),
                                  ('env_end', 'envArray + 8', 8, 0),
                                  ('env_value', 'envValue', 1, 0)]:
    cert += [f'theorem {stem} : bytesT initialMem ({address}) {width} = {value:#x}#{8*width} :=',
             f'  (loaderMem_bytes pieces imageByte ({address}) {width}).trans (by decide +kernel)', '']
cert += ['theorem env_not_empty : bytesT initialMem envArray 8 ≠ 0#64 := by',
         '  rw [env_first]; decide', '', 'end OCaml.Vm.Boot.WhileMinImage', '']
certpath = ROOT / 'OCaml/Vm/Boot/WhileMinEnvironment.lean'
certtext = '\n'.join(cert)
if args.check:
    if not certpath.exists() or certpath.read_text() != certtext: raise SystemExit('boot environment drift')
elif not certpath.exists() or certpath.read_text() != certtext: certpath.write_text(certtext)


if args.expected_memory:
    memory = {a+i:b for a,body in pieces for i,b in enumerate(body)}
    for _,a,n,v in map(json.loads,gzip.open(ROOT/'results/boot/while_min-stores.jsonl.gz')):
        for i in range(n):memory[a+i]=(v>>(8*i))&255
    args.expected_memory.write_bytes(b''.join(a.to_bytes(8,'little')+bytes([b])
        for a,b in sorted(memory.items())))
    print(f'Expected memory: {len(memory)} bytes')
