#!/usr/bin/env python3
"""Regenerate preserved stdio proof templates (with explicit import cuts)."""
import argparse
import json
import re
from stdio_layout import layout
from gen_stdio_image import image_source
from stdio_steps import retarget_steps
from retarget_allocator_specs import rewrite_auipc_values
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / 'experiments/syi/stdio-template'


def outputs(include_pending=False):
    checked = set(json.loads((TEMPLATES / 'checked-modules.json').read_text()))
    old,new,syms,secs,relocate,expansions,offsets = layout()
    result = {}
    for p in sorted(TEMPLATES.rglob('*.lean')):
        rel = p.relative_to(TEMPLATES)
        module = '.'.join(rel.with_suffix('').parts)
        if not include_pending and module not in checked:
            continue
        s = p.read_text()
        if module == 'VsaIris.Vsa.LibraryStdioFoot':
            names=['__sglue','global_locale_string','__global_locale','__default_locale','_impure_data',
                   'environ','_impure_ptr','__atexit_recursive_mutex','initial_env','__stdio_exit_handler',
                   '_PathLocale','__atexit','__sf','saved_categories.0','new_categories.1','__atexit0']
            names += [n for n in syms if n.startswith('__lock___')]
            ranges=[]
            for n in names:
                a,z=syms[n]
                assert z>0,(n,a,z)
                ranges.append((a+(4 if n=='_impure_data' else 0),a+z))
            merged=[]
            for a,b in sorted(ranges):
                if merged and a<=merged[-1][1]:merged[-1]=(merged[-1][0],max(b,merged[-1][1]))
                else:merged.append((a,b))
            s=s.replace('STDIO_RANGES',' ∨\n  '.join(f'InRange 0x{a:x} 0x{b:x} a' for a,b in merged))
        if '.SnpSteps.' in module:
            s = retarget_steps(s,old,new,syms,relocate,expansions)
        if module.rsplit('.',1)[-1] in ['SnpCtx','SnpMove','SnpPuts','SnpPrint','SnpStrlen','SnpArith','SnpSvf','SnpSvfConv','SnpSvfLoop','SnpFormatSupport','SnpFmt']:
            ow={i[0]:i[1] for f in old['functions'].values() for i in f['insts']}
            nw={i[0]:i[1] for f in new.values() for i in f['insts']}
            s=rewrite_auipc_values(s,ow,nw,relocate)
            def addr(m):
                a=int(m[0],16)
                if a in offsets:return f'0x{offsets[a]:x}'
                return f'0x{relocate(a):x}' if 0x80000000<=a<0x90000000 else m[0]
            s=re.sub(r'(?<![a-zA-Z0-9_])([0-9]+)(?![a-zA-Z0-9_])',lambda m:str(relocate(int(m[0]))) if 0x80000000<=int(m[0])<0x90000000 else m[0],s)
            s=re.sub(r'0x[0-9a-fA-F]+',addr,s)
            s=re.sub(r'(?<=_)800[0-9a-f]{5}(?=\b|_)',lambda m:f'{relocate(int(m[0],16)):08x}',s)
        if module == 'VsaIris.Vsa.SnpCode':
            s = re.sub(r'0x[0-9a-fA-F]+', lambda m: f'0x{relocate(int(m[0],16)):x}', s)
            result[ROOT/'VsaIris/Vsa/SnpImage.lean'] = image_source(old,new,secs,relocate)
        s = '-- GENERATED by scripts/retarget_stdio_specs.py; edit its templates.\n' + s
        if s.count('∃') > 8:
            s = '-- discipline: allow(R7-conj-tower-def) preserved upstream stdio contracts\n' + s
        s = '\n'.join(('-- discipline: allow(R6-anon-projection-tower) preserved upstream stdio invariant projection\n' if '.2.2.2.2' in line else '') + line for line in s.split('\n'))
        result[ROOT / rel] = s
    return result


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--include-pending', action='store_true')
    args = ap.parse_args()
    files = outputs(args.include_pending)
    bad = []
    for p, s in files.items():
        if args.check:
            if not p.exists() or p.read_text() != s:
                bad.append(str(p.relative_to(ROOT)))
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(s)
    if bad:
        raise SystemExit('Stdio proof drift: ' + ', '.join(bad))
    print(f'Stdio templates: {len(files)} modules')
